### ISSUE TITLE
Heroku client internal error on 'logs' command

### ISSUE THREAD

**Issue by rayascott** [heroku/heroku#1026]
Below is the output I get when I attempt to run the 'heroku logs' command from my app root. Other heroku commands run just fine. 

[14:07:58] rayscott@cortex:~/Developer/.../GitHub/Runways-fluentd $ heroku logs
/Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918: warning: exception in verify_callback is ignored
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
    Backtrace:   /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect'
                 /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
                 /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
                 /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:918:in `connect'
                 /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
                 /Users/rayscott/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/client.rb:616:in `process'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/client.rb:594:in `get'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/client.rb:484:in `read_logs'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/helpers/log_displayer.rb:19:in `display_logs'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/command/logs.rb:33:in `index'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/command.rb:218:in `run'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/lib/heroku/cli.rb:28:in `start'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/gems/heroku-3.3.0/bin/heroku:17:in `<top (required)>'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/bin/heroku:23:in `load'
                 /Users/rayscott/.rvm/gems/ruby-2.0.0-p247@runways-fluentd/bin/heroku:23:in `<main>'

    Command:     heroku logs
    Version:     heroku-gem/3.3.0 (x86_64-darwin12.3.0) ruby/2.0.0

**Comment by phikal** [comment]
Did you manage fix this?

**Comment by dickeyxxx** [comment]
upgrade your version of the toolbelt, your version is very old

**Comment by phikal** [comment]
Well, the issue was from 2014...

**Comment by dickeyxxx** [comment]
oh I missed that

**Comment by phikal** [comment]
Anyway, I managed to fix it on Fedora 22 by updating my certificates and reinstalling heroku via gem.
