### ISSUE TITLE
Help! Can't connect to Heroku: Unable to connect to Heroku API, please check internet connectivity and try again.

### ISSUE THREAD

**Issue by starrychloe** [heroku/heroku#1046]
My Heroku client stopped working all of a sudden. It always gives this error.

C:\Users\Chloe\workspace\Tyger>heroku version
heroku/toolbelt/3.4.3 (i386-mingw32) ruby/1.9.3

C:\Users\Chloe\workspace\Tyger>heroku status
 !    Unable to connect to Heroku API, please check internet connectivity and try again.

I can push to Heroku through Git just fine. I also re-installed it, but it didn't help.

I also entered a ticket: https://help.heroku.com/tickets/112947

I also entered a StackOverflow question: http://stackoverflow.com/questions/22276121/unable-to-connect-to-heroku-api-please-check-internet-connectivity-and-try-agai

**Comment by VRanga000** [comment]
FYI - my issue was that I had the env var http_proxy set. This is likely to be an issue for others using it behind a corp vpn.

**Comment by andr3wll** [comment]
I use the heroku toolbelt from homebrew and get the same issue. In my case installing the version from https://toolbelt.heroku.com/ can solve the issue.

**Comment by JohnsonMatsiko** [comment]
Ive just installed the version from https://toolbelt.heroku.com/ and it still won't work.

**Comment by dickeyxxx** [comment]
if you get this error this means that we are either having a serious outage (check status.heroku.com) or it's an issue with the internet connection on your side. On Unix you can run `curl https://status.heroku.com/api/v3/current-status.json` to check for any errors. You may need to setup your proxy.

**Comment by Shekharrajak** [comment]
Same problem here .Don't know what to do.

**Comment by jigdevelopment** [comment]
This things happen after set  proxy environment...
