### ISSUE TITLE
error adding SSL

### ISSUE THREAD

**Issue by mezderman** [heroku/heroku#1087]
resolving trust chain... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Expected(200) <=> Actual(500 InternalServerError) (Excon::Errors::InternalServerError)
    Backtrace:   /usr/local/heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/expects.rb:10:in `response_call'
                 /usr/local/heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/response_parser.rb:8:in `response_call'
                 /usr/local/heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:349:in `response'
                 /usr/local/heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:247:in `request'
                 /usr/local/heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:284:in `post'
                 /Users/mezderman/.heroku/client/lib/heroku/command/certs.rb:197:in `block in post_to_ssl_doctor'
                 /Users/mezderman/.heroku/client/lib/heroku/helpers.rb:227:in `action'
                 /Users/mezderman/.heroku/client/lib/heroku/command/certs.rb:195:in `post_to_ssl_doctor'
                 /Users/mezderman/.heroku/client/lib/heroku/command/certs.rb:204:in `read_crt_and_key_through_ssl_doctor'
                 /Users/mezderman/.heroku/client/lib/heroku/command/certs.rb:220:in `read_crt_and_key'
                 /Users/mezderman/.heroku/client/lib/heroku/command/certs.rb:72:in `add'
                 /Users/mezderman/.heroku/client/lib/heroku/command.rb:218:in `run'
                 /Users/mezderman/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/local/heroku/bin/heroku:24:in `<main>'

    Command:     heroku certs:add sslCert-_narrative_is.crt server.key
    Version:     heroku-toolbelt/3.6.0 (x86_64-darwin10.8.0) ruby/1.9.3

**Comment by mjankowski** [comment]
I had this issue today as well.

Uninstalling the toolbelt binary, and then installing the `heroku` gem fixed the issue for me.

**Comment by sindrenm** [comment]
I'm getting the same both with the toolbelt and the gem:

## Toolbelt error output:

```
$ heroku certs:add certificate.pem server.key -r production
Resolving trust chain... failed

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Expected(200) <=> Actual(500 InternalServerError)
 (Excon::Errors::InternalServerError)
    Command:     heroku certs:add certificate.pem server.key -r production
    Plugins:     heroku-deploy
                 heroku-pages

    Version:     heroku-toolbelt/3.36.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    bdbfbf8d158c40a0a257e0ea582d4805
```

## Gem error output:

```
$ heroku certs:add certificate.pem server.key -r production
Resolving trust chain... failed

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Expected(200) <=> Actual(500 InternalServerError)
 (Excon::Errors::InternalServerError)
    Command:     heroku certs:add certificate.pem server.key -r production
    Plugins:     heroku-deploy
                 heroku-pages

    Version:     heroku-gem/3.36.6 (x86_64-darwin14) ruby/2.2.2
    Error ID:    dbcde9abf83440f19807eeef58e45722
```

**Comment by acmisiti** [comment]
I am seeing this exact issue still when adding an ssl certificate. The heroku gem is outdated now so any other solution suggestions?

**Comment by ransombriggs** [comment]
@acmisiti what is the output of `heroku version`?

**Comment by acmisiti** [comment]
```heroku-toolbelt/3.42.23 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.27.7-135a760 (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-apps@1.0.0
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.4
heroku-local@4.1.5
heroku-run@2.9.2
heroku-status@1.2.3```
