### ISSUE TITLE
auth:whoami should fail if not logged in

### ISSUE THREAD

**Issue by listrophy** [heroku/heroku#1149]
There doesn't seem to be any way in the entire toolbelt to determine _whether_ I'm logged in without triggering an interactive login.

I'd like for `heroku auth:whoami` to return with exit status > 0 when not logged in. The actual output in such a case is up to you.

Context: I'm writing a script that calls `heroku config`, and I'd like to provide a helpful error message.

**Comment by camstuart** [comment]
Agreed. I'm trying to automate the login process, but if there is no current user logged in, an ```auth:login``` triggers. Which is a bit annoying

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku/pull/1598
