### ISSUE TITLE
Two factor auth breaks fork

### ISSUE THREAD

**Issue by brandur** [heroku/heroku#1158]
Fork doesn't recognize the 2nd factor hint and blows up with something obscure like:

```
$ heroku sudo fork -a myapp
Failed to fork app myapp to myapp-633.

 !    WARNING: Potentially Destructive Action
 !    This command will destroy myapp-633 (including all add-ons).
 !    To proceed, type "myapp-633" or re-run this command with --confirm myapp-633

>
```

/cc @jacobian @pedro

**Comment by hunterloftis** [comment]
Just ran into this. Anybody come up with workarounds?

**Comment by dickeyxxx** [comment]
I can look into fixing it with the fork replacement

**Comment by dickeyxxx** [comment]
actually this brings up something possibly important. @jacobian @brandur are people forking under sudo?

**Comment by hunterloftis** [comment]
@dickeyxxx I would like to fork with sudo (for support tickets).

**Comment by dickeyxxx** [comment]
@friism just wanted to point this out, I'll have to take a look at this issue next week

**Comment by friism** [comment]
@dickeyxxx do you need any help here?

**Comment by dickeyxxx** [comment]
working on it, I need to add 2fa into v4

**Comment by tucsonalama** [comment]
any updates on this?  This is causing problems for a number of scripted deployments I have.

**Comment by tucsonalama** [comment]
any updates on this?  This is causing problems for a number of scripted deployments I have.

**Comment by dickeyxxx** [comment]
nothing yet, I need to fix the new fork implementation here https://github.com/heroku/heroku-fork and include the fixes around 2fa

**Comment by dickeyxxx** [comment]
this is now fixed
