### ISSUE TITLE
deployhooks:email settings aren't copied with fork

### ISSUE THREAD

**Issue by seanknox** [heroku/heroku#1203]
Forked an app with `deployhooks:email` as so:

``` bash
heroku fork -a source_app new_app
```

And got this error:

``` bash
Creating fork new_app... done
Copying slug... done
Adding deployhooks:email... skipped (email hook is missing config: recipient)
Adding flydata:feather... done
Adding logentries:tryit... done
...
```

Just to confirm: recipient is indeed set on `source app`'s deployhooks:email addon.

**Comment by trimble** [comment]
This issue looks stale.

I will attempt to recreate, but can you tell us if it's still a problem?

Thanks!

**Comment by seanknox** [comment]
No longer using this feature so can't say. Thanks for checking in, closing.
