### ISSUE TITLE
Not behind proxy but cannot run console

### ISSUE THREAD

**Issue by josegrad** [heroku/heroku#1240]
In order to connect to the internet in the place I'm right now I need to provide a username and password. You know like in the airports.

This tells me I'm not behind a proxy: http://amibehindaproxy.com/

All programs seem to connect to the network except for Heroku client. I can push to heroku but I cannot run console or bash. (tried heroku run:detached but didn't help)

Any hints how to fix this? 
I'm sitting here a few hours a week and hit every day the same issue.

Thanks.

**Comment by zackster** [comment]
At an airport.  Port 5000 is blocked.  But port ssh is open.  So I ssh'd into one of my VPs and installed the heroku-cli there.
