### ISSUE TITLE
Heroku client internal error. | heroku pgbackups

### ISSUE THREAD

**Issue by clivecrous** [heroku/heroku#1250]
% heroku pgbackups
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
    Backtrace:   /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/net/http.rb:918:in `connect'
                 /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
                 /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
                 /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/net/http.rb:918:in `connect'
                 /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
                 /home/x/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/net/http.rb:851:in `start'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/rest_client-1.7.3/lib/restclient/request.rb:182:in `transmit'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/rest_client-1.7.3/lib/restclient/request.rb:68:in `execute'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/rest_client-1.7.3/lib/restclient/request.rb:35:in `execute'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/rest_client-1.7.3/lib/restclient/resource.rb:51:in `get'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/client/pgbackups.rb:69:in `block in get'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/client/pgbackups.rb:92:in `check_errors'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/client/pgbackups.rb:68:in `get'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/client/pgbackups.rb:30:in `get_transfers'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/command/pgbackups.rb:20:in `index'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/command.rb:217:in `run'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/lib/heroku/cli.rb:38:in `start'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/gems/heroku-3.15.0/bin/heroku:17:in `<top (required)>'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/bin/heroku:23:in `load'
                 /home/x/Repositiories/y/.vendor/ruby/2.0.0/bin/heroku:23:in `<main>'

    Command:     heroku pgbackups
    Version:     heroku-gem/3.15.0 (x86_64-linux) ruby/2.0.0

**Comment by EnriqueV** [comment]
hello, please help me i have a problem with:
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
    Command:     heroku open
    Version:     heroku-toolbelt/3.30.6 (i486-linux) ruby/1.9.3
    Error ID:    1dbf422d620848d5ad093bd07b8feeea


    More information in /root/.heroku/error.log
