### ISSUE TITLE
How do I pass -a and -c arguments to `heroku run` scripts?

### ISSUE THREAD

**Issue by aseemk** [heroku/heroku#1264]
I want to run a command which has `-a` and `-c` parameters on an app whose git remote is `staging`. Here is my attempt:

```
$ heroku run some-script.sh -a foo -c bar -r staging
 !    Mismatch between --app and --confirm
```

This issue is present even if I remove the `-c` argument:

```
$ heroku run some-script.sh -a foo -r staging
 !    App not found
```

I'm able to get it to work by quoting everything... but this is a [currently known bug](https://github.com/heroku/toolbelt/issues/51) in the CLI:

```
$ heroku run "some-script.sh -a foo -c bar" -r staging
Running `some-script.sh -a foo -c bar` attached to terminal... up, run.1234
```

If it helps:

```
$ heroku --version
heroku-toolbelt/3.15.2 (x86_64-darwin10.8.0) ruby/1.9.3
```

Thanks!

**Comment by dickeyxxx** [comment]
this is supported, but you'll need to use the `--exit-code` flag to use the new implementation right now. Use `--` to separate your flags.

`heroku run --exit-code -r staging -- some-script.sh -a foo -c bar`
