### ISSUE TITLE
Hypotesis: heroku-cli 3.20.0 fails on auto-update

### ISSUE THREAD

**Issue by pjmolina** [heroku/heroku#1332]
**Facts**

A. Using v. 3.20.0 on two windows machines got:
```
>heroku version
heroku/toolbelt/3.20.0 (i386-mingw32) ruby/1.9.3

>heroku update
updating... !    Unable to connect to Heroku API, please check internet connectivity and try again.
```

B. Doing the same update operation on another windows machine with version 3.12.0 worked.

**Hypotesis**
Therefore, that explains the title of the issue.
- Double check 3.21.0 (the current) and if other version are affected of this bug also when version n+1 is available.

**Workaround**
Uninstall heroku-toolbelt v. 3.20.0 and reinstall it.

**Comment by dickeyxxx** [comment]
I'm pretty sure this came from an ssl error on windows with s3. I moved the updating to use http since it performs a checksum validation anyways.
