### ISSUE TITLE
piping to heroku run echoes all output and then stops abruptly

### ISSUE THREAD

**Issue by timdiggins** [heroku/heroku#1336]
Like others I want to pipe in long files to a heroku run process (rather than send via a dyno/controller, or put it into csv).

However heroku CLI (up to and including 3.21.1) doesn't seem to deal well with files beyond a particular size. 

Typically I'm running a thor task on the heroku process, but for clarity we can just run a word count:

`cat some-file | heroku run wc -`

we can directly then compare this with 

`cat some-file | wc -`
  and
`cat some-file | ssh SOMESERVER  wc -`

First odd behaviour is that the toolbelt echoes back the piped input into stdout of my local process. (This has been observed by others for a while: http://stackoverflow.com/questions/25774249/can-you-pipe-to-heroku-run-without-it-echoing-the-text-back). I've observed that it echoes back the stdin content somewhat interleaved with the ongoing stdout of the heroku process (not observable with `wc` but observable with custom thor commands)

More importantly, if the file is large enough (49k > x > 61k in my recent tests, but about a year ago I estimated this as a lot smaller), then it stops abruptly part way through the process. I'm wondering what this constraint is, why it occurs...

Further, by checking with a custom thor script I can tell that if the script outputs response during processing, then the maximum size of piped stdin decreases (I'm guessing this is because there is some kind of total size for the output, including the echoed stdin). 

Sample thor script:

```
class Data < Thor

  desc "count_lines", "counts lines in stdin"
  option :verbose, type: :boolean, aliases: [:v]
  def count_lines
    row_count =0
    $stdin.each_line do | line |
      row_count +=1
      puts "##{row_count}" if options[:verbose]
    end
    puts "#{row_count} rows read"
  end

end
```

**Comment by jpaas** [comment]
I am having the same issue here. Trying to pipe a 36kb JSON file to be parsed by a rake task. It always fails parsing because the contents of the file are incomplete. The phantom echo shows the whole file. But  reading from stdin always ends at 4096 bytes.

**Comment by timdiggins** [comment]
@jpaas I've found the only solution is to give up on stdin, instead to open files from a url (I use a thor task to upload a file to an S3 bucket which auto-deletes its content). The other obvious alternative is to commit files to your repo temporarily and git push to heroku. (Yuck)

**Comment by jpaas** [comment]
Thanks @timdiggins, I ended up committing my files to the repo to get past it. It is yucky, but I only use this feature of my app for dealing with exceptional cases when they come up, so I can live with it.

**Comment by dickeyxxx** [comment]
Can you two submit support tickets? You can reference this issue. It isn't an issue with the CLI but the service that it connects to.

**Comment by jpaas** [comment]
Will do. Thanks @dickeyxxx for following up.

**Comment by timdiggins** [comment]
@dickeyxxx can you give me some reasons why you're stating "it isn't an issue with the CLI but the service that it connects to". 

I actually reported this problem to heroku support **in Oct 2015** at https://help.heroku.com/tickets/105256 and I referenced the stackoverflow question I had written http://stackoverflow.com/questions/20471959/piping-local-stdin-to-heroku-run-mustnt-write-to-stdout-4k-stdout-buffer.  

The response was:

> I believe that this is an issue with the Heroku toolbelt. Unfortunately, the team who maintains this tool does not receive requests via our ticketing system[https://github.com/heroku/heroku/issues/new]. Since this is a public tool, you should open a new Github Issue to report this. Feel free to reference this ticket number there.

I then wrote this issue up in Dec 2014 (sorry, I forgot to reference the ticket number -- I think I had forgotten about the ticket response). 

Can you help me out with this a bit further?

**Comment by dickeyxxx** [comment]
I'm not sure why you received that message but go ahead and submit a new one if you haven't already. This project is only maintained by the CLI team, it's not used by other teams. This particular issue doesn't involve this codebase so I don't have a good way to forward the issue to the appropriate team.

**Comment by timdiggins** [comment]
@dickeyxxx ok thanks, have done so.

but @dickeyxxx is this https://github.com/heroku/heroku-run/commit/eabaf6c9badfc3f73613a8e8d9b60d20489011ad why you are saying it's not a CLI issue? (have been poking through the codebase to try to understand why you said that)

**Comment by dickeyxxx** [comment]
It is related to that comment, but there isn't anything I can do to fix it. I do apologize but without having a good understanding of our internal architecture I'm not able to explain more of what the underlying issue is.

**Comment by timdiggins** [comment]
gotcha @dickeyxxx thanks for the clarification.
