### ISSUE TITLE
Git version check fails on Windows with git 1.9.5 installed

### ISSUE THREAD

**Issue by jcharlesworth** [heroku/heroku#1340]
On Windows 8.1 (may affect others?), I have current version of git installed:
```
C:\> git --version
git version 1.9.5.msysgit.0
```
When running any heroku command, I get the following result:
```
C:\> heroku
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - git --version (Errno::ENOENT)
    Backtrace:   C:/Program Files (x86)/Heroku/lib/heroku/git.rb:23:in ``'
                 C:/Program Files (x86)/Heroku/lib/heroku/git.rb:23:in `git_version'
                 C:/Program Files (x86)/Heroku/lib/heroku/git.rb:3:in `check_git_version'
                 C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:36:in `start'
                 C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

    Command:     heroku
    Version:     heroku/toolbelt/3.21.3 (i386-mingw32) ruby/1.9.3
```
The `git` command is in my path, as shown above.

**Comment by TrangPham** [comment]
@jcharlesworth 

The issue seems to be this line:
``` Ruby
/git version ([\d\.]+)/.match(`git --version`)[1]
```

Could you run `irb` in your command line and check the output of running that piece of code?

**Comment by dickeyxxx** [comment]
@jcharlesworth I added some better messaging around this, but I'm not sure it'll work for you since you said running `git --version` in the same shell worked. Anything weird going on with your `PATH` maybe that might cause the CLI to not be picking up Git?

**Comment by jcharlesworth** [comment]
Thanks for your help @TrangPham  and @dickeyxxx. @dickeyxxx  you were absolutely correct. There was a MySQL entry in my system path that was interfering. I narrowed it down by moving the Heroku CLI and GIT directories higher in priority using [PathMan](https://code.google.com/p/pathman/). Eventually I got the proper CLI output!
