### ISSUE TITLE
heroku auth:login  Error:       invalid byte sequence in UTF-8 (ArgumentError) (debian instable ruby 2.1)

### ISSUE THREAD

**Issue by gilgam** [heroku/heroku#1359]
i installed a new system (the last debian unstable) and as i did with fedora, installed heroku. 
heroku status command is ok but heroku auth:login fails. 

thanks

**Comment by dickeyxxx** [comment]
can you show me the full error?

**Comment by gilgam** [comment]
Ok here it is  

  Error:       invalid byte sequence in UTF-8 (ArgumentError)
    Backtrace:   /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:72:in `split'
                 /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:72:in `block in lex'
                 /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:71:in `each'
                 /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:71:in `lex'
                 /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:64:in `read'
                 /usr/local/heroku/lib/heroku/auth.rb:142:in `netrc'
                 /usr/local/heroku/lib/heroku/auth.rb:113:in `delete_credentials'
                 /usr/local/heroku/lib/heroku/auth.rb:40:in `login'
                 /usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
                 /usr/local/heroku/lib/heroku/command.rb:223:in `run'
                 /usr/local/heroku/lib/heroku/cli.rb:39:in `start'
                 /usr/local/heroku/bin/heroku:25:in `<main>'

    Command:     heroku auth:login
    Version:     heroku-toolbelt/3.22.1 (x86_64-linux-gnu) ruby/2.1.5

**Comment by gilgam** [comment]
oops i closed it ... can i change the status (noob in bugs on github).

**Comment by dickeyxxx** [comment]
you have some kind of issue with your  `~/.netrc` file

**Comment by gilgam** [comment]
indeed 
it was unreadable, with lot of strange characters. 
I deleted it and it works fine again.
I switched from fedora to debian, keeping the /home partition. It may be from a an old .netrc file.

Thanks a lot
