### ISSUE TITLE
Unable to heroku login because of .netrc permission issue

### ISSUE THREAD

**Issue by RamchandraApte** [heroku/heroku#1366]
I was running `heroku login` inside my project directory and I'm getting this directory. Doesn't seem to be [this bug](https://github.com/heroku/netrc/issues/20) because my $HOME is set correctly.

    ~/project$ heroku login

     !    Heroku client internal error.
     !    Search for help at: https://help.heroku.com
     !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Permission denied @ rb_sysopen - /home/ramchandra/.netrc (Errno::EACCES)
    Backtrace:   /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:62:in `read'
                 /usr/local/heroku/vendor/gems/netrc-0.10.2/lib/netrc.rb:62:in `read'
                 /usr/local/heroku/lib/heroku/auth.rb:142:in `netrc'
                 /usr/local/heroku/lib/heroku/auth.rb:113:in `delete_credentials'
                 /usr/local/heroku/lib/heroku/auth.rb:40:in `login'
                 /usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
                 /usr/local/heroku/lib/heroku/command.rb:223:in `run'
                 /usr/local/heroku/lib/heroku/cli.rb:39:in `start'
                 /usr/local/heroku/bin/heroku:25:in `<main>'

    Command:     heroku login
    Version:     heroku-toolbelt/3.23.1 (x86_64-linux-gnu) ruby/2.1.2

**Comment by RamchandraApte** [comment]
Never mind, somehow I had a .netrc (don't know how) file which my user doesn't have permissions to. Deleted the file and it works.

**Comment by vferko** [comment]
On windows, setting the file as hidden will cause this too.
