### ISSUE TITLE
Not deploy file successfully in heroku server

### ISSUE THREAD

**Issue by chaudhary-sushil** [heroku/heroku#1368]
I am trying to deploy my file on heroku server but every time i am face a lot's of problem and one of the basic problem is, in browser show a error message. how to solve this problem 
"Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

**Comment by dickeyxxx** [comment]
have you gone through a getting started guide? https://devcenter.heroku.com/start

**Comment by chaudhary-sushil** [comment]
Yes I'm follow complete guide of heroku and I'm also follow this link

"  http://www.sitepoint.com/deploying-yeomanangular-app-heroku/ "  to
deploy my nodejs app and I'm successfully deploy my app and that is show in
my heroku account but when I'm browse my app link that is show me
application error.
I'm really very confuse about deployment, because I'm try these steps many
time but not succeed.

my nodejs app file structure is

​
I'm using firebase to manage my data and one important thing is this - I am
beginner so I have no more knowledge about nodejs, angularjs and about how
to deploy my app on heroku so plz provide a better solution

I think mma_1/Gruntfile.js may cough a problem or package.json or
bower.json I'm really very confuse...

On Thu, Jan 22, 2015 at 1:35 AM, Jeff Dickey <notifications@github.com>
wrote:

> have you gone through a getting started guide?
> https://devcenter.heroku.com/start
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/heroku/issues/1368#issuecomment-70911344>.
>



-- 
*Chaudhary Sushil*

**Comment by dickeyxxx** [comment]
can you run `heroku logs` or something to get an error message?

**Comment by chaudhary-sushil** [comment]
yes and at finally i got problem and I'm successfully deploy my app...
