### ISSUE TITLE
incompatible character encoding (UTF-8 and windows 1252)

### ISSUE THREAD

**Issue by justberare** [heroku/heroku#1402]
![image](https://cloud.githubusercontent.com/assets/3747087/6030502/1dad95c4-abf8-11e4-8acb-aa9171682f93.png)

Environnement - Windows 8.1 x64 - French version
Heroku version: 3.25
git version: 1.9.5

Hi,

Just got this error message for every heroku command I try. With the great support of the One Month guys, we've been looking at both the variables of the cmd (UTF-8) and the encoding of the rb files mentionned in the error message (all UTF-8). But no solution found.

Thanks

**Comment by dickeyxxx** [comment]
can you add this to line 433 of `c:\Program Files (x86)/Heroku/lib/heroku/helpers.rb:433`:

```ruby
      formatted_error.each { |s| p s; p s.encoding }
```

just above the line

```ruby
formatted_error.join("\n")
```

**Comment by justberare** [comment]
thx for the reply. just did so and it gives me the following message 
![image](https://cloud.githubusercontent.com/assets/3747087/6031596/144a140e-ac01-11e4-8498-c14465fd7302.png)

**Comment by justberare** [comment]
Found the error.
I changed my ... last name (in .gitconfig). I dropped the accent and it worked.

**Comment by dickeyxxx** [comment]
We should still fix the error message here

**Comment by insane56** [comment]
I have same problem and cant fix it. Cant find file .gitconfig.

**Comment by SorokinV** [comment]
I have same problem. Most likely, the problem is associated with non-latin characters in user names, directories and profiles, which are files or where access is required. For example: c:\ПКЮЖ235.
How can I get around this?

**Comment by NeilJee** [comment]
I have the same problem. But actually I do not have any non-latin characters in my user names, directories and profiles.

![](http://7xj90c.com1.z0.glb.clouddn.com/QQ截图20150529000119.png)

Could any one know how to solve this problem ?

**Comment by SorokinV** [comment]
I must say that the screen is given tracing the secondary error. That is, (1) there must be some error when you run, then (2) there is a call procedure of forming the error text (helper.rb:449). In the formation of the text of this error occurs (3) in the formation of the text of the error (helper.rb:440), which is displayed in the trace on the screen.
Therefore, the problem can cause any error that can not display a error message on the screen.

In my case, I have determined that the initial error occurs when there is the command mkdir.
So I created a user only Latin characters with the new profile, and passed this point without any problems, just in case the administrative mode. It was important only for heroku. Django 1.8 and Python 3.4 normally work with non-Latin characters.

Search for error or bypass option in your case you need seek to cli:19, cli:39 or heroku:29 lines.

**Comment by LukaszWiktor** [comment]
Same problem here. I have a non-latin character in my home path. When I switched to another account with all latin characters then it worked.

**Comment by acdcjunior** [comment]
My windows user folder has a `ô` on its name. Having the same error here.

Other than creating a new windows user O_o, does anyone have a workaround?

**Comment by ransombriggs** [comment]
@acdcjunior Could you please run `heroku update` and try again?  I just shipped an update that should fix your issue.

**Comment by acdcjunior** [comment]
@ransombriggs The error is thrown at `heroku update` as well.
My current version is `heroku/toolbelt/3.37.2 (i386-mingw32) ruby/1.9.3`.
![screenshot](https://cloud.githubusercontent.com/assets/5091082/12898036/b4cc04ec-ce91-11e5-978d-9b64ebd6c2ea.png)

I guess all I can do is uninstall the current version and install the latest via control panel or similar, right?

**Comment by ransombriggs** [comment]
@acdcjunior Could you please install the current version from https://toolbelt.heroku.com/ ?

**Comment by acdcjunior** [comment]
@ransombriggs It worked. For me, at least.

I reinstalled heroku-toolbelt.exe (without unninstalling the current). Called `heroku update` right after that and had no problems (nothing to update, of course, tough).

Thanks for the help.
