### ISSUE TITLE
--wait-interval flag causes errors

### ISSUE THREAD

**Issue by JacobEvelyn** [heroku/heroku#1434]
`Error:       can't convert String into time interval (TypeError)`

It's trying to call `sleep` without converting the param to an integer.

**Comment by dickeyxxx** [comment]
I wonder if this is something that was changed in newer versions of ruby since it works for me on 2.2. In any case, #1436 should resolve this and it is released in 3.28.2

**Comment by dickeyxxx** [comment]
thanks for the help with this by the way!

**Comment by JacobEvelyn** [comment]
Thanks for getting this out!
