### ISSUE TITLE
!    internal error  on pg:backups if no backups exist

### ISSUE THREAD

**Issue by stillinbeta** [heroku/heroku#1448]
Multiple people in IRC have reported this internal error: on an app that hasn't used pg:backups, `heroku pg:backups` reports an `!   internal error`

capturing a backup alleviates this issue.

**Comment by uhoh-itsmaciek** [comment]
Thanks, I'll take a look at this. We have a branch for the "no backups" case, so something more subtle is going on, but I think I can track this down.

**Comment by uhoh-itsmaciek** [comment]
I believe this was resolved by a server-side fix that I pushed yesterday. I noticed that there are still some edge cases where calling `pg:backups` commands when you have no databases can cause errors, but I think that's more of an edge case; I'll handle those separately. Thanks for reporting.
