### ISSUE TITLE
Hung on forking an application

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku#1462]
Our build machine regularly forks applications, but as of today or yesterday it began to hang. 

Here is the command we are now executing (this is running on Ubuntu):
`heroku fork --copy-pg-data --app base-app target-app`

It appears to just sit there afterwards - no output. I believe this was introduced at the same time the --copy-pg-data flag was introduced. The first failure I saw was the first time I saw it instruct me to include `--copy-pg-data` to include a copy of the database. But even after adding that, it still hangs.

**Comment by dickeyxxx** [comment]
can you run `heroku version` or `heroku local` on that box?

**Comment by Taytay** [comment]
Sure thing. This is happening from both my Mac and Linux machines. Here is the full output:

Vagrant (Linux) box:
```
vagrant at webserver in ~ 
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise

vagrant at webserver in ~ 
$ heroku --version
heroku-toolbelt/3.30.2 (x86_64-linux) ruby/2.1.0
heroku-cli/4.12.2-ed2563f (amd64-linux) go1.4.2
=== Installed Plugins
heroku-fork@2.2.2

vagrant at webserver in ~ 
$ heroku local
Installing plugin heroku-local... done
Downloading forego-0.16.1 to /home/vagrant/.heroku... done
ERROR: open Procfile: no such file or directory
```

And from our Mac: 
```
$ heroku --version
heroku-toolbelt/3.30.2 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.12.2-ed2563f (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-fork@2.2.2
heroku-oauth
heroku-pg-extras
heroku-pipeline
```

On Mac:
```
$ heroku local
Installing plugin heroku-local... done
Downloading forego-0.16.1 to /Users/taylorbrown/.heroku... done
ERROR: open Procfile: no such file or directory

$ heroku version
heroku-toolbelt/3.30.2 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.12.2-ed2563f (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-fork@2.2.2
heroku-local@3.0.0
heroku-oauth
heroku-pg-extras
heroku-pipeline
```

Note: I was just able to fork one of our apps (that doesn't have a PG database). I am going to see if I can narrow down the plugins or circumstances that cause fork to hang.

**Comment by Taytay** [comment]
I've narrowed down the issue to these lines of the [Heroku fork](https://github.com/heroku/heroku-fork) plugin (I added those console logs)

```
getLastRelease: function* (app) {
    console.log('before asking for releases')
    let releases = yield this.heroku.request({
      path: `/apps/${app.name}/releases`,
      headers: { 'Range': 'version ..; order=desc;'}
    });
    console.log('before processing releases')
    let release = _.chain(releases)
    .filter('slug')
    .first()
    .value();
    if (!release) {
      throw new ForkError(`No slug for app ${app.name} was found.
Push some code to ${app.name} before forking it.`);
    }
    return release;
  }
```

I see the "before asking for releases" but nothing else, so I don't think it's returning from that method.
Still debugging to see if it's throwing a silent error internally, or if the request really is hanging.

P.S. Man, love the new ES6 plugin architecture. The generator syntax makes async code linear and much easier to read. The transition time makes for some bugs, but I bet it will be worth it.

**Comment by Taytay** [comment]
Okay - figured it out.
apps.getLastRelease:
```
  getLastRelease: function* (app) {
    let releases = yield this.heroku.request({
      path: `/apps/${app.name}/releases`,
      headers: { 'Range': 'version ..; order=desc;'}
    });
    let release = _.chain(releases)
    .filter('slug')
    .first()
    .value();
    if (!release) {
      throw new ForkError(`No slug for app ${app.name} was found.
Push some code to ${app.name} before forking it.`);
    }
    return release;
  },
```
Notice it sets the range header manually, which makes sense. You're trying to get the most recent releases.

However, there appears to be a bug in the request code:
```
Request.prototype.performRequest = function performRequest(cachedResponse) {
  var defaultRequestOptions,
      headers,
      key,
      requestOptions,
      req;

  this.cachedResponse = cachedResponse;

  headers = {
    'Accept': 'application/vnd.heroku+json; version=3',
    'Content-type': 'application/json',
    'Range': this.nextRange // Here it's setting the range to this.nextRange
  };

  console.log('headers before: ', headers)
  this.options.headers = this.options.headers || {};

  // And down here we override the range header if it was set in the options
  for (key in this.options.headers) {
    if (this.options.headers.hasOwnProperty(key)) {
      headers[key] = this.options.headers[key];
    }
  }
```

The first time through the request method, the above code works great. The range header you set correctly sets the range header to the one you set in the options (`'Range': 'version ..; order=desc;'`)
However, when the response comes back, the request objects sees that there is a `next-range` header specified as (in our app's case) `version ]348..; order=desc`, so it does this in `handleSuccess`:
```
  if (res.headers['next-range']) {
    this.nextRequest(res.headers['next-range'], body);
  } 
```
Which in turn does this:
```
Request.prototype.nextRequest = function nextRequest(nextRange, body) {
  this.updateAggregate(body);
  this.nextRange = nextRange;
  this.request();
};
```
So it's setting the `nextRange` property, which, in normal circumstances does modify the range request header, but in this case, since the `options.headers.Range` property is already set, the nextRange gets immediately overridden by the Range initially set in the headers.

There are numerous workarounds/solutions I can think of, but the most straightforward is to remove the `range` header from options.headers in the nextRequest method:
```
Request.prototype.nextRequest = function nextRequest(nextRange, body) {
  this.updateAggregate(body);
  this.nextRange = nextRange;
  delete (this.options.headers['Range']);
  this.request();
};
```

As soon as I did this, it started working like a champ.

One thing to note though is that we are modifying the options directly, and if the consumer wants to reuse those options for a subsequent request, they wouldn't be able to. To get around that, you could clone the options object first at construction time.

**Comment by Taytay** [comment]
I've opened a pull request with the change proposed above: heroku/node-heroku-client#34

**Comment by dickeyxxx** [comment]
Nice find! Can you change it to .Range to make the linter happy? (Check the CI failure)

**Comment by dickeyxxx** [comment]
Thanks for the detailed writeup as well! The range portion of the node client does need some work. It's gotten in our way a couple of times, but this looks like a good fix for this bug.

**Comment by Taytay** [comment]
Cool - updated as requested. :) Fingers crossed this one makes the linter happy.
