### ISSUE TITLE
ERROR: fork/exec iojs-v1.5.1-linux-x86/bin/node: no such file or directory

### ISSUE THREAD

**Issue by janraasch** [heroku/heroku#1465]
Hi guys,

as I was trying to try the new plugin architecture by running `heroku plugins:install heroku-papertrail`, but got

```bash
Installing Heroku Toolbelt v4... done
Installing plugin heroku-papertrail... ERROR: fork/exec iojs-v1.5.1-linux-x86/bin/node: no such file or directory
```

When then running any `heroku ...` command I would get

```bash
ERROR: symlink ../lib/node_modules/npm/bin/npm-cli.js /home/vagrant/.heroku/iojs-v1.5.1-linux-ia32/bin/npm: file exists
error loading plugin commands
```

I have `node` setup via `nvm` on my ubuntu box. Maybe that was causing trouble, since running this on a Mac w/o an installation of node seems to work.

**Comment by abbottc** [comment]
Same problem here, running Linux Mint 17.1.  If I delete/rename the "node" and "npm" symlinks in `~/.heroku/iojs-v1.5.1-linux-ia32/bin`, and then run a heroku command, I don't see errors appear and I see that the "node" and "npm" symlinks get recreated.  But after that, executing more heroku commands causes the same symlink errors to appear again.

**Comment by dickeyxxx** [comment]
somewhere that `ia32` directory is being referenced. Trying to find where.

**Comment by dickeyxxx** [comment]
I need to test it, but this PR should fix it dickeyxxx/gode#1

**Comment by abbottc** [comment]
Was that PR a part of the 3.30.3 update that was released today?  If so, the errors still occur after the update.

**Comment by dickeyxxx** [comment]
@abbottc @janraasch sorry about this, I was on vacation until today. Mind giving it another try? It's fixed in the latest version of https://github.com/heroku/heroku-cli

**Comment by abbottc** [comment]
No error messages now.  Thanks!  And sorry to hear about the untimely end to your time on vacation.  The days will be sorely missed.

**Comment by dickeyxxx** [comment]
ha! well glad to hear it is fixed :)
