### ISSUE TITLE
Incorrect documentation on exporting postgres DB

### ISSUE THREAD

**Issue by chibicode** [heroku/heroku#1473]
On this page:
https://devcenter.heroku.com/articles/heroku-postgres-import-export#export

On "Download backup" section, it currently says to type:

```
$ heroku pg:backups capture
$ curl -o latest.dump `heroku pg:backups public-url b001 -a sushi`
```

However, `heroku pg:backups public-url b001 -a sushi` displays something like this:

```
The following URL will expire at 2015-03-26 02:00:21 +0000:
   'https://...'
```

So I don't think you can put that directly into `curl -o`.

I had to try something like this:

```
$ curl -o latest.dump `heroku pg:backups public-url $1 | tr -d '\r\n' | sed -e "s/.*'\(.*\).*'/\1/")`
```

**Comment by chibicode** [comment]
It'd be simpler if `public-url` had an option which just returns URL and nothing else.

**Comment by dickeyxxx** [comment]
closing as dupe of #1466

**Comment by chibicode** [comment]
@dickeyxxx I don't think it's a dupe (I saw #1466 before creating this issue). Documentation URLs are different, too.

- This issue says: `public-url` is outputting extra information, so it can't be fed into `curl` as [this "Importing and Exporting Heroku Postgres Databases with PG Backups" documentation](https://devcenter.heroku.com/articles/heroku-postgres-import-export#export) says.
- #1466 says: `public-url` should work without a backup ID, as [this "Converting PGBackups Add-on Commands" documentation](https://devcenter.heroku.com/articles/mapping-pgbackups-commands#downloading-your-backup) says.

**Comment by uhoh-itsmaciek** [comment]
@chibicode you're right--it's not exactly a dupe, but #1463 fixed both issues. Sorry for the inconvenience.

**Comment by chibicode** [comment]
@uhoh-itsmaciek oh ok, thank you!

**Comment by dickeyxxx** [comment]
its released btw

**Comment by chibicode** [comment]
@dickeyxxx great! Thank you for letting me know :)
