### ISSUE TITLE
Fixed runtime decency `rubyzip = 0.9.9` leds to incompatibility

### ISSUE THREAD

**Issue by zillou** [heroku/heroku#1474]
I want to add [pgbackups-archive (1.0.0)](https://rubygems.org/gems/pgbackups-archive/versions/1.0.0) to my project. bundler can't finished due to Heroku requires a fixed `rubyzip = 0.9.9`

```
Bundler could not find compatible versions for gem "rubyzip":
  In Gemfile:
    pgbackups-archive (= 1.0.0) ruby depends on
      heroku (>= 3.28.6, ~> 3.28) ruby depends on
        rubyzip (= 0.9.9) ruby

    selenium-webdriver (= 2.45.0) ruby depends on
      rubyzip (1.0.0)
```

**Comment by kjohnston** [comment]
@zillou, thanks for opening this issue.  I ran into this the other day, but figured we'd be hung in this position for a while since upgrading rubyzip will break 1.8.7 support, but @dickeyxxx is looking into that right now.

https://github.com/heroku/heroku/pull/1470
https://github.com/heroku/heroku/pull/1479

**Comment by wuputah** [comment]
FYI, `pgbackups` is now deprecated, in favor of `pg:backups`. See:
https://devcenter.heroku.com/articles/pgbackups
https://devcenter.heroku.com/articles/heroku-postgres-backups

It'd be nice to see `pgbackups-archive` move to the new system, and ideally not depend on the CLI gem (use the API directly).

**Comment by kjohnston** [comment]
@wuputah, [pgbackups-archive](https://github.com/kjohnston/pgbackups-archive) was changed over to the new service as of v1.0.0.

Regarding shelling out to the CLI, it's possible if we need to go there, but it's not the favorable approach, not that there is a favorable one - the API isn't directly accessible or documented and the Platform API gem won't support it anytime soon, although that would seem like the place we'd piggyback on after the old `heroku` gem is gone.

**Comment by kjohnston** [comment]
@wuputah, see https://github.com/heroku/heroku/pull/1470 for more discussion on the above.
