### ISSUE TITLE
sudo labs:enable fails for user features when done in an app directory

### ISSUE THREAD

**Issue by dmcinnes** [heroku/heroku#1475]
If a sudo user runs `labs:enable` for a user:
```
heroku sudo labs:enable limited-features -u thatguy@example.com
```
But they happen to be running it from one of their apps, they get a cryptic error message:
```
Enabling limited-features for ... failed
!    You do not have access to the app foo.
```

This is actually caused by an API bug, but it's on a v2 endpoint which we're in the process of deprecating. I figure I'd make a note of it here.
https://github.com/heroku/api/issues/3619

**Comment by mikehale** [comment]
:+1: for switching to the v3 endpoint

**Comment by dickeyxxx** [comment]
that's already been done
