### ISSUE TITLE
Better message handling for non git-initialized directories

### ISSUE THREAD

**Issue by pravj** [heroku/heroku#1478]
Hi there,

Today, I created an application via the web-interface and tried adding the remote for that in the directory I was working in.

I don't do this generally but I forgot to do `git-init` in that directory and when I attempted the command `heroku git:remote -a <application>`, the result was nothing.

It assumes that the directory has git initialized already. And doesn't takes care of the error `fatal: Not a git repository (or any of the parent directories): .git` returned by git.

https://github.com/heroku/heroku/blob/master/lib/heroku/command/git.rb#L47-L59
```ruby
  #
  # $ heroku git:remote -a example
  # Git remote heroku added
  #
  def remote
    validate_arguments!
    app_info = api.get_app(app).body
    if git('remote').split("\n").include?(remote_name)
      update_git_remote(remote_name, git_url(app_info['name']))
    else
      create_git_remote(remote_name, git_url(app_info['name']))
    end
  end
```

**Comment by dickeyxxx** [comment]
this is fixed as part of https://github.com/heroku/heroku/pull/1533
