### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by EnriqueV** [heroku/heroku#1487]
hello everybody please help me with this problem:
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
    Command:     heroku open
    Version:     heroku-toolbelt/3.30.6 (i486-linux) ruby/1.9.3
    Error ID:    1dbf422d620848d5ad093bd07b8feeea

    More information in /root/.heroku/error.log

**Comment by dickeyxxx** [comment]
are you trying to run this in a vm or something? this means it can't find a browser
