### ISSUE TITLE
Can't login with heroku toolbelt on Windows

### ISSUE THREAD

**Issue by dipacs** [heroku/heroku#1489]
I can't use heroku toolbelt on windows cause of an error:
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:434:in `join': incompatible character encodings: UTF-8 and Windows-1
250 (Encoding::CompatibilityError)
        from C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:434:in `format_error'
        from C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:443:in `styled_error'
        from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:57:in `rescue in start'
        from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:40:in `start'
        from C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

I think the problem is that my home folder contains an 'á' character.
I added a line to helpers.rb and i get the following output:

Authentication successful.
" !    Heroku client internal error."
#<Encoding:US-ASCII>
" !    Search for help at: https://help.heroku.com"
#<Encoding:US-ASCII>
" !    Or report a bug at: https://github.com/heroku/heroku/issues/new"
#<Encoding:US-ASCII>
""
#<Encoding:US-ASCII>
"    Error:       Permission denied - C:/Users/D\u00A0vid (Errno::EACCES)"
#<Encoding:UTF-8>
"    Command:     heroku login"
#<Encoding:US-ASCII>
"    Version:     heroku/toolbelt/3.30.6 (i386-mingw32) ruby/1.9.3"
#<Encoding:US-ASCII>
"    Error ID:    f19de2f411874f4ab7648b9909364d10"
#<Encoding:US-ASCII>
"\n"
#<Encoding:US-ASCII>
"    More information in C:/Users/D\xA0vid/.heroku/error.log"
#<Encoding:Windows-1250>
"\n"
#<Encoding:US-ASCII>
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:434:in `join': incompatible character encodings: UTF-8 and Windows-1
250 (Encoding::CompatibilityError)
        from C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:434:in `format_error'
        from C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:443:in `styled_error'
        from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:57:in `rescue in start'
        from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:40:in `start'
        from C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by dickeyxxx** [comment]
it's a different issue, it's related to this bug in Ruby https://bugs.ruby-lang.org/issues/10126

I've got a fix coming though

**Comment by dickeyxxx** [comment]
#1501

**Comment by marhw** [comment]
I got same problem after fix from #1501 Here's my log

 Heroku client internal error.
"\x88" to UTF-8 in conversion from Windows-1250 to UTF-8
c:/Heroku/vendor/gems/netrc-0.10.3/lib/netrc.rb:24:in `readable?'
c:/Heroku/vendor/gems/netrc-0.10.3/lib/netrc.rb:24:in `home_path'
c:/Heroku/vendor/gems/netrc-0.10.3/lib/netrc.rb:11:in `default_path'
c:/Heroku/lib/heroku/auth.rb:131:in `netrc_path'
c:/Heroku/lib/heroku/auth.rb:150:in `rescue in netrc'
c:/Heroku/lib/heroku/auth.rb:141:in `netrc'
c:/Heroku/lib/heroku/auth.rb:113:in `delete_credentials'
c:/Heroku/lib/heroku/auth.rb:40:in `login'
c:/Heroku/lib/heroku/command/auth.rb:31:in `login'
c:/Heroku/lib/heroku/command.rb:223:in `run'
c:/Heroku/lib/heroku/cli.rb:45:in `start'
c:/Heroku/bin/heroku:29:in `<main>'

**Comment by viellepeau** [comment]
I have the same issue because my name is Joël : $ heroku login
c:/Users/Jo%l/.heroku/client/lib/heroku/helpers.rb:433:in `join': incompatible character encodings: IBM775 and Windows-1252 (Encoding::CompatibilityError)
        from c:/Users/Jo%l/.heroku/client/lib/heroku/helpers.rb:433:in `format_error'
        from c:/Users/Jo%l/.heroku/client/lib/heroku/helpers.rb:442:in `styled_error'
        from c:/Users/Jo%l/.heroku/client/lib/heroku/cli.rb:52:in `rescue in start'
        from c:/Users/Jo%l/.heroku/client/lib/heroku/cli.rb:35:in `start'
        from c:/Heroku/bin/heroku:29:in `<main>'

I tried what suggested marhw but it did not work
I was able to use the heroku toolbelt before it did an automatic update..
What should I do ?
I searched a lot on Google but no solution for me so far

Thx

**Comment by viellepeau** [comment]
As a workaround, I have created a new Windows user account on my machine.
Joël ==> Joel to avoid special char
Now I can use the heroku toolbelt.
However I would appreciate not to change my name to work :)

**Comment by seanjb** [comment]
Appears to be caused by this line in jsplugin.rb

File.join(ENV['LOCALAPPDATA'], 'heroku')

Replacing ENV['LOCALAPPDATA'] with a hard coded (non special character) path appears to work for now

**Comment by dickeyxxx** [comment]
@seanjb what error are you seeing exactly?

**Comment by seanjb** [comment]
This is the error I get. My User folder is Seán however that doesn't seem to come through correctly encoded on ENV['LOCALAPPDATA']. Have used the command heroku plugins as an example here, but similar for other commands.

C:\Users\Seán>heroku plugins
Installing Heroku Toolbelt v4... done.
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
No such file or directory - "C:\Users\Se??n\AppData\Local/heroku/heroku-cli.exe"
 version
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:102:in ``'
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:102:in `version'
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:135:in `setup'
c:/Heroku/AppData/.heroku/client/lib/heroku/cli.rb:24:in `start'
C:/Heroku/bin/heroku:29:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - "C:\Users\Se??n\AppData\Local/herok
u/heroku-cli.exe" version (Errno::ENOENT)
    Command:     heroku plugins
    Version:     heroku/toolbelt/3.42.17 (i386-mingw32) ruby/1.9.3


    More information in C:/Heroku/AppData/.heroku/error.log

"\xC3" from ASCII-8BIT to UTF-8
c:/Heroku/AppData/.heroku/client/lib/heroku/helpers.rb:462:in `write'
c:/Heroku/AppData/.heroku/client/lib/heroku/helpers.rb:462:in `block in error_lo
g'
c:/Heroku/AppData/.heroku/client/lib/heroku/helpers.rb:461:in `open'
c:/Heroku/AppData/.heroku/client/lib/heroku/helpers.rb:461:in `error_log'
c:/Heroku/AppData/.heroku/client/lib/heroku/helpers.rb:454:in `styled_error'
c:/Heroku/AppData/.heroku/client/lib/heroku/cli.rb:42:in `rescue in start'
c:/Heroku/AppData/.heroku/client/lib/heroku/cli.rb:20:in `start'
C:/Heroku/bin/heroku:29:in `<main>'
No such file or directory - "C:\Users\Se??n\AppData\Local/heroku/heroku-cli.exe"
 version
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:102:in ``'
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:102:in `version'
c:/Heroku/AppData/.heroku/client/lib/heroku/jsplugin.rb:135:in `setup'
c:/Heroku/AppData/.heroku/client/lib/heroku/cli.rb:24:in `start'
C:/Heroku/bin/heroku:29:in `<main>'

C:\Users\Seán>

**Comment by dickeyxxx** [comment]
This will fix the issue: https://github.com/heroku/heroku/pull/1774

**Comment by tedf20** [comment]
Line 107 in jsplugin.rb is 'File.join(ENV['LOCALAPPDATA'], 'heroku').encode('windows-1252')', but the issue still appears. The error upon 'heroku login' with a cyrillic user name

Heroku client internal error.
U+0412 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
Heroku client internal error.
U+0412 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
Heroku client internal error.
U+0412 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by burrellg** [comment]
I am getting the same error, but my name has a space rather than a Cyrillic character.  Error log at the following link:

<a href="https://github.com/burrellg/pinteresting2/blob/master/heroku%20error.log" class="issue-link" title="Heroku error log">heroku error log</a>

Tried the solutions recommended for the other problems but to no avail.

**Comment by ransombriggs** [comment]
@burrellg - Could you please run `heroku update` and try again?  I sent out a release on Friday that should have fixed this problem.

**Comment by seanjb** [comment]
Just re-installed Heroku and had success running
> heroku
> heroku update

However 
>heroku login
gave the following:

`C:\Users\Seán>heroku login
No such file or directory - C:\Users\Seán\AppData\Local/heroku/heroku-cli.exe
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:165:in `exec'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:165:in `run'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:15:in `try_takeover'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:25:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
incompatible character encodings: UTF-8 and CP850
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:467:in `join'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:467:in `format_error'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:476:in `styled_error'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:42:in `rescue in start'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:20:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
No such file or directory - C:\Users\Seán\AppData\Local/heroku/heroku-cli.exe
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:165:in `exec'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:165:in `run'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:15:in `try_takeover'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:25:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
`

**Comment by ransombriggs** [comment]
@seanjb this is a known issue that I am currently working on

**Comment by ransombriggs** [comment]
@dipacs @marhw @viellepeau @seanjb If you are still having issues, could you please reinstall the toolbelt from https://toolbelt.heroku.com/ and try again, it should work now.

**Comment by seanjb** [comment]
@ransombriggs it's working perfectly for me now. Thanks a million!
