### ISSUE TITLE
Fork app to europe failed on Adding pgbackups

### ISSUE THREAD

**Issue by mikes01** [heroku/heroku#1499]
Could you help me with this issue? Log explains everything...

>mikolaj@mikolaj-VirtualBox:/var/www/houseOps$ heroku fork -a house-ops house-ops-eu --region eu
Creating fork house-ops-eu... done
Copying slug... done
Adding heroku-postgresql:hobby-dev... done
Adding pgbackups:plus to house-ops... Failed to fork app house-ops to house-ops-eu.

 >!    WARNING: Potentially Destructive Action
 !    This command will destroy house-ops-eu (including all add-ons).
 !    To proceed, type "house-ops-eu" or re-run this command with --confirm house-ops-eu

> house-ops-eu
Deleting house-ops-eu... done
Original exception below:
 !    Resource not found

**Comment by dickeyxxx** [comment]
what is the output of `heroku version`?

**Comment by mikes01** [comment]
>mikolaj@mikolaj-VirtualBox:/var/www/houseOps$ heroku version
heroku-toolbelt/3.28.5 (x86_64-linux) ruby/1.9.3
You have no installed plugins.
WARNING: Toolbelt v3.31.3 update available.

**Comment by dickeyxxx** [comment]
you're on an old version, if you update you should be good

**Comment by mikes01** [comment]
You are right, it works. Thanks a lot!
