### ISSUE TITLE
Keeping .git folder when deploying on Heroku?

### ISSUE THREAD

**Issue by Unitech** [heroku/heroku#1509]
Hi,

Is it possible to keep the .git folder when deploying to Heroku? We need to do some processing based on the data in this folder.

Thanks

**Comment by dickeyxxx** [comment]
you probably don't want to, that would greatly increase the slug size. What is it you're trying to do?

**Comment by Unitech** [comment]
I understand, but is there any way to include ignored file/folder like .git log or tmp?

**Comment by dickeyxxx** [comment]
I don't think so, file a support ticket, this project is for the CLI
