### ISSUE TITLE
pg:backups is prefixing manual backups with "a"

### ISSUE THREAD

**Issue by chadbailey59** [heroku/heroku#1510]
The code that decides the prefix is [located here](https://github.com/heroku/heroku/blob/ccdd80e109c8e1e2586f5444950b0b059dbf5c47/lib/heroku/command/pg_backups.rb#L104). It looks for the `schedule` key in the transfer hash. For unscheduled backups, the `schedule` key exists, and has a value of `{"uuid" => nil}`:

```
{:uuid=>"f789ab71-41a3-4ed7-bfe0-5e66b66ceef8", :num=>110, :from_name=>"BACKUP", :from_type=>"gof3r", :from_url=>"https://xfrtu.s3.amazonaws.com/4064d0f2-6cfc-47e0-be3d-6d3b47f2dc88/2015-01-23T07:07:16Z/1ce28e91-34ad-4a1c-83a7-0bd2043e02ee", :to_name=>"DATABASE", :to_type=>"pg_restore", :to_url=>"postgres://u5bkl7qanc48gh:pbp1d8g0jk7mb74qg1lua2b3846@ec2-23-23-237-11.compute-1.amazonaws.com:5472/d50elnql8bn1g9", :options=>{}, :source_bytes=>nil, :processed_bytes=>0, :succeeded=>false, :created_at=>"2015-02-05 22:21:18 +0000", :started_at=>"2015-02-06 07:05:04 +0000", :canceled_at=>nil, :updated_at=>"2015-02-06 07:05:09 +0000", :finished_at=>"2015-02-06 07:05:05 +0000", :deleted_at=>nil, :purged_at=>nil, :schedule=>{"uuid"=>nil}, :num_keep=>5}
```

Looks like we either need to code around that fact in the CLI or tweak the transfer hash not to include the `schedule` key at all.

**Comment by uhoh-itsmaciek** [comment]
Good catch. Let's go with the former.

**Comment by uhoh-itsmaciek** [comment]
Err, latter. Let's go with the latter.

**Comment by uhoh-itsmaciek** [comment]
Closing since this is now essentially just a transferatu issue.
