### ISSUE TITLE
Deploying app using one click heroku fails - not a valid Heroku application error.

### ISSUE THREAD

**Issue by iCHAIT** [heroku/heroku#1512]
I'm trying to deploy one of my Django application using One Click Heroku.

[Here](https://github.com/iCHAIT/Timer) is the link to the repostiroy that I want to deploy.
I have added a app.json files that mantains the description of my application.

Now when I'm trying to deploy my app it gives the following error -

![screen shot 2015-04-24 at 2 15 36 am](https://cloud.githubusercontent.com/assets/8472314/7307102/e07fc118-ea27-11e4-9244-cea3fc5aa35c.png)

Is there anything that I'm missing?

**Comment by dickeyxxx** [comment]
can you submit a support ticket? this project is only for the CLI
