### ISSUE TITLE
 Heroku client internal error.

### ISSUE THREAD

**Issue by ashish-pandey-tavant** [heroku/heroku#1516]
!    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory -  git remote -v 2>&1  (Errno::ENOENT
)
    Command:     heroku ps
    Version:     heroku/toolbelt/3.32.0 (i386-mingw32) ruby/1.9.3
    Error ID:    ad4938a784db4739aa736fc98d4acf44

    More information in C:/Users/ashish.pandey/.heroku/error.log

**Comment by dickeyxxx** [comment]
you need to install git
