### ISSUE TITLE
heroku addons:configure_addon command crashes

### ISSUE THREAD

**Issue by diwu1989** [heroku/heroku#1524]
What is this command? and it doesn't work
![image](https://cloud.githubusercontent.com/assets/380950/7437139/e61940f8-f009-11e4-89fd-5d007254e4f0.png)

**Comment by dickeyxxx** [comment]
it's probably in one of your plugins

**Comment by ghickman** [comment]
I'm having a similar issue which appears to be related to the pg-extras plugin:

![](http://cl.ly/image/3r0K3C2t331n/Image%202015-05-05%20at%203.30.57%20pm.png)

I get this before the output of any heroku command I run.

**Comment by ghickman** [comment]
Running `heroku plugins:update` has fixed this for me.

@diwu1989 – does that command help you too?
