### ISSUE TITLE
 heroku git:clone error

### ISSUE THREAD

**Issue by renanlecaro** [heroku/heroku#1525]
The clone seems to have been completed but well, here is the initial request :

C:\Users\Renan> heroku git:clone -a cyberlegume
Cloning from app 'cyberlegume'...
Cloning into 'cyberlegume'...
remote: Counting objects: 2570, done.
remote: Compressing objects: 100% (1391/1391), done.
remote: Total 2570 (delta 1261), reused 1860 (delta 765)
Receiving objects: 100% (2570/2570), 12.97 MiB | 578.00 KiB/s, done.
Resolving deltas: 100% (1261/1261), done.
Checking connectivity... done.
updating... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Une connexion existante a d¹ Ûtre fermÚe par lÆh¶te distant. (Errn
o::ECONNRESET) (Excon::Errors::SocketError)
    Command:     heroku git:clone -a cyberlegume
    Version:     heroku/toolbelt/3.32.0 (i386-mingw32) ruby/1.9.3
    Error ID:    dad39795f29b4440b96e520c19c7d32e
    More information in C:/Users/Renan/.heroku/error.log
C:\Users\Renan>cat C:/Users/Renan/.heroku/error.log

And here is the error log

Heroku client internal error.
Une connexion existante a dû être fermée par l92hôte distant. (Errno::ECONNRESET)
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/socket.rb:211:in `read'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/socket.rb:211:in `read_block'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/socket.rb:37:in `read'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/response.rb:133:in `parse'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/middlewares/response_parser.rb:6:in `response_call'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/connection.rb:372:in `response'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon/connection.rb:236:in `request'
C:/Users/Renan/.heroku/client/vendor/gems/excon-0.45.1/lib/excon.rb:229:in `get'
C:/Users/Renan/.heroku/client/lib/heroku/excon.rb:4:in `get_with_redirect'
C:/Users/Renan/.heroku/client/lib/heroku/excon.rb:6:in `get_with_redirect'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:36:in `http_get'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:146:in `block in download_file'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:145:in `open'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:145:in `download_file'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:120:in `block (2 levels) in update'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:112:in `block in update'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:84:in `wait_for_lock'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:108:in `update'
C:/Users/Renan/.heroku/client/lib/heroku/updater.rb:97:in `autoupdate'
C:/Users/Renan/.heroku/client/lib/heroku/cli.rb:46:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by dickeyxxx** [comment]
This just means the network connection failed. It's not a bug.
