### ISSUE TITLE
pg:promote no longer works if you specify a DATABASE_URL: "Can not find add-on with "HEROKU_POSTGRESQL_TEAL_URL""

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku#1527]
This bug or change started happening in the last 24 hours. Previously, this worked for us multiple times a day:

List our DBs:
```
$ heroku pg --app y-fix-small-ansible-related-bu
=== HEROKU_POSTGRESQL_IVORY_URL (DATABASE_URL)
Plan:               Standard 0
Status:             Available
Data Size:          37.8 MB
Tables:             35
PG Version:         9.4.1
Connections:        5/120
Fork/Follow:        Available
Rollback:           earliest from 2015-05-05 17:05 UTC
Created:            2015-05-05 17:03 UTC
Maintenance:        not required
Maintenance window: Thursdays 19:00 to 23:00 UTC

=== HEROKU_POSTGRESQL_TEAL_URL
Plan:        Hobby-basic
Status:      Available
Connections: 1/20
PG Version:  9.4.1
Created:     2015-05-05 17:08 UTC
Data Size:   37.0 MB
Tables:      35
Rows:        81705/10000000 (In compliance)
Fork/Follow: Unsupported
Rollback:    Unsupported
```
Promote the Teal DB:
```
$ heroku pg:promote HEROKU_POSTGRESQL_TEAL_URL --app y-fix-small-ansible-related-bu
 !    Can not find add-on with "HEROKU_POSTGRESQL_TEAL_URL"
```

Previously, the ability to specify the DATABASE_URL as the DB that you wanted to promote was very handy. Is there a new way to call this?

**Comment by Taytay** [comment]
Oh! After reading through the latest Pull request that introduced this change, it looks like I should be calling this as:
`heroku pg:promote TEAL` instead of `HEROKU_POSTGRESQL_TEAL_URL`. Will make the change.

On a related note, Is there a place to be notified of such breaking changes?

**Comment by dickeyxxx** [comment]
the changelog is where we post such things: https://devcenter.heroku.com/changelog but unfortunately this wasn't included.

**Comment by rdbartlett** [comment]
Hey @dickeyxxx just letting you know [the Heroku docs](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases) are out of date: made our db migration on [Loomio](https://loomio.org) production a bit scary til we found this bug report.

**Comment by dickeyxxx** [comment]
cc @jonmountjoy

**Comment by dickeyxxx** [comment]
there is a fix in for this https://github.com/heroku/heroku/pull/1557

**Comment by rdbartlett** [comment]
Nice one @dickeyxxx
