### ISSUE TITLE
addons:create is somewhat broken

### ISSUE THREAD

**Issue by davetron5000** [heroku/heroku#1530]
```
> heroku help addons
Additional commands, type "heroku help COMMAND" for more details:

  addons:_create                                  # 
  addons:attach ADDON_NAME                        #  attach add-on resource to an app
  addons:create                                   # 
  addons:destroy ADDON_NAME [ADDON_NAME ...]      #  destroy add-on resources
  addons:detach ATTACHMENT_NAME                   #  detach add-on resource from an app
  addons:docs ADDON_NAME                          #  open an add-on's documentation in your browser
  addons:downgrade ADDON_NAME ADDON_SERVICE:PLAN  #  downgrade an existing add-on resource to PLAN
  addons:open ADDON_NAME                          #  open an add-on's dashboard in your browser
  addons:plans SERVICE                            #  list all available plans for an add-on service
  addons:services                                 #  list all available add-on services
  addons:upgrade ADDON_NAME ADDON_SERVICE:PLAN    #  upgrade an existing add-on resource to PLAN
```

Notice that there is a weird `_create` command, and that both it and `create` (no underscore) show no help.

Further, the addon command *does* work, but it ignores all command-line options.

I've verified that `create` in `lib/heroku/command/addon.rb` *is* being called, and the command-line arguments are being passed properly.

Further, if I just copy that method and give it a different name, *that* command is fully documented and works.  SO there's something special about `create`.

**Comment by dickeyxxx** [comment]
can you show me the output of `heroku version`?

**Comment by davetron5000** [comment]
Oops,forgot to include that:

```
> heroku version
heroku-toolbelt/3.35.1 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-accounts
heroku-oauth
heroku-pg-extras
heroku-repo
```

`heroku update` doesn't do anything.

**Comment by dickeyxxx** [comment]
ah it's an issue with heroku-pg-extras. @will it looks like it's an issue since it's now aliasing create instead of just an underlying method

**Comment by kivanio** [comment]
<pre>
heroku version                                                                                                [9:17:18]
 !    Unable to load plugin heroku-pg-extras.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)
    Command:     heroku version
    Plugins:     heroku-pg-extras
    Version:     heroku-toolbelt/3.35.1 (x86_64-darwin14) ruby/2.2.2
    Error ID:    f6bf7add46de4228bed9ce0ff31a1836

heroku-toolbelt/3.35.1 (x86_64-darwin14) ruby/2.2.2
=== Installed Plugins
heroku-pg-extras
</pre>

**Comment by will** [comment]
@dickeyxxx Yeah, the method that I was using was taken away, and now the only option is at the entry of that command. Maybe we can add a proper hook something like `expand_addon_shorthand if defined?(expand_addon_shorthand)`?

**Comment by dickeyxxx** [comment]
I think the shorthand is pretty useful regardless, I'm inclined just to add it into the mainline

**Comment by dickeyxxx** [comment]
this is fixed, just update your plugins

**Comment by davetron5000** [comment]
Awesome, thank you!!

**Comment by eprothro** [comment]
For others:

In example above, run `heroku plugins:update heroku-pg-extras` to update the offending plugin.

**Comment by ark1980** [comment]
They replaced `add` instead of `create`

**Comment by dickeyxxx** [comment]
you've got that backwards
