### ISSUE TITLE
undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)

### ISSUE THREAD

**Issue by trg** [heroku/heroku#1532]
Running:
    `$ heroku pgbackups:url -a my_app_name`

Yields the following error:

    
    !    Unable to load plugin heroku-pg-extras.
    !    Search for help at: https://help.heroku.com
    !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `configure_addon' for class `Heroku::Command::Addons' (NameError)
    Command:     heroku pgbackups:url -a my_app_name
    Plugins:     heroku-oauth
                 heroku-pg-extras

    Version:     heroku-toolbelt/3.35.1 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    e5cd0d2c9ce44e20bb760191a4c6c302

    More information in /Users/my_username/.heroku/error.log

In ~/.heroku/error.log:

    Unable to load plugin heroku-pg-extras.
    undefined method `configure_addon' for class `Heroku::Command::Addons'
    /Users/my_username/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:734:in `alias_method'
    /Users/my_username/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:734:in `<class:Addons>'
    /Users/my_username/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:733:in `<module:Command>'
    /Users/my_username/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:732:in `<top (required)>'
    /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    /Users/my_username/.heroku/plugins/heroku-pg-extras/init.rb:6:in `<top (required)>'
    /Users/my_username/.heroku/client/lib/heroku/plugin.rb:62:in `load'
    /Users/my_username/.heroku/client/lib/heroku/plugin.rb:62:in `load_plugin'
    /Users/my_username/.heroku/client/lib/heroku/plugin.rb:54:in `block in load!'
    /Users/my_username/.heroku/client/lib/heroku/plugin.rb:51:in `each'
    /Users/my_username/.heroku/client/lib/heroku/plugin.rb:51:in `load!'
    /Users/my_username/.heroku/client/lib/heroku/command.rb:22:in `load'
    /Users/my_username/.heroku/client/lib/heroku/cli.rb:44:in `start'
    /usr/bin/heroku:24:in `<main>'

This issue came up for the first time today.  I did not make any changes that I'm aware of that are related.  This is on a system that has had the heroku toolbelt working without error for a while.

    OSX 10.10.3
    heroku-toolbelt/3.35.1 (x86_64-darwin10.8.0) ruby/1.9.3
    heroku-cli/4.17.2-7ab5f64 (amd64-darwin) go1.4.2
    === Installed Plugins
    heroku-oauth
    heroku-pg-extras

**Comment by dickeyxxx** [comment]
update your plugins `heroku plugins:update`

**Comment by KelseyDH** [comment]
@dickeyxx :+1: 

Might be a good idea to ask users in their error messages to run `heroku plugins:update` before reporting issues to Github.  Eg. the current error says:

```
 !    Unable to load plugin heroku-pg-extras.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new
```

**Comment by dickeyxxx** [comment]
this should fix up users still experiencing this bug https://github.com/heroku/heroku/pull/1566
