### ISSUE TITLE
Strange @ref markers printed for some config vars

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku#1542]
In `3.36.1`, when running `heroku config` without `--shell` on newer apps, `@ref` markers are printed for the value of variable names instead of the real value. This seems to only be a display issue, the variable is still set correctly otherwise. 

```
$ heroku version
heroku-toolbelt/3.36.1 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-repo

$ heroku apps:create 
Creating agile-everglades-4272... done, stack is cedar-14
https://agile-everglades-4272.herokuapp.com/ | https://git.heroku.com/agile-everglades-4272.git

$ heroku addons:create memcachier --app agile-everglades-4272
Creating warming-quietly-8063... done
Adding warming-quietly-8063 to agile-everglades-4272... done
Setting MEMCACHIER_PASSWORD, MEMCACHIER_SERVERS, MEMCACHIER_USERNAME and restarting agile-everglades-4272... done, v3
Please allow up to three minutes for MemCachier credentials to sync.
Use `heroku addons:docs memcachier` to view documentation.
```

I waited 5 minutes just to be sure it wasn't Memcachier. 

```
$ heroku config --app agile-everglades-4272
=== agile-everglades-4272 Config Vars
MEMCACHIER_PASSWORD: @ref:warming-quietly-8063:password
MEMCACHIER_SERVERS:  @ref:warming-quietly-8063:servers
MEMCACHIER_USERNAME: @ref:warming-quietly-8063:username

$ heroku config:get MEMCACHIER_USERNAME --app agile-everglades-4272
654202

$ heroku config --shell --app agile-everglades-4272
MEMCACHIER_PASSWORD=dxc224bg99
MEMCACHIER_SERVERS=mc5.dev.ec2.memcachier.com:11211
MEMCACHIER_USERNAME=654202

$ heroku run irb --app agile-everglades-4272
Running `irb` attached to terminal... up, run.5549
irb(main):001:0> ENV["MEMCACHIER_USERNAME"]
=> "654202"
irb(main):002:0> exit
```

(Passwords changed from real values in this output, and this app has already been destroyed)

**Comment by dickeyxxx** [comment]
very strange, but I can't reproduce.

What is the output of `heroku version`?

**Comment by dickeyxxx** [comment]
also, what happens if you do `heroku config:get`?

**Comment by csuhta** [comment]
> What is the output of heroku version?
> also, what happens if you do heroku config:get?

Both of these are in the first post. O_o

**Comment by dickeyxxx** [comment]
I want the *output* of `heroku version` to see what plugins you have installed (if any). You could also try running with `HEROKU_DEBUG`, that would tell me if the string are coming back from the API like that.

**Comment by csuhta** [comment]
```
$ heroku version
heroku-toolbelt/3.36.1 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-repo

$ HEROKU_DEBUG=1 heroku version
heroku-toolbelt/3.36.1 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-repo
```

What am I supposed to set `HEROKU_DEBUG` to? Doesn't appear to do anything.

**Comment by dickeyxxx** [comment]
set it to 1 and run the config command

**Comment by csuhta** [comment]
Hrm. No longer able to reproduce this myself, too. Maybe it was a fleeting API issue? Closing!

**Comment by dickeyxxx** [comment]
cc @brandur this seems to have gone away, but strange anyways

**Comment by brandur** [comment]
@dickeyxxx Hah, this is our "resource-symbols" feature I think. At some point a few customers seem to have been flagged into it, but I'm not sure exactly when that happened. Someone may have been doing it based on support tickets at some point. Either way though, I think we're going to migrate away from that system.

@csuhta Sorry about the trouble!
