### ISSUE TITLE
Heroku ToolBelt v4 update erros

### ISSUE THREAD

**Issue by nickmeulen** [heroku/heroku#1543]
I am getting error with heroku commands after it updated the toolbelt to v4. 

I get the following error log

Heroku client internal error.
No such file or directory - C:/Users/user/.heroku/heroku-cli.exe plugins
C:/Users/user/.heroku/client/lib/heroku/jsplugin.rb:54:in 
C:/Users/user/.heroku/client/lib/heroku/jsplugin.rb:54:in plugins
C:/Users/user/.heroku/client/lib/heroku/jsplugin.rb:61:in is_plugin_installed?'
C:/Users/user/.heroku/client/lib/heroku/jsplugin.rb:84:in install
C:/Users/user/.heroku/client/lib/heroku/command/git.rb:48:in remote
C:/Users/user/.heroku/client/lib/heroku/command.rb:227:in run
C:/Users/user/.heroku/client/lib/heroku/cli.rb:26:in start
C:/Program Files (x86)/Heroku/bin/heroku:29:in <main>

command line output as follows

    C:\Users\user\Documents\Development\co.paperclip>heroku git:remote -a paperclip-dev
    error loading plugin commands
    error loading plugin topics
    error loading plugin commands
    !    Heroku client internal error.
    !    Search for help at: https://help.heroku.com
    !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - C:/Users/user/.heroku/heroku-cli.exe plugins (Errno::ENOENT)
    Command:     heroku git:remote -a paperclip-dev
    Version:     heroku/toolbelt/3.36.1 (i386-mingw32) ruby/1.9.3
    Error ID:    cdf05c2ce17b48aa80f6fd048306864b

    More information in C:/Users/user/.heroku/error.log

**Comment by dickeyxxx** [comment]
what files are in `C:\Users\user\.heroku`?

**Comment by nickmeulen** [comment]
client folder
usage folder
autoupdate.last
error.log
heroku-cli.exe

**Comment by nickmeulen** [comment]
I uninstalled, deleted all folders and re-installed and did the following to no avail

    C:\Users\user>heroku version
    heroku/toolbelt/3.36.1 (i386-mingw32) ruby/1.9.3
    You have no installed plugins.

    C:\Users\user>heroku login
    Enter your Heroku credentials.
    Email: "email here"
    Password (typing will be hidden):
    Authentication successful.

    C:\Users\user>cd C:\Users\user\Documents\Development\co.paperclip

    C:\Users\user\Documents\Development\co.paperclip>heroku git:remote -a paperclip-dev
    Installing Heroku Toolbelt v4... done
    !    Heroku client internal error.
    !    Search for help at: https://help.heroku.com
    !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - C:/Users/user/.heroku/heroku-cli.exe plugins (Errno::ENOENT)
    Command:     heroku git:remote -a paperclip-dev
    Version:     heroku/toolbelt/3.36.1 (i386-mingw32) ruby/1.9.3
    Error ID:    cdaddf5e4e0a409a931797dd2096648e


    More information in C:/Users/user/.heroku/error.log


    C:\Users\Nick Meulen\Documents\Development\co.paperclip>

**Comment by dickeyxxx** [comment]
does your username have any non-ascii characters by chance? or is it just 'user'?

**Comment by nickmeulen** [comment]
username has a space in it. But the toolbelt has worked before. I multiple apps on heroku which I have uploaded before today.

**Comment by dickeyxxx** [comment]
ah that's the problem, fix inc

**Comment by nickmeulen** [comment]
username is an issue?

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku/pull/1545

**Comment by dickeyxxx** [comment]
I'll push this out shortly

**Comment by dickeyxxx** [comment]
alright, 3.36.2 is out with the fix

**Comment by nickmeulen** [comment]
Great, all working now. Thanks.
