### ISSUE TITLE
Error:       Proxy is invalid (Excon::Errors::ProxyParseError)

### ISSUE THREAD

**Issue by qwerty2323** [heroku/heroku#1556]
Tried to do:
env --unset=HTTP_PROXY and env --unset=HTTPS_PROXY
But it didn't help.

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       Proxy is invalid (Excon::Errors::ProxyParseError)
Backtrace:   /home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:450:in `setup_proxy'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:61:in `initialize'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon.rb:126:in `new'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon.rb:126:in `new'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/command/certs.rb:7:in `<class:Certs>'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/command/certs.rb:6:in `<top (required)>'
             /home/qwerty/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
             /home/qwerty/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/command.rb:14:in `block in load'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/command.rb:13:in `each'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/command.rb:13:in `load'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/lib/heroku/cli.rb:32:in `start'
             /home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.11.2/bin/heroku:17:in `<top (required)>'
             /home/qwerty/.rvm/gems/ruby-2.1.3/bin/heroku:23:in `load'
             /home/qwerty/.rvm/gems/ruby-2.1.3/bin/heroku:23:in `<main>'
             /home/qwerty/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
             /home/qwerty/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'

Command:     heroku version
HTTP Proxy:  
Version:     heroku-gem/3.11.2 (x86_64-linux) ruby/2.1.3
```

**Comment by dickeyxxx** [comment]
have you tried simply running `unset`? You've also got a pretty old version of the CLI

**Comment by qwerty2323** [comment]
Yes, I've tried. I've updated the gem, but the error is still up.
And there is no log file /home/qwerty/.heroku/error.log

Proxy is invalid
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:450:in `setup_proxy'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon/connection.rb:61:in `initialize'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon.rb:126:in `new'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/excon-0.45.3/lib/excon.rb:126:in `new'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command/certs.rb:8:in `<class:Certs>'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command/certs.rb:7:in `<top (required)>'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command.rb:24:in `require'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command.rb:24:in `block in load'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command.rb:23:in `each'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/command.rb:23:in `load'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/lib/heroku/cli.rb:26:in `start'
/home/qwerty/.rvm/gems/ruby-2.1.3/gems/heroku-3.36.7/bin/heroku:17:in `<top (required)>'
/home/qwerty/.rvm/gems/ruby-2.1.3/bin/heroku:23:in `load'
/home/qwerty/.rvm/gems/ruby-2.1.3/bin/heroku:23:in `<main>'
/home/qwerty/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/home/qwerty/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Proxy is invalid (Excon::Errors::ProxyParseError)
    Command:     heroku login
    HTTP Proxy:  
    Version:     heroku-gem/3.36.7 (x86_64-linux) ruby/2.1.3


    More information in /home/qwerty/.heroku/error.log

**Comment by dickeyxxx** [comment]
what is the output of this?

```
echo $HTTP_PROXY
echo $HTTPS_PROXY
```

**Comment by qwerty2323** [comment]
there is no output...just blank line

**Comment by dickeyxxx** [comment]
sorry this one slipped through the cracks, but if you're still having issues the problem is probably that the proxy is set to something that only appears blank. Make sure you unset the env variable completely (how to do this depends on your shell)

**Comment by trimble** [comment]
Any new news on this one, or should it be closed for cleanup?
