### ISSUE TITLE
fork command error: "Error: Cannot find module 'columnify'"

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku#1567]
When trying to fork our app, I got this error
```
00:19:29.205 + heroku fork --app source-app target-app
00:19:29.857 module.js:339
00:19:29.857     throw err;
00:19:29.857           ^
00:19:29.857 Error: Cannot find module 'columnify'
00:19:29.857     at Function.Module._resolveFilename (module.js:337:15)
00:19:29.857     at Function.Module._load (module.js:287:25)
00:19:29.857     at Module.require (module.js:366:17)
00:19:29.858     at require (module.js:385:17)
00:19:29.858     at Object.<anonymous> (/home/vagrant/.heroku/node_modules/heroku-fork/node_modules/heroku-cli-util/columnify.js:2:17)
00:19:29.858     at Module._compile (module.js:431:26)
00:19:29.858     at Object.Module._extensions..js (module.js:449:10)
00:19:29.859     at Module.load (module.js:356:32)
00:19:29.859     at Function.Module._load (module.js:311:12)
00:19:29.859     at Module.require (module.js:366:17)
```

**Comment by dickeyxxx** [comment]
did it just happen one? or is it working now?

**Comment by Taytay** [comment]
JUST happened. Working now.

**Comment by Taytay** [comment]
I swear, our build infrastructure is like a heroku stress test. :)

**Comment by dickeyxxx** [comment]
I know what happened. I released a fork update and it was caught in the middle of updating (remember I removed the message stating that)




I had an idea to fix this issue without blocking while an update is taking place and without just showing an annoying message on stderr.




I was thinking I could lock on each plugin so you would only have to wait for a single plugin to finish updating (which wouldn't take long at all)

**Comment by Taytay** [comment]
Unfortunately, it looks like it just failed again on the same build machine. I will try again. If I can't get this to work, do I need to update the fork command specifically?

**Comment by dickeyxxx** [comment]
Potentially, 'heroku plugins:install heroku-fork'

**Comment by dickeyxxx** [comment]
I think I figured this one out. The updater was touching the `~/.heroku/autoupdate` file so it knows the last time it updated AFTER it finished updating. Because some commands call the v4 cli 2-3 times, this means that 2-3 updates would be triggered all at once. I fixed it by checking to see if an update is needed right before performing it.

Let me know if you see it again though.
