### ISSUE TITLE
Heroku CLI yields : "timed out while updating" on every command

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku#1579]
All of our Linux build machines are currently experiencing the following. Running any heroku command hangs for a signicant amount of time (1 minute?) and then just prints:
`Timed out while updating`

Furthermore, the exit code returned by the command is still 0 (success), meaning that our scripts think everything is fine.

**Comment by Taytay** [comment]
This appears to be working now. Perhaps it was a transient issue?
I am still concerned about the exit code being 0, as it makes me worry that I might have missed this.

**Comment by dickeyxxx** [comment]
it was an incident: https://status.heroku.com/incidents/769




though it should’ve still executed your command
