### ISSUE TITLE
heroku git:clone Error:Cannot find module 'columnify'

### ISSUE THREAD

**Issue by yuan78** [heroku/heroku#1580]
when I run:
D:\>heroku git:clone -a guarded-reef-33585
 !   Error in heroku-git:
 !   module.js:339
    throw err;
          ^
Cannot find module 'columnify'
Attempting to repair heroku-git...
Repair complete. Try running your command again.

I reinstall the toolbelt, but it does not work, pls help solve

**Comment by dickeyxxx** [comment]
maybe try deleting `~/.heroku/.npm-cache` or `~/.heroku` entirely

**Comment by yuan78** [comment]
HI, I deleting ~/.heroku entirely, but it does not work, and report same error, how can I do? THX

**Comment by yuan78** [comment]
It's OK now, THX!
