### ISSUE TITLE
When run "git push heroku master" ,encounter errors 

### ISSUE THREAD

**Issue by yuan78** [heroku/heroku#1581]
Hi,
When run "git push heroku master" ,encounter errors 

remote:
remote: -----> Building dependencies
remote:        Installing node modules
remote:        npm ERR! TypeError: Arguments to path.resolve must be strings
remote:        npm ERR!     at Object.exports.resolve (path.js:313:15)
remote:        npm ERR!     at Object.exports.relative (path.js:370:20)
remote:        npm ERR!     at installOne_ (/tmp/build_8fb18dcdfd94eb22e8fbe6e1d
b9766f6/.heroku/node/lib/node_modules/npm/lib/install.js:707:26)
remote:        npm ERR!     at installOne (/tmp/build_8fb18dcdfd94eb22e8fbe6e1db
9766f6/.heroku/node/lib/node_modules/npm/lib/install.js:634:3)
remote:        npm ERR!     at /tmp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6/.hero
ku/node/lib/node_modules/npm/lib/install.js:520:9
remote:        npm ERR!     at /tmp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6/.hero
ku/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
remote:        npm ERR!     at Array.forEach (native)
remote:        npm ERR!     at /tmp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6/.hero
ku/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
remote:        npm ERR!     at Array.forEach (native)
remote:        npm ERR!     at asyncMap (/tmp/build_8fb18dcdfd94eb22e8fbe6e1db97
66f6/.heroku/node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:53:8)

remote:        npm ERR! If you need help, you may report this log at:
remote:        npm ERR!     <http://github.com/isaacs/npm/issues>
remote:        npm ERR! or email it to:
remote:        npm ERR!     <npm-@googlegroups.com>
remote:
remote:        npm ERR! System Linux 3.13.0-49-generic
remote:        npm ERR! command "node" "/tmp/build_8fb18dcdfd94eb22e8fbe6e1db976
6f6/.heroku/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/t
mp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6/.npmrc"
remote:        npm ERR! cwd /tmp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6
remote:        npm ERR! node -v v0.10.38
remote:        npm ERR! npm -v 1.1.71
remote:        npm ERR!
remote:        npm ERR! Additional logging details can be found in:
remote:        npm ERR!     /tmp/build_8fb18dcdfd94eb22e8fbe6e1db9766f6/npm-debu
g.log
remote:        npm ERR! not ok code 0
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing!
remote:
remote:        Are you running into a common issue?
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploy
s
remote:
remote:        During the build we spotted some likely problems:
remote:
remote:        - This version of npm (1.1.71) has several known issues - conside
r upgrading to the latest release (2.10.1)
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying
-an-npm-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to guarded-reef-3358.
remote:
To https://git.heroku.com/guarded-reef-3358.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/guarded-reef-3358.git

Pls advise how can I do now
'

**Comment by dickeyxxx** [comment]
please submit a support ticket. This project is for the CLI only.
