### ISSUE TITLE
Heroku-cli Syntax error

### ISSUE THREAD

**Issue by arenoth** [heroku/heroku#1583]
When running any of the heroku commands ie; heroku status, heroku git:clone, etc

I get this log

(precise)wjzhou@localhost:~$ heroku git:clone -a wecycle-webapp
Installing Heroku Toolbelt v4... done
/home/wjzhou/.heroku/heroku-cli: 1: /home/wjzhou/.heroku/heroku-cli: Syntax error: "(" unexpected
/home/wjzhou/.heroku/heroku-cli: 1: /home/wjzhou/.heroku/heroku-cli: Syntax error: "(" unexpected
/home/wjzhou/.heroku/heroku-cli: 1: /home/wjzhou/.heroku/heroku-cli: Syntax error: "(" unexpected

and then when I type "heroku status"

The following displays:
heroku-toolbelt/3.37.1 (armv7l-linux-eabihf) ruby/2.2.2
You have no installed plugins.

Description: Ubuntu 14.04.2 LTS

I'm not sure if this is an error on my part, but I've tried reinstalling heroku and ruby several times. Any help would be awesome

**Comment by shakna-israel** [comment]
Not alone. I've uninstalled, tried removing ```.heroku```, several times over. It successfully installs Heroku Toolbelt v3.37.2... It'll let me login, after that, almost every command gives this stacktrace:

```
heroku git:remote -a project
Installing Heroku Toolbelt v4... done
/home/pi/.heroku/heroku-cli: 1: /home/pi/.heroku/heroku-cli: Syntax error: "(" unexpected
/home/pi/.heroku/heroku-cli: 1: /home/pi/.heroku/heroku-cli: Syntax error: "(" unexpected
/home/pi/.heroku/heroku-cli: 1: /home/pi/.heroku/heroku-cli: Syntax error: "(" unexpected
```

**Comment by dickeyxxx** [comment]
what server are you hosting it on that uses arm?

**Comment by arenoth** [comment]
It's my local development environment, my computer is an arm computer

**Comment by dickeyxxx** [comment]
I'm able to reproduce this using a scaleway server (took me a while to find a cloud host that had arm). This uses [new code written in Go](https://github.com/heroku/heroku-cli) I probably need to setup to cross-compile to arm. Updates soon.

**Comment by dickeyxxx** [comment]
can you update and try again? you may need to delete `~/.heroku/heroku-cli`

**Comment by arenoth** [comment]
Hi, I deleted the CLI, reinstalled heroku via the wget, and while trying to clone, I once again ran into the same bug.

Were you able to get it working on your end? Let me know if you want me to test anything for you. I'll also try to completely uninstall heroku again, so if it works I'll post here, but I have a feeling it won't

**Comment by shakna-israel** [comment]
Completely uninstalling and reinstalling did work in my case, kind of. I got hit by io.js needing a newer version of libc6, but I'd be guessing that's another kettle of fish.

In sum, removing ```~/.heroku```, and ```apt-get remove heroku``` together, and then running ```wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh``` did seem to successfully run.

**Comment by arenoth** [comment]
Oh man, this is bizzare then
I "believe" that I have completely uninstalled heroku through several different ways including the way shown here and from above
https://devcenter.heroku.com/articles/heroku-command

I have then reinstalled from the wget but still having the same syntax error from earlier when running "heroku status"

**Comment by dickeyxxx** [comment]
maybe you forgot to do `apt-get update`?

**Comment by dickeyxxx** [comment]
you should be on `3.37.3`

**Comment by arenoth** [comment]
Unfortunately still no luck


However, I'm not sure if this is normal, but during reinstallation, this came up in the log

update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match rsync Default-Stop values (none)
 System start/stop links for /etc/init.d/rsync already exist.
runlevel:/var/run/utmp: No such file or directory


Here's my version info

(precise)user@localhost:~$ heroku version
/home/user/.heroku/heroku-cli: 1: /home/user/.heroku/heroku-cli: Syntax error: "(" unexpected
error loading plugin commands
heroku-toolbelt/3.37.3 (armv7l-linux-eabihf) ruby/2.2.2
You have no installed plugins.

**Comment by dickeyxxx** [comment]
I realize you have probably already done this, but could you delete `/home/user/.heroku/heroku-cli` one last time and retry? (I'm wondering if there was some versions of of sync)

If that doesn't work, can you show me the output of: 
```
$ ruby -e "p RbConfig::CONFIG['host_cpu']"
$ ruby -e "p RbConfig::CONFIG['host_os']"
```

**Comment by dickeyxxx** [comment]
I don't think that rsync issue is related at all btw

**Comment by arenoth** [comment]
No money man, deleted it,  then tried a reinstall again. Sorry it's been such a hassle to take care of, do you think it could be something on my end? Ie: ruby is having something funny going on? Let me know if you need anything else

Here are the logs provided below

(precise)user@localhost:~$ ruby -e "p RbConfig::CONFIG['host_cpu']"
"armv7l"

(precise)user@localhost:~$ ruby -e "p RbConfig::CONFIG['host_os']"
"linux-gnueabihf"

**Comment by dickeyxxx** [comment]
ah I see the issue. On the arm box I was testing it returned `arm` for the host cpu, but yours is `armv7l`. Fix incoming.

**Comment by dickeyxxx** [comment]
#1597

**Comment by dickeyxxx** [comment]
fixed in 3.37.4

**Comment by dickeyxxx** [comment]
have you had a chance to test it @arenoth?

**Comment by arenoth** [comment]
Hey @dickeyxxx 
I just got a chance to run heroku status

Setting up heroku-toolbelt (3.37.5) ...
(precise)user@localhost:~$ heroku status
Installing Heroku Toolbelt v4... done
Installing plugin heroku-status... done
=== Heroku Status
Production:   No known issues at this time. 
Development:  No known issues at this time. 

Looks all good to me, I'll repost if I run into any other issues with heroku

Thanks so much for the fix I appreciate it

**Comment by dickeyxxx** [comment]
great!
