### ISSUE TITLE
heroku command line fails

### ISSUE THREAD

**Issue by abienkowski** [heroku/heroku#1590]
+ heroku ps -a ps-ice4m-latest
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       no time information in "allow_until" (ArgumentError)
    Command:     heroku ps -a ps-ice4m-latest
    Plugins:     heroku-repo
    Version:     heroku-toolbelt/3.37.2 (x86_64-linux-gnu) ruby/2.1.5
    Error ID:    944240d697ba4c25887caf409cdc30f3

    More information in /opt/jenkins/jenkins_home/.heroku/error.log

**Comment by abienkowski** [comment]
Removing the heroku-repo causes new error.  All plugins have been reinstalled, including the heroku toolbelt itself.

-bash-4.1$ heroku apps
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       private method `select' called for #<String:0x00000001e537c8> (NoMethodError)
    Command:     heroku apps
    Version:     heroku-toolbelt/3.37.2 (x86_64-linux) ruby/2.0.0
    Error ID:    ff86ba241e2841b4a2d349a7ded4cee6


    More information in /opt/jenkins/jenkins_home/.heroku/error.log

-bash-4.1$

**Comment by abienkowski** [comment]
-bash-4.1$ heroku --version
heroku-toolbelt/3.37.2 (x86_64-linux-gnu) ruby/2.1.5
heroku-cli/4.19.28-8f2bd89 (amd64-linux) go1.4.2
=== Installed Plugins
heroku-apps@0.1.4
heroku-fork@3.0.4
heroku-git@2.2.3
heroku-redis@0.8.0
heroku-status@1.2.0

**Comment by dickeyxxx** [comment]
this likely means there is a json parsing error. Can you run the following?

```
ruby -r json -e "p JSON.parse('{}')"
```

**Comment by abienkowski** [comment]
I get the following, looks like a successful outcome.

-bash-4.1$ ruby -r json -e "p JSON.parse('{}')"
{}
-bash-4.1$

**Comment by abienkowski** [comment]
Is there a way to turn on some debug logs, which would help to trace where the issues is.

So far I've removed and reinstalled all apps and heroku tool-belt itself, without any effect.

I've removed the .heroku folder as well, and .netrc file, which re-initiated the login process.  Authentication kelp failing, even though I could still successfully sign into the account on other systems and through the UI.

**Comment by dickeyxxx** [comment]
yeah you can run it with `HEROKU_DEBUG=1`

**Comment by dickeyxxx** [comment]
it's possible the API may be returning invalid JSON. I'm assuming that's what it is since it is expecting an array but getting a string. The JSON parser catches exceptions and just returns the original string in that case.

**Comment by abienkowski** [comment]
Seems I could not find a solution to this issue, and had to rebuild the machine.  Thankfully its' done with Ansible. :)
