### ISSUE TITLE
maintenance command fails with mis-formatted .netrc

### ISSUE THREAD

**Issue by joshuatobin** [heroku/heroku#1592]
I noticed having a mis-formatted entry in `.netrc` file resulted in `heroku maintenance:on` / `heroku maintenance:off` command to fail.

For instance in my specific case having an entry missing the machine definition label prepending the hostname. The rest of the heroku commands work as expected with the mis-formatted entry. 

```bash
somehost.herokuapp.com
  login user@host
  password XXXX
```

**Comment by dickeyxxx** [comment]
ah that makes sense. That command is one of the new v4 commands which uses a Go parser for the netrc: https://github.com/bgentry/go-netrc

I took a stab last week at converting the ruby netrc gem over to Go so it would act identically, but I discovered a bug that even the current ruby netrc implementation wouldn't work if you had the password specified before the login. I may try to fix that and port it over again.

**Comment by ys** [comment]
Can we have an example of the wrong netrc entry? So i can track that

**Comment by joshuatobin** [comment]
@ys There is an example in the description but here is one type as well:

Good:

```
machine somehost.herokuapp.com
  login user@host
  password XXXX
```

Bad

```
somehost.herokuapp.com
  login user@host
  password XXXX
```

**Comment by ys** [comment]
Oh thanks, sorry about that part:D
