### ISSUE TITLE
pg:upgrade fails

### ISSUE THREAD

**Issue by diwu1989** [heroku/heroku#1606]
!    living-amply-4207 will be upgraded to a newer PostgreSQL version,
 !    stop following HEROKU_POSTGRESQL_JADE, and become writable.
 !    Use `heroku pg:wait` to track status
 !
 !    This cannot be undone.
...
Requesting upgrade... failed
 !    internal error

**Comment by dickeyxxx** [comment]
submit a support ticket for issues like this
