### ISSUE TITLE
Random errors in heroku cli

### ISSUE THREAD

**Issue by oguya** [heroku/heroku#1618]
I'm trying to run `heroku apps` but I keep getting the error:
<pre>`private method `select' called for #<String:0x00000002932450> (NoMethodError)`</pre>
I also keep getting random errors when using various heroku tools.

- show heroku apps

        $ heroku apps
         !    Heroku client internal error.
         !    Search for help at: https://help.heroku.com
         !    Or report a bug at: https://github.com/heroku/heroku/issues/new

            Error:       private method `select' called for #<String:0x00000002932450> (NoMethodError)
            Command:     heroku apps
            Version:     heroku-toolbelt/3.37.7 (x86_64-linux) ruby/2.2.2
            Error ID:    78f06c0967ec488693aa9033af657ea3

            More information in /home/james/.heroku/error.log

- error log

        $ cat /home/james/.heroku/error.log
        Heroku client internal error.
        private method `select' called for #<String:0x00000002932450>
        /home/james/.heroku/client/lib/heroku/command/apps.rb:33:in `index'
        /home/james/.heroku/client/lib/heroku/command.rb:212:in `run'
        /home/james/.heroku/client/lib/heroku/cli.rb:27:in `start'
        /home/james/src/heroku-client/bin/heroku:24:in `<main>'

- heroku ps

        $ heroku ps
         !    Heroku client internal error.
         !    Search for help at: https://help.heroku.com
         !    Or report a bug at: https://github.com/heroku/heroku/issues/new

            Error:       no time information in "allow_until" (ArgumentError)
            Command:     heroku ps
            Version:     heroku-toolbelt/3.37.7 (x86_64-linux) ruby/2.2.2
            Error ID:    8306fc723873465e882b81a68b1bdf7f

            More information in /home/james/.heroku/error.log

- error log

        $ cat /home/james/.heroku/error.log
        Heroku client internal error.
        no time information in "allow_until"
        /usr/share/ruby/time.rb:252:in `make_time'
        /usr/share/ruby/time.rb:364:in `parse'
        /home/james/.heroku/client/lib/heroku/command/ps.rb:129:in `index'
        /home/james/.heroku/client/lib/heroku/command.rb:212:in `run'
        /home/james/.heroku/client/lib/heroku/cli.rb:27:in `start'
        /home/james/src/heroku-client/bin/heroku:24:in `<main>'

- heroku version

        $ heroku version
        heroku-toolbelt/3.37.7 (x86_64-linux) ruby/2.2.2
        You have no installed plugins.

**Comment by dickeyxxx** [comment]
this is probably a JSON parsing error. Try reinstalling the toolbelt, or possibly ruby.

**Comment by oguya** [comment]
thanks @dickeyxxx. I decided to trash the system-wide ruby & install a new one in my home directory which fixed the random errors I was getting.
```
wget -qO- http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz | tar -xvz
cd ruby-2.2.2/
mkdir -p ~/apps/ruby/2.2.2
./configure --prefix=/home/james/apps/ruby/2.2.2
CC=clang make
make install
export PATH="/home/james/apps/ruby/2.2.2/bin:$PATH"
```

**Comment by dickeyxxx** [comment]
yeah somehow your compiled version of ruby didn't have json support, or had broken json support
