### ISSUE TITLE
CLI cannot detect app with remote in the format of https://git.heroku.com/someapp.git

### ISSUE THREAD

**Issue by holic** [heroku/heroku#1623]
I've been having trouble lately with new and old Heroku apps via my CLI. Most of my apps exist in the same parent `projects/` folder (e.g. `projects/someapp/`, `projects/otherapp/`).

Every time I'd run a command in one of these app directories (e.g. `heroku config`) I'd get the following message:

```
$ heroku config
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
```

`git config -l` shows a correctly configured Heroku remote:

```
remote.heroku.url=https://git.heroku.com/someapp.git
remote.heroku.fetch=+refs/heads/*:refs/remotes/heroku/*
branch.master.remote=heroku
branch.master.merge=refs/heads/master
```

After a bit of digging, I decided to try to remove the `heroku` remote and re-add it in the alternative URI format:

```
$ git remote add heroku git@heroku.com:someapp.git
```

This resolved the issue and further CLI commands (e.g. `heroku config`) now properly detect the app that I'm working with.

**Comment by dickeyxxx** [comment]
you're probably on an old version of the CLI

**Comment by holic** [comment]
```
$ heroku --version
heroku-toolbelt/3.38.1 (x86_64-darwin10.8.0) ruby/1.9.3
=== Installed Plugins
heroku-accounts
heroku-config
```

**Comment by dickeyxxx** [comment]
does `heroku maintenance` work when you use the http url? (that uses some different code)

**Comment by dickeyxxx** [comment]
By the way, you can quickly switch with 'heroku git:remote -a appname'

**Comment by holic** [comment]
It looks like `heroku git:remote -a appname` uses the same `https://` protocol that is causing issues:

```
$ heroku git:remote -a someapp
Installing Heroku Toolbelt v4... done
Installing plugin heroku-git... done
set git remote heroku to https://git.heroku.com/someapp.git

$ git remote -v
heroku	https://git.heroku.com/someapp.git (fetch)
heroku	https://git.heroku.com/someapp.git (push)

$ heroku config
 !    Multiple apps in folder and no app specified.
 !    Specify app with --app APP.

$ heroku --version
heroku-toolbelt/3.38.1 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.20.7-c71480f (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-accounts
heroku-config
heroku-git@2.3.1
```

Then running `heroku maintenance`:

```
$ heroku maintenance
Installing plugin heroku-apps... done
off

$ heroku maintenance
off

$ heroku config
 !    Multiple apps in folder and no app specified.
 !    Specify app with --app APP.
```

**Comment by dickeyxxx** [comment]
Oh this is a bug with the heroku-accounts plugin probably

**Comment by holic** [comment]
Yep, you're right. Looks like a few are having the exact issue and have solved it in the same way:
https://github.com/ddollar/heroku-accounts/issues/81#issuecomment-112889740

**Comment by holic** [comment]
I've just uninstalled `heroku-accounts` for now and everything's working again. Been a while since I needed to manage multiple Heroku accounts anyway.

Cheers!

**Comment by jhubert** [comment]
@holic Heroku has an official fork that supports https remotes: https://github.com/heroku/heroku-accounts

**Comment by holic** [comment]
@jhubert Awesome! Thanks for pinging me.
