### ISSUE TITLE
Cannot see new Github organizations

### ISSUE THREAD

**Issue by aequasi** [heroku/heroku#1626]
Under Deploy > GitHub

When you click the dropdown, it doesn't seem to show newly added organizations, since connecting your app.

**Comment by jmccartie** [comment]
Please open a support ticket at http://help.heroku.com  That will allow us to follow-up and find a solution.

**Comment by aequasi** [comment]
Sorry, thought you meant here. Created it!

**Comment by mushishi78** [comment]
+1 @aequasi Was there a way to get it to work?

**Comment by aequasi** [comment]
![Yeah](http://content.screencast.com/users/aequasi/folders/Jing/media/78c3634a-79b5-4154-9e88-aeb2d23e51da/00000280.png)

**Comment by mushishi78** [comment]
Thanks alot! That's worked great.
