### ISSUE TITLE
New to Heroku, following the Windows guide -- Login Error

### ISSUE THREAD

**Issue by footprintsusa** [heroku/heroku#1639]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\jburgess>jruby -S gem install bundler
io/console not supported; tty will not be manipulated
Fetching: bundler-1.10.5.gem (100%)
Successfully installed bundler-1.10.5
1 gem installed

C:\Users\jburgess>heroku login
Enter your Heroku credentials.
Email: hidden@hidden.com
Password (typing will be hidden):
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Permission denied - U:/_netrc (Errno::EACCES)
    Command:     heroku login
    Version:     heroku/toolbelt/3.38.2 (i386-mingw32) ruby/1.9.3
    Error ID:    a31c7af6eceb4bcdbfcd5592db304547

    More information in U:/.heroku/error.log

Permission denied - U:/.heroku
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `mkd
ir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `fu_
mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:221:in `blo
ck (2 levels) in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `rev
erse_each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `blo
ck in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `eac
h'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `mkd
ir_p'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:456:in `error_log'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:450:in `styled_error'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:39:in `rescue in start'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:19:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
Permission denied - U:/_netrc
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1140:in `in
itialize'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1140:in `op
en'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1140:in `re
scue in block in touch'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1136:in `bl
ock in touch'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1134:in `ea
ch'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:1134:in `to
uch'
C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:186:in `write_credentials'
C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:268:in `ask_for_and_save_creden
tials'
C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:106:in `get_credentials'
C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:41:in `login'
C:/Program Files (x86)/Heroku/lib/heroku/command/auth.rb:31:in `login'
C:/Program Files (x86)/Heroku/lib/heroku/command.rb:212:in `run'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:27:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

C:\Users\jburgess>

**Comment by dickeyxxx** [comment]
it needs permission to write to your home directory. In this case `H:\`

**Comment by footprintsusa** [comment]
Alright, and how am to give it permission to write to my directory?

**Comment by dickeyxxx** [comment]
http://www.wikihow.com/Change-File-Permissions-on-Windows-7

**Comment by footprintsusa** [comment]
Alright, that part makes sense -- what about if I did not want that to be the home directory? I'd rather it stay on my C:/ drive vs. the U:/ drive as that one is on the network and really not the one I wish to use for this database.

**Comment by dickeyxxx** [comment]
set the `HOME` environment variable

**Comment by footprintsusa** [comment]
Dickeyxxx, I just want to thank you so much -- I hadn't a clue how to change all of that and now I do and it is working flawlessly! Thank you kind sir, and have a great day.
