### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by jona872** [heroku/heroku#1640]
Error:       Permission denied - /home/jona872/.heroku/autoupdate.last (Errno::EACCES)
 Command:     heroku login
 Version:     heroku-toolbelt/3.39.1 (i686-linux) ruby/1.9.3
 Error ID:    6218c5a1e6a7426f8cade0ee0bb2c8e8

loggin with correct data, seem to be tring to finish another operation and crash

**Comment by dickeyxxx** [comment]
it needs permission to write to that file
