### ISSUE TITLE
'heroku pg:backups restore' stuck on "Pending"

### ISSUE THREAD

**Issue by billba** [heroku/heroku#1645]
I'm having the same problem as https://github.com/heroku/heroku/issues/1459, but with restore.

I did this exact thing successfully last week and it restored almost instantly. Today it's stuck on 'pending'. Needless to say today's the day I'm supposed to deploy the live site, so this is awesome timing!

**Comment by billba** [comment]
Update: eventually canceled (for the second time), tried again half an hour later and it worked fine. So maybe just some temporary congestion?

**Comment by dickeyxxx** [comment]
please submit a support ticket for issues like this, this project is for the CLI only
