### ISSUE TITLE
Invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by ptsiakos77** [heroku/heroku#1658]
When running a rake tasks that performs operations on postgress DB I encounter sporadically the following error:

Error:       invalid byte sequence in UTF-8 (ArgumentError)
    Command:     heroku run rake demo:populate --app staging-workable-workablestg3
    Version:     heroku-toolbelt/3.39.5 (x86_64-linux) ruby/2.2.2
    Error ID:    4af97dbf537e4132b613149a3f44faf2

The error.log file contains the following info:
/usr/local/heroku/lib/heroku/client/rendezvous.rb:109:in `gsub'
/usr/local/heroku/lib/heroku/client/rendezvous.rb:109:in `fixup'
/usr/local/heroku/lib/heroku/client/rendezvous.rb:75:in `block in start'
/usr/local/heroku/lib/heroku/client/rendezvous.rb:53:in `loop'
/usr/local/heroku/lib/heroku/client/rendezvous.rb:53:in `start'
/usr/local/heroku/lib/heroku/command/run.rb:149:in `rendezvous_session'
/usr/local/heroku/lib/heroku/command/run.rb:136:in `run_attached'
/usr/local/heroku/lib/heroku/command/run.rb:41:in `index'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:45:in `start'
/usr/bin/heroku:25:in `<main>'
Heroku client internal error.
invalid byte sequence in UTF-8

**Comment by dickeyxxx** [comment]
this code has all moved to node so it should be fixed now
