### ISSUE TITLE
Compatibility with Grails 3.0.3

### ISSUE THREAD

**Issue by felansu** [heroku/heroku#1661]

**Comment by jingweno** [comment]
@felansu You're filing the issue to the wrong repo. This repo is about the [Heroku CLI](https://devcenter.heroku.com/articles/heroku-command). I believe you're looking for [the Grails buildpack](https://github.com/heroku/heroku-buildpack-grails).

**Comment by felansu** [comment]
thanks man!

**Comment by jingweno** [comment]
Closing
