### ISSUE TITLE
Undefined method `confirm_billing` adding an addon

### ISSUE THREAD

**Issue by raldred** [heroku/heroku#1671]
heroku addons:create autobus:trip

    Error:       undefined method `confirm_billing' for Heroku::Helpers:Module (NoMethodError)
    Command:     heroku addons:create autobus:trip
    Version:     heroku-toolbelt/3.39.5 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    88ef2465ffbd43d5be7971b8b3e299e0

Heroku client log:

    Heroku client internal error.
    undefined method `confirm_billing' for Heroku::Helpers:Module
    /usr/local/heroku/lib/heroku/command.rb:217:in `rescue in run'
    /usr/local/heroku/lib/heroku/command.rb:268:in `run'
    /usr/local/heroku/lib/heroku/cli.rb:27:in `start'
    /usr/bin/heroku:24:in `<main>'

**Comment by dickeyxxx** [comment]
@pedro do you know what's going on here? looks like some code was removed but is still referenced: https://github.com/heroku/heroku/commit/ccb1b
https://github.com/heroku/heroku/blob/master/lib/heroku/command.rb#L216-L217

**Comment by raldred** [comment]
@dickeyxxx to give you some context, it turns out that the owner of the app I was developing and trying to add the addon to has not paid their bill.

**Comment by dickeyxxx** [comment]
that makes sense, this is just presenting the error message badly. I've added https://github.com/heroku/heroku/pull/1673 to address that
