### ISSUE TITLE
Not able to git clone using heroku

### ISSUE THREAD

**Issue by jay3126** [heroku/heroku#1674]
I am not able to clone the repo using heroku. I am using Mac OS X Yosemite version 10.10.4
Following is the error information. Please suggest.

    Error:       Permission denied - /Users/jay/.heroku/cacert.pem (Errno::EACCES)
    Command:     heroku git:clone -a coahs
    Version:     heroku-toolbelt/3.40.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    80ee6b3287ed4408bb1c4a452c8d32e1

**Comment by dickeyxxx** [comment]
that file needs to be writable
