### ISSUE TITLE
Load Error from Heroku Login using Windows CLI

### ISSUE THREAD

**Issue by chidumaga** [heroku/heroku#1686]
I am trying to set heroku up on my local Windows machine. When I run `heroku login` and enter my email address, the console spits out this error:

```
Password (typing will be hidden): C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb
n `initialize': No such file or directory (LoadError)
    from C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `dlopen'
    from C:/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `initialize'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:236:in `new'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:236:in `ask_
    assword_on_windows'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:211:in `ask_
    redentials'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:262:in `ask_
    nd_save_credentials'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:106:in `get_
    ntials'
    from C:/Users/shree1/.heroku/client/lib/heroku/auth.rb:41:in `login
    from C:/Users/shree1/.heroku/client/lib/heroku/command/auth.rb:31:i
    gin'
    from C:/Users/shree1/.heroku/client/lib/heroku/command.rb:221:in `r
    from C:/Users/shree1/.heroku/client/lib/heroku/cli.rb:39:in `start'
    from C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
```

From searching around for a solution online I gather that this should work in the bin folder of heroku's install directory, and in my project folder if I edit my system path to include my Ruby version after Heroku as per:

`C:\Program Files (x86)\Heroku\bin;C:\Ruby21-x64\bin`

However this is not the case. I still get the LoadError even from my install dir and editing the path makes no difference. Have no clue about what to tinker with next. 

Any help will be greatly appreciated.

**Comment by dickeyxxx** [comment]
it shouldn't be using your version of ruby, maybe try uninstalling it to see if that fixes it first

**Comment by chernetsov0** [comment]
@chidumaga If you're using Windows 10 see #1696

**Comment by chidumaga** [comment]
Not a solution but I eventually uninstalled my version of Ruby and installed a 32-bit version to get it working.

**Comment by chernetsov0** [comment]
If everyone else has this issue, try replacing `crtdll` with `msvcrt` [here](https://github.com/heroku/heroku/blob/v3.41.3/lib/heroku/auth.rb#L245) and write back if it works. Will try to do pull request.

@chidumaga can you verify that login still works with this change?
