### ISSUE TITLE
Update hash signature mismatch; been lots of updates to the heroku CLI today, at least the 2nd -- real or hacked?

### ISSUE THREAD

**Issue by notjonathan** [heroku/heroku#1688]
updating Heroku CLI... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Update hash signature mismatch (Heroku::Command::CommandFailed)
    Command:     heroku config:set --app [ redacted ]
    Version:     heroku-toolbelt/3.41.1 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    f464d222398649c2a5bdaa7aab50a44c

**Comment by dickeyxxx** [comment]
It seems the latest release was incomplete. I pushed out a new one, seems to be good now. Thanks for posting!
