### ISSUE TITLE
Latest release broke addons:open

### ISSUE THREAD

**Issue by ekosz** [heroku/heroku#1709]
Running:

```bash
$ heroku addons:open newrelic
```

Produces this error:

```bash
!    Ambiguous identifier; multiple matching add-ons found: advising-keenly-3809, advising-subtly-7596, cooking-softly-5080, dozing-amply-4192, dreaming-peacefully-9087, drifting-peacefully-4130, reading-gladly-9015, reading-patiently-3721, relaxing-sweetly-5446, sighing-coyly-7978, soaring-newly-6491, swimming-coyly-6119, swimming-freely-4442, unwinding-freely-3061, warming-newly-3132.
```

Version info:

```
$ heroku --version
heroku-toolbelt/3.41.4 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.22.2-6d52139 (amd64-darwin) go1.5
=== Installed Plugins
heroku-apps@0.2.0
heroku-fork@3.1.4
heroku-git@2.4.1
heroku-local@4.0.1
heroku-run@2.5.3
heroku-status@1.2.1
```

**Comment by dickeyxxx** [comment]
this is fixed

**Comment by jon-ga** [comment]
I'm seeing this same issue with 

```
$ heroku addons:open scheduler
 !    Ambiguous identifier; multiple matching add-ons found: ...
```

Version info:
```
$ heroku --version
heroku-toolbelt/3.42.21 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.27.2-eb1b3ca (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-accounts
heroku-apps@0.5.2
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.3
heroku-local@4.1.5
heroku-run@2.9.1
heroku-status@1.2.2
```

**Comment by bebbi** [comment]
same here with
$ heroku addons:destroy <someaddon>
and
$ heroku addons:upgrade <someaddon>

 heroku --version
heroku-toolbelt/3.40.6 (universal.x86_64-darwin13) ruby/2.0.0
heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2
=== Installed Plugins
heroku-apps@1.0.0
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.4
heroku-local@4.1.5
heroku-pipeline
heroku-run@2.9.2
heroku-status@1.2.4

**Comment by halilim** [comment]
I've just got 2.1 MB worth of identifiers:

```bash
heroku addons:open newrelic
# =>  ▸    Ambiguous identifier; multiple matching add-ons found: advising-ably-1366, ... ~90k more
heroku --version
# => heroku-toolbelt/3.42.48 (x86_64-darwin10.8.0) ruby/1.9.3
# => heroku-cli/4.29.4-6a9494e (amd64-darwin) go1.6
# => === Installed Plugins
# => heroku-apps@1.7.3
# => heroku-cli-addons@0.3.0
# => heroku-config
# => heroku-fork@4.1.2
# => heroku-git@2.4.5
# => heroku-local@5.0.1
# => heroku-orgs@1.0.7
# => heroku-pipelines@1.1.3
# => heroku-repo
# => heroku-run@3.1.3
# => heroku-spaces@2.1.2
# => heroku-status@2.1.2
```
(installed a few minutes ago from https://devcenter.heroku.com/toolbelt-downloads/osx)

**Comment by dickeyxxx** [comment]
@heroku/add-ons

**Comment by cdwort** [comment]
Hey @jon-ga @halilim , 

Thanks for bringing this to our attention. We found a recently introduced bug in the API behind this command. We expect a fix to be released in the next day, and when that happens, the command will be fixed for you without any updates to the CLI.

In the mean time, running this command for an individual app should work as normal, e.g. `heroku addons:open newrelic --app my-app`, although that may not get you the information you need.

Thank you again for bringing this to our attention.

**Comment by dickeyxxx** [comment]
https://github.com/heroku/heroku-cli/issues/254

**Comment by bjeanes** [comment]
The API issue has been fixed.
