### ISSUE TITLE
Unable to "Heroku Login" from git

### ISSUE THREAD

**Issue by aldenoah** [heroku/heroku#1710]
I am unable to login to heroku from git and my browser anymore. This is what I see.

 Error:       An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
 Command:     heroku logs
 Version:     heroku/toolbelt/3.41.3 (i386-mingw32) ruby/1.9.3
 Error ID:    8a9df87b2cdc4d4fa3ec76cc8bf64cfb

how do i fix this?

**Comment by dickeyxxx** [comment]
There probably isn't anything I can do to help—this is an issue with your internet connection. If you're behind a proxy make sure it's setup correctly. https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy

**Comment by Robert-Janagap** [comment]
hey @dickeyxxx thanks a lot for the link. It works 100%. https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy
