### ISSUE TITLE
heroku auto update get in the way when we are trying to solve urgent issues

### ISSUE THREAD

**Issue by phuongnd08** [heroku/heroku#1715]
it's really annoying when we try to access to heroku to solve the issues and the toolbelt trying to update itself. it should give us the option to skip the update to a later in time rather than get it the way in a rude way like it currently do.

**Comment by dickeyxxx** [comment]
this was moved to be asynchronous, though you may have to reinstall to get it

**Comment by phuongnd08** [comment]
Thank you.
