### ISSUE TITLE
cannot login from windows toolbelt

### ISSUE THREAD

**Issue by joshzume** [heroku/heroku#1719]
I copy/paste the same password I use for web but login always fails.

PS D:\> heroku login
Enter your Heroku credentials.
Email: josh@XXXXXX
Password (typing will be hidden):
Authentication failed.
Enter your Heroku credentials.
Email: josh@XXXXXXX
Password (typing will be hidden):
Authentication failed.
Enter your Heroku credentials.
Email: josh@XXXXXXX
Password (typing will be hidden):
Authentication failed.
PS D:\> heroku version
heroku/toolbelt/3.41.5 (i386-mingw32) ruby/1.9.3
You have no installed plugins.

**Comment by dickeyxxx** [comment]
this should be resolved now
