### ISSUE TITLE
error output not complete

### ISSUE THREAD

**Issue by ianstormtaylor** [heroku/heroku#1721]
Running into an issue with `heroku local` where the full stack trace of an error isn't printed, making it really hard to do any serious development. 

With `heroku local` I only get the offending line:

```
$ heroku local
forego | starting web.1 on port 5000
web.1  | /Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2
```

Whereas with `foreman` I get a full stack trace:

```
$ foreman start
17:29:48 web.1  | started with pid 2303
17:29:48 web.1  | /Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2
17:29:48 web.1  | throw new Error('stop!');
17:29:48 web.1  | ^
17:29:48 web.1  | Error: stop!
17:29:48 web.1  |     at Object.<anonymous> (/Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2:7)
17:29:48 web.1  |     at Module._compile (module.js:434:26)
17:29:48 web.1  |     at Object.Module._extensions..js (module.js:452:10)
17:29:48 web.1  |     at Module.load (module.js:355:32)
17:29:48 web.1  |     at Function.Module._load (module.js:310:12)
17:29:48 web.1  |     at Function.Module.runMain (module.js:475:10)
17:29:48 web.1  |     at startup (node.js:117:18)
17:29:48 web.1  |     at node.js:951:3
17:29:48 web.1  | exited with code 1
17:29:48 system | sending SIGTERM to all processes
SIGTERM received
```

I opened an issue on `forego` too, since it seems to be a problem further down, but wanted to open this here since it makes the built-in `heroku local` command very hard to use. https://github.com/ddollar/forego/issues/67

**Comment by ErikEvenson** [comment]
Bumping this as this is a serious time-killer.

**Comment by raimo** [comment]
+1 This is a serious problem that really needs to get fixed.

**Comment by phaddius** [comment]
+1 me too

**Comment by liron00** [comment]
A great workaround is to use Node Foreman's "nf start" to run your Heroku app locally.

https://coderwall.com/p/qdluuq/node-js-node-foreman

Basically `nf start` is identical to `heroku local` but prints the full log.

**Comment by MaxPleaner** [comment]
Seconding this, and also tried multiple fixes including changing the `RAILS_ENV` environment variable to development as well as changing the `LOG_LEVEL` environment level to `debug` or `info`. Nothing has any effect.

**Comment by chkuendig** [comment]
@liron00's workaround works perfect, but still annoying that heroku local doesn't cover this

**Comment by nodeit** [comment]
+1

**Comment by RGafiyatullin** [comment]
@liron00 , many thanks!

**Comment by dickeyxxx** [comment]
this is fixed now
