### ISSUE TITLE
`heroku releases` lists my username for GitHub auto-deployed releases

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku#1722]
I have the GitHub auto-deploy feature set up (ie: push to GitHub master and the app is auto-deployed).

The last N+ deploys have all been due to this feature, rather than by be manually deploying, yet:
```bash
[~/src/treeherder]$ heroku releases
=== treeherder-heroku Releases
v373  Deploy 655ee07  emorley@SNIP.com  2015/09/14 17:54:10 (~ 1h ago)
v372  Deploy f7aa033  emorley@SNIP.com  2015/09/14 17:36:05 (~ 1h ago)
v371  Deploy 6a62082  emorley@SNIP.com  2015/09/14 17:03:35 (~ 1h ago)
v370  Deploy 120ae4f  emorley@SNIP.com  2015/09/14 11:24:42 (~ 7h ago)
v369  Deploy 5ca2e89  emorley@SNIP.com  2015/09/11 22:15:11
v368  Deploy 64cb103  emorley@SNIP.com  2015/09/11 19:37:39
v367  Deploy 1961495  emorley@SNIP.com  2015/09/11 17:49:54
...
```

...where `emorley@SNIP.com` is the email addressed associated with my Heroku account. Over half of the pushes listed above were triggered by commits made by other users, not me.

I would have expected "user" to instead be one of:
* "GitHub auto-deploy from master"
*  (The empty string)
* The email address of committer of the GitHub push that triggered the auto-deploy, not my account

Thanks! :-)

**Comment by dickeyxxx** [comment]
This isn't related to the CLI, you should submit a support ticket instead

**Comment by edmorley** [comment]
Thanks done - https://help.heroku.com/tickets/278051
