### ISSUE TITLE
Ruby on Rails Heroku Application Error

### ISSUE THREAD

**Issue by manithink** [heroku/heroku#1733]
I have deployed my rails app on heroku. It was working fine.
Now accidentally not working. i am not changing any code or config in my app.

My app "https://homa-testing-app.herokuapp.com"

I am getting this error as below,
" Error: An existing connection was forcibly closed by the remote host."

2015-09-17T12:18:49.260849+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-09-17T12:18:49.245359+00:00 heroku[web.1]: Process exited with status 137

How to resolve it. Please help me.

Thanks in advance.

**Comment by dickeyxxx** [comment]
this project is for the cli, please submit a support ticket
