### ISSUE TITLE
Error loading plugins!!!!!

### ISSUE THREAD

**Issue by sam0516** [heroku/heroku#1741]
I've done installed Heroku Toolbet v4. But still set up node-4.1.1... failed n loading plugins failled. Need solutions for it.
![heroku](https://cloud.githubusercontent.com/assets/14818298/10092552/465a6f3a-637a-11e5-99ba-b550d0d89586.png)

**Comment by dickeyxxx** [comment]
I believe this will fix this https://github.com/heroku/heroku/pull/1742

**Comment by dickeyxxx** [comment]
can you update and try again?

**Comment by intellisense** [comment]
@dickeyxxx This is not fixed. I have just encountered the same error.

**Comment by dickeyxxx** [comment]
what version are you on @intellisense?

**Comment by ducnvhn** [comment]
having same eror. cannot run any heroku command (include heroku version) . This is what I get trying to run heroku in mysgit : 
![image](https://cloud.githubusercontent.com/assets/4236292/10183982/689384bc-6760-11e5-80b5-6e953201cfea.png)

**Comment by dickeyxxx** [comment]
@ducnvhn that isn't the same error. Can you show me the contents of heroku.bat? You could also try reinstalling.

**Comment by ducnvhn** [comment]
hi Dickey. 
bellow is my heroku.bat in C:\Program Files (x86)\Heroku\bin

:: Don't use ECHO OFF to avoid possible change of ECHO
:: Use SETLOCAL so variables set in the script are not persisted
@SETLOCAL

:: Add bundled ruby version to the PATH, use HerokuPath as starting point
@SET HEROKU_RUBY="%HerokuPath%\ruby-1.9.3\bin"
@SET PATH=%HEROKU_RUBY%;%PATH%;%ProgramFiles(x86)%\Git\bin

:: Invoke 'heroku' (the calling script) as argument to ruby.
:: Also forward all the arguments provided to it.
@ruby.exe "%~dpn0" %*

I have tried re-install heroku several times but still not working. 
tried to run heroku from windows cmd and it hang at "Setting up node-v4.1.1..... "

**Comment by dickeyxxx** [comment]
I put in a fix for cygwin that apparently broke git bash. If you reinstall with the latest from toolbelt.heroku.com you should be good.

**Comment by ducnvhn** [comment]
Thank you Dickey . 
Now Heroku toolbelt works nicely with my Git Bash.
