### ISSUE TITLE
Error with heroku login on window 8.1

### ISSUE THREAD

**Issue by joshijimit** [heroku/heroku#1746]
I installed heroku toolbelt in my D drive. On running "heroku login" from cmd first time, gave me below error. When I run it again, it shows "Installing Heroku Toolbelt v4... Done", however it hung on installing nodejs. On running it third time, I got everything ok and I was able to login through my heroku credentials. But when I restarted my machine and try to login again using "heroku login" it displayed below error again. Why it always trying to install heroku on heroku login command. Is it because I have installed it on D drive and not on C.

C:\Users\admin>heroku login
Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       read timeout reached (Excon::Errors::Timeout)
    Command:     heroku --version
    Version:     heroku/toolbelt/3.42.3 (i386-mingw32) ruby/1.9.3
    Error ID:    17b0f8b5e1cc4346a615b75602d4b894

    More information in C:/Users/admin/.heroku/error.log

More Errors on another attempt:

C:\Users\admin>heroku --version
Installing Heroku Toolbelt v4... done.
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
Setting up node-v4.1.1... ?    read tcp 192.168.1.103:52542->54.230.148.53:443:
wsarecv: An existing connection was forcibly closed by the remote host.
error loading plugin commands
error loading plugin topics
error loading plugin commands
heroku/toolbelt/3.42.3 (i386-mingw32) ruby/1.9.3
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - "C:/Users/admin/.heroku/heroku-cli.
exe" version (Errno::ENOENT)
    Command:     heroku --version
    Version:     heroku/toolbelt/3.42.3 (i386-mingw32) ruby/1.9.3
    Error ID:    060c570c73d84ee9897471a71436247b

    More information in C:/Users/admin/.heroku/error.log

More Updates: I have installed it in C drive and there too having same issue. After few attempts I managed to get logged in through command prompt, cloned Java sample from git and when I executed heroku create, it again started to install Toolbelt. It's driving me crazy. Please note that its a same command prompt in which i have executed heroku login and got successfully authenticated.

D:\Projects\R&D\Heroku\java-getting-started>heroku create
Installing Heroku Toolbelt v4... done.
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
Setting up node-v4.1.1...

**Comment by dickeyxxx** [comment]
can you update and try again?

**Comment by joshijimit** [comment]
Working fine now. May I know the root cause please.

**Comment by dickeyxxx** [comment]
your home drive is on a network drive, this prevents windows from allowing a connection with the executable I place there. I resolved it by using $LOCALAPPDATA instead of the home directory
