### ISSUE TITLE
heroku cannot start from git bash - mysgit

### ISSUE THREAD

**Issue by ducnvhn** [heroku/heroku#1749]
I try to run the heroku version (or any other heroku command ) from git bash and get this error: 
$ heroku version
/c/Program Files (x86)/Heroku/bin/heroku.bat: line 9: unexpected EOF while looking for matching `''
/c/Program Files (x86)/Heroku/bin/heroku.bat: line 12: syntax error: unexpected end of file
work around: 
1.uninstall heroku, node.js , ruby... and all folder and install again 
2.delete all relate folder and install again
3.run heroku from windows cmd as administrator 
all of these above not help it to work again , please help.

**Comment by dickeyxxx** [comment]
try reinstalling, a fix went out for this a few days ago

**Comment by ducnvhn** [comment]
Thanks Dickey, 
it's working on my machine now.
