### ISSUE TITLE
heroku login on windows looking for h: 

### ISSUE THREAD

**Issue by thehellmaker** [heroku/heroku#1750]
C:\Users\akash\Documents\fox-server>heroku version
heroku/toolbelt/3.41.5 (i386-mingw32) ruby/1.9.3
You have no installed plugins.
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory - H: (Errno::ENOENT)
    Command:     heroku version
    Version:     heroku/toolbelt/3.41.5 (i386-mingw32) ruby/1.9.3
    Error ID:    67691eb35e604371842873ba920dfa83

    More information in H:/.heroku/error.log

No such file or directory - H:
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `mkd
ir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `fu_
mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:221:in `blo
ck (2 levels) in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `rev
erse_each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `blo
ck in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `eac
h'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `mkd
ir_p'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:461:in `error_log'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:455:in `styled_error'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:39:in `rescue in start'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:19:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
No such file or directory - H:
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `mkd
ir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `fu_
mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:221:in `blo
ck (2 levels) in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `rev
erse_each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `blo
ck in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `eac
h'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `mkd
ir_p'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:98:in `autoupdate'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:28:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

C:\Users\akash\Documents\fox-server>^T

**Comment by dickeyxxx** [comment]
what is your `%LOCALAPPDATA% env var set to? It's probably that non-existent drive.
