### ISSUE TITLE
says remote doesn't exist when it does

### ISSUE THREAD

**Issue by drewB** [heroku/heroku#1751]
Since a recent update, when I do `heroku run console ---remote=<remotename>` is always returns an error that remote doesn't exist.  Then is lists the available remotes including the one I used.

**Comment by dickeyxxx** [comment]
you probably used to use the deprecated heroku-accounts plugin. Just run `heroku git:remote -a appname -r remotename` and it will fix them for you

**Comment by drewB** [comment]
never used any plugins for that.  I ran the command which appeared to be successful but the error continues.

**Comment by dickeyxxx** [comment]
what is the error exactly? can you show me the command + output?

**Comment by drewB** [comment]
heroku run console --remote=production
 ▸    could not find git remote --remote=production in <file path>
 ▸    remotes: production staging

**Comment by dickeyxxx** [comment]
what remotes are listed in `git remote -vv`?

**Comment by drewB** [comment]
production	https://git.heroku.com/<appname>.git (fetch)
production	https://git.heroku.com/<appname>.git (push)
staging	git@heroku.com:<stagingapp name>.git (fetch)
staging	git@heroku.com:<stagingapp name>.git (push)

it is related to https vs git protocol?

**Comment by dickeyxxx** [comment]
is there no app name? it should look like this:
```
production https://git.heroku.com/myapp.git (push)
```

**Comment by drewB** [comment]
take another look at the comment.  I updated right after posting (github formatting issue)

**Comment by dickeyxxx** [comment]
is `HEROKU_GIT_HOST` or `HEROKU_HTTP_GIT_HOST` set? I copy + pasted your remotes and mine was able to parse it. Also, what is the output of `heroku version`?

**Comment by drewB** [comment]
HEROKU_GIT_HOST and HEROKU_HTTP_GIT_HOST are not set.  Output of heroku version:

heroku-toolbelt/3.42.3 (x86_64-linux) ruby/1.9.3
heroku-cli/4.24.4-d580541 (amd64-linux) go1.5.1
=== Installed Plugins
heroku-apps@0.2.2
heroku-cli-addons@0.0.1
heroku-fork@3.1.4
heroku-git@2.4.1
heroku-local@4.1.2
heroku-ranger
heroku-run@2.7.1
heroku-status@1.2.1

**Comment by dickeyxxx** [comment]
ahhhh it's a CLI parsing issue. for some reason with this flag it isn't working with the equals separator

**Comment by dickeyxxx** [comment]
alright, I'm pushing out 4.25.1 which will have the fix for this
