### ISSUE TITLE
Raising Authentication Failure on commands with --app flag throws confusing error message

### ISSUE THREAD

**Issue by stephenhmarsh** [heroku/heroku#1760]
Hello,
I was trying to run `heroku certs` but did not realize I was not logged in.

I got the following errors:

<pre>$ heroku certs
 !    Multiple apps in folder and no app specified.
 !    Specify app with --app APP.
$ heroku certs --app my-app
Authentication failure
 ▸    Unexpected flag: --app</pre>

At first this appeared to me as if the *authentication failure* was related to/caused by `Unexpected flag`, rather than a side effect of raising `Authentication failure` and having `--app` passed along.

Eventually I realized I wasn't logged in and everything was fine.

**Comment by dickeyxxx** [comment]
This was a bug but was resolved earlier. I would ask for your version, but it's probably autoupdated by now. I'm going to assume this is resolved unless you can reproduce it.
