### ISSUE TITLE
Heroku toolbelt failure

### ISSUE THREAD

**Issue by fomojola** [heroku/heroku#1764]
The Heroku CLI recently autoupdated to Heroku recently to 3.42.15. Now anytime I run the toolbelt from the command line I get this:

C:/Program Files/Heroku/lib/heroku/updater.rb:93:in `fork': fork() function is unimplemented on this machine (
NotImplementedError)
        from C:/Program Files/Heroku/lib/heroku/updater.rb:93:in `background_update!'
        from C:/Program Files/Heroku/lib/heroku/updater.rb:78:in `inject_libpath'
        from C:/Program Files/Heroku/bin/heroku:19:in `<main>'

I actually needed it to work right now so I commented out the call to background_update on line 78 in updater.rb: that prevents the crash. Not sure how much of this is an issue with my Windows XP device: prior to the latest upgrade this just worked.

**Comment by dickeyxxx** [comment]
you have some old code, try reinstalling
