### ISSUE TITLE
heroku tool belt install failed on Windows 10

### ISSUE THREAD

**Issue by poogasuki** [heroku/heroku#1768]
I installed heroku-toolbelt.exe on Windows10 and run "heroku" command  on the console.
I got this error message.
What is the problem?
========================================================================
noriko@NORIKO-VAIO C:\Users\noriko
> heroku
Installing Heroku Toolbelt v4... done.
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
Setting up node-v4.1.2... done
Updating plugins... done
Installing core plugins heroku-cli-addons, heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run...Error reading plugin heroku-status. Reinstalling... done
 done
"\x80" on Windows-31J
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/json/common.rb:148:in `encode'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/json/common.rb:148:in `initialize'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/json/common.rb:148:in `new'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/json/common.rb:148:in `parse'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:218:in `json_decode'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:82:in `commands_info'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:77:in `commands'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:204:in `find_command'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:12:in `try_takeover'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       "\x80" on Windows-31J (Encoding::InvalidByteSequenceError)
    Command:     heroku
    Version:     heroku/toolbelt/3.42.16 (i386-mingw32) ruby/1.9.3

    More information in C:/Users/noriko/.heroku/error.log
========================================================================

**Comment by iam--nash** [comment]
@poogasuki what have you done to fix this ? it might solve the error I encountered . Thanks!

**Comment by poogasuki** [comment]
I'm sorry for din't mentioning the result and closing this post.
This should have been the Encoding problem.I fixed this by doing this.  
http://stackoverflow.com/questions/33029991/heroku-comannd-always-fails/33043592#33043592
I hope this might help you.

**Comment by iam--nash** [comment]
@poogasuki thanks! other than that, have you not done something else to make it totally work?

**Comment by poogasuki** [comment]
@iam--nash Sorry, nothing else i have done. all i did was, 
1. download "heroku-toolbelt.exe" form here  "https://toolbelt.heroku.com/".
2. run the "heroku-toolbelt.exe" and it was installed into "C:\Program Files (x86)\Heroku".
3. to confirm if it was installed collectly, i entered "heroku --version" on the command line.
4. and i get the error message as i mentioned at "http://stackoverflow.com/questions/33029991/heroku-comannd-always-fails/33043592#33043592".
5. so i fixed that problem, and "heroku" comannd worked well.

i also see the  issue #1779, i have no idea about that. i'm sorry for i can't help you.
