### ISSUE TITLE
Issue using Heroku Toolbelt - triggered automatic upgrade to v4

### ISSUE THREAD

**Issue by NullVoxPopuli** [heroku/heroku#1769]
I ran the command: `heroku pg:pull DATABASE_URL local_db_name --app app_name`

```
Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       uninitialized constant Excon::Middleware::Decompress (NameError)
    Command:     heroku pg:pull DATABASE_URL local_db_name --app app_name
    Version:     heroku-toolbelt/3.42.17 (x86_64-linux) ruby/2.2.2
    Error ID:    c71ce7579f0b407390b7a7fa344a9b8d


    More information in /home/me/.heroku/error.log
```

from the log

```
Heroku client internal error.
uninitialized constant Excon::Middleware::Decompress
/usr/local/heroku/lib/heroku/jsplugin.rb:124:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:24:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
```

**Comment by dickeyxxx** [comment]
Try reinstalling, sometimes old gems get loaded and I think an old version of excon is causing the issue here.

**Comment by NullVoxPopuli** [comment]
What I used to uninstall: `sudo apt-get purge heroku*`
To install: `wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh` from https://toolbelt.heroku.com/

Output:
```
Preparing to unpack .../heroku-toolbelt_3.42.17_all.deb ...
Unpacking heroku-toolbelt (3.42.17) ...
Setting up heroku (3.42.17) ...
Setting up heroku-toolbelt (3.42.17) ...
```

and then when I run the command again, I get the same error.

Did I miss something?


I decided to check out both repos -- this one and https://github.com/heroku/toolbelt
and noticed some differences from what the toolbelt is developed for / what I'm running.

Not sure if any of these could contribute to the error, but at the very least I found them interesting
The toolbelt is only set up for `Ruby 2.1.5` I'm using `Ruby 2.2.2` (Travis should probably be updated to test the same rubies as the heroku is set up for?)

In the toolbelt gem, Excon isn't a dependency (it is for specs though).

For this gem, excon is not a dependency at all (maybe that's why there are name errors?)
https://rubygems.org/gems/heroku

but idk. Maybe I'm missing something. Some gems have some pretty funky setups.

**Comment by dickeyxxx** [comment]
Well this wouldn't happen on debian since it doesn't keep old code around (I assumed you were on osx). You're looking at the wrong code, that repo is for the website http://toolbelt.heroku.com. The code is tested on 2.2. Excon doesn't need to be listed as a dependency because it is part of heroku-api.

I think what's happening here is the version you installed with apt-get isn't the same one you are running. Try uninstalling and running `which heroku`. You probably need to remove that other version.

**Comment by NullVoxPopuli** [comment]
oh ok.
Just keeping record here, in case someone else runs across this problem.
```
$ which heroku
/usr/local/heroku/bin/heroku
```

```
$ sudo apt-get purge heroku*
...
dpkg: warning: while removing heroku, directory '/usr/local/heroku/vendor/gems' not empty so not removed
```
I didn't notice that warning before -- that probably has something to do with it. 

```
which heroku
```
returns nothing.

So, I guess I'll remove the heroku directory in `/usr/local` -- since it has a gems folder, it's possible that folder was keeping the old version of excon around.

But real quick, lets see what's in that directory:
```
$ ls /usr/local/heroku/vendor/gems/
excon-0.25.3  heroku-api-0.3.15  launchy-2.3.0
```
boom - oldish version of excon

`sudo rm -rf /usr/local/heroku/` to be safe.

installing again via `wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh`

Checking out the heroku gem directory, cause I'm curious:
```
ls /usr/local/heroku/vendor/gems/
addressable-2.3.8  heroku-api-0.3.23  mime-types-1.25.1  netrc-0.10.3   net-ssh-gateway-1.2.0  rest-client-1.6.8
excon-0.45.4       launchy-2.4.3      multi_json-1.11.2  net-ssh-2.9.2  rdoc-4.2.0             rubyzip-1.1.7
```
hey! a newer excon. yay


Now I rerun the command, and it looks like all is well. Thanks!

**Comment by dickeyxxx** [comment]
yeah sorry about this, we **do** upgrade versions of the gems, but in weird cases (like this) I've seen it pick up old versions. Not really sure why it happens, but since we're moving commands over to the go/node codebase it's not likely to cause many problems in the future.

**Comment by NullVoxPopuli** [comment]
It's cool. It got figured out :-)
