### ISSUE TITLE
maintenance help output is ~useless

### ISSUE THREAD

**Issue by bgentry** [heroku/heroku#1772]
<img width="512" alt="screen shot 2015-10-12 at 7 51 20 pm" src="https://cloud.githubusercontent.com/assets/114033/10444400/e1403194-711a-11e5-9092-dfdfef528d39.png">

Output does not show any of the subcommands (`on` and `off`) and does not show usage info of any kind.

**Comment by dickeyxxx** [comment]
thanks for letting me know! this will fix it: https://github.com/heroku/heroku/pull/1776

**Comment by bgentry** [comment]
thanks @dickeyxxx !
