### ISSUE TITLE
Login error (Windows-1252)

### ISSUE THREAD

**Issue by ichar** [heroku/heroku#1785]
Hi!
Please advise.
When I try to login via Heroku Toolbelt from command line I get the error:

e:\Heroku>heroku login
U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
I:/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
I:/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
I:/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
I:/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
I:/Heroku/lib/heroku/jsplugin.rb:213:in `check_if_old'
I:/Heroku/lib/heroku/jsplugin.rb:123:in `setup'
I:/Heroku/lib/heroku/cli.rb:24:in `start'
I:/Heroku/bin/heroku:29:in `<main>'
U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
I:/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
I:/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
I:/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
I:/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
I:/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
I:/Heroku/lib/heroku/cli.rb:24:in `start'
I:/Heroku/bin/heroku:29:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252 (Encoding::UndefinedConversionError)
    Command:     heroku login
    Version:     heroku/toolbelt/3.42.20 (i386-mingw32) ruby/1.9.3

    More information in C:/Users/Администратор/.heroku/error.log

-------- error.log:

Heroku client internal error.
U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
I:/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
I:/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
I:/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
I:/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
I:/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
I:/Heroku/lib/heroku/cli.rb:24:in `start'
I:/Heroku/bin/heroku:29:in `<main>'
Heroku client internal error.
U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
I:/Heroku/lib/heroku/jsplugin.rb:112:in `encode'
I:/Heroku/lib/heroku/jsplugin.rb:112:in `app_dir'
I:/Heroku/lib/heroku/jsplugin.rb:119:in `bin'
I:/Heroku/lib/heroku/jsplugin.rb:147:in `setup?'
I:/Heroku/lib/heroku/jsplugin.rb:124:in `setup'
I:/Heroku/lib/heroku/cli.rb:24:in `start'
I:/Heroku/bin/heroku:29:in `<main>'

OC: Windows Vista
Locale: Russia, coding Windows-1251

**Comment by dickeyxxx** [comment]
Reinstall, you're on an old version.

**Comment by ichar** [comment]
I've tried to check with non-cyrillic username (local account) - works. My native name russian.

**Comment by ransombriggs** [comment]
@ichar I just pushed an update to https://toolbelt.heroku.com/ that should fix your problem with a windows username in cyrillics

**Comment by ichar** [comment]
Thank you. I will try.

----- Original Message -----
