### ISSUE TITLE
Heroku client internal error.

### ISSUE THREAD

**Issue by Matroskin94** [heroku/heroku#1787]
I'm just beginner, please, can someone explain this problem? I'm trying to connect to heroku with my ruby project. Already signed into heroku.
Followed the tutorial in this book http://railstutorial.ru/chapters/4_0/beginning#sec-heroku_setup
I Changed the gemfile in project:

`gem 'rails', '4.1.8'`
`group :development do `
	`gem 'sqlite3'`
`end`

`gem 'sass-rails', '~> 4.0.3'`
`gem 'uglifier', '>= 1.3.0'`
`gem 'coffee-rails', '~> 4.0.0'`
`gem 'jquery-rails'`
`gem 'turbolinks'`
`gem 'jbuilder', '~> 2.0'`
`gem 'sdoc', '~> 0.4.0',          group: :doc`

`group :production do` 
`	gem 'pg'`
`	gem 'rails_12factor'`
`end`

`gem 'tzinfo-data', platforms: [:mingw, :mswin]`

Then according  to the book trying enter command 
$heroku login
But see this report

Heroku client internal error.
U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252
d:/Soft/WEB/Programs/Heroku/lib/heroku/jsplugin.rb:112:in \`encode'
d:/Soft/WEB/Programs/Heroku/lib/heroku/jsplugin.rb:112:in \`app_dir'
d:/Soft/WEB/Programs/Heroku/lib/heroku/jsplugin.rb:119:in \`bin'
d:/Soft/WEB/Programs/Heroku/lib/heroku/jsplugin.rb:147:in \`setup?'
d:/Soft/WEB/Programs/Heroku/lib/heroku/jsplugin.rb:124:in \`setup'
d:/Soft/WEB/Programs/Heroku/lib/heroku/cli.rb:24:in \`start'
d:/Soft/WEB/Programs/Heroku/bin/heroku:29:in \`\<main\>'

Error: U+0410 to WINDOWS-1252 in conversion from UTF-8 to WINDOWS-1252 (Encoding::UndefinedConversionError)
Command: heroku login
Version:    heroku/toolbelt/3.42.20 (i386-mingw32)  ruby/1.9.3

I'm using OS Windows.

**Comment by Matroskin94** [comment]
The reason was in Cyrillics symbols in path to folder in path to .heroku, I had windows username in cyrillics, so I create new temporary windows user as administrator, then change name of my real windows username to latin and now seccessfuly using heroku.

**Comment by ransombriggs** [comment]
@Matroskin94 I just pushed an update to https://toolbelt.heroku.com/ that should fix your problem with a windows username in cyrillics
