### ISSUE TITLE
'No app specified' given even after using `heroku git:remote`

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku#1791]
1) Create a new app using https://dashboard.heroku.com/new
2) Link the new app to the project's GitHub account via the "deploy" section of the web UI
3) Use the manual "deploy branch X" button on the GitHub tab of the deploy section
4) On the command line, from the root of the GitHub repo clone, run:
`heroku git:remote --app my-app-name`
5) Without changing directory, run `heroku ps`

Expected:
* At step [4] the output is:
`set git remote heroku to https://git.heroku.com/my-app-name.git`
* At step [5], `heroku ps` works as expected.

Actual:
* At step [4] the output is:
`set git remote heroku to https://git.heroku.com/my-app-name.git`
* At step [5], `heroku ps` gives:
```
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
```
I'm presuming this is because the CLI assumes that there would be a branch on the `heroku` Git remote - whereas since I used the web UI to deploy, there isn't? `git remote -v` still shows me the app repo URL, so guessing the CLI needs to just use that directly rather than checking for the `master` branch there?

Using:
heroku/toolbelt/3.42.20 (i386-mingw32) ruby/1.9.3
heroku-cli/4.26.1-bf7a4d8 (386-windows) go1.5.1
=== Installed Plugins
heroku-apps@0.3.2
heroku-cli-addons@0.0.2
heroku-fork@4.0.0
heroku-git@2.4.3
heroku-local@4.1.5
heroku-repo
heroku-run@2.9.1
heroku-status@1.2.2

**Comment by edmorley** [comment]
An alternative (for people who don't intend on using the Heroku git remote at all, since they are using auto-deploy from GitHub etc) would be to have an in-repo file that points at the Heroku instance (that I can check into the repo for all of my team) so I don't have to use `heroku git:remote` at all.

**Comment by dickeyxxx** [comment]
I'm not sure I follow completely, what is the output of `git remote -vv` after you ran `heroku git:remote`

**Comment by edmorley** [comment]
It's:
```bash
[~/src/bugherder]$ git remote -vv
heroku  ssh://git@heroku.com/mozilla-bugherder.git (fetch)
heroku  ssh://git@heroku.com/mozilla-bugherder.git (push)
origin  git@github.com:edmorley/bugherder.git (fetch)
origin  git@github.com:edmorley/bugherder.git (push)
upstream        git@github.com:mozilla/bugherder.git (fetch)
upstream        git@github.com:mozilla/bugherder.git (push)
[~/src/bugherder]$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/upstream/master
```

**Comment by dickeyxxx** [comment]
I can't reproduce. If you run `heroku git:remote -a appname` it doesn't change your git remote?

**Comment by edmorley** [comment]
No, it does change the remote.
The issue is that *even with* the added remote, the Heroku CLI doesn't see there being an associated app - presumably because that app was created via the web UI (see above) and not via a git push. As such, the git repo remotely is presumably empty.

**Comment by edmorley** [comment]
ie for another project (where it was created in the "traditional" manner ie with a `git push`) I get:
```bash
[~/src/treeherder]$ git branch -a | grep heroku
  remotes/heroku/master
```

However in the output for this project (two comments up), there is no such master branch on the heroku remote.

**Comment by edmorley** [comment]
Did you definitely create a new app from scratch using https://dashboard.heroku.com/new and not the CLI?

**Comment by dickeyxxx** [comment]
I don't follow. If you run `heroku git:remote --app appname` you should be able to run `heroku ps` so long as it executes. Is this not happening? How the app is created doesn't matter.

**Comment by edmorley** [comment]
> If you run heroku git:remote --app appname you should be able to run heroku ps so long as it executes

I have run that command multiple times and `heroku ps` does not work. I'm not sure how to make the original STR any clearer, they are pretty thorough as it is. The lack of a master branch was just a hunch, perhaps it's unrelated.

If there's some logging I can turn on to help provide additional info, seeing as it's not reproducible for you, just let me know.

Thanks :-)

**Comment by edmorley** [comment]
Ah so one difference I can see between the project for which `heroku ps` works without `--app`, and the one that doesn't is the protocol set for the git remote.

Doesn't work:
```bash
[~/src/bugherder]$ git remote -vv
heroku  ssh://git@heroku.com/mozilla-bugherder.git (fetch)
heroku  ssh://git@heroku.com/mozilla-bugherder.git (push)
origin  git@github.com:edmorley/bugherder.git (fetch)
origin  git@github.com:edmorley/bugherder.git (push)
upstream        git@github.com:mozilla/bugherder.git (fetch)
upstream        git@github.com:mozilla/bugherder.git (push)
[~/src/bugherder]$ heroku ps
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
```

Works:
```bash
[~/src/treeherder]$ git remote -vv
heroku  git@heroku.com:treeherder-heroku.git (fetch)
heroku  git@heroku.com:treeherder-heroku.git (push)
origin  git@github.com:mozilla/treeherder.git (fetch)
origin  git@github.com:mozilla/treeherder.git (push)
[~/src/treeherder]$ heroku ps
=== web (Standard-1X): `newrelic-admin run-program gunicorn treeherder.config.wsgi:application --log-file - --timeout 29 --max-requests 2000`
...
```

A `git config -e` in the directory of the project that doesn't work, shows:
```
[remote "heroku"]
	url = https://git.heroku.com/mozilla-bugherder.git
	fetch = +refs/heads/*:refs/remotes/heroku/*
```

...so I'm slightly surprised why the `git remote -vv` output shows `ssh://`.

**Comment by dickeyxxx** [comment]
yeah I'm not sure where the `ssh://` is coming from, nothing in the CLI would produce that as far as I know. Running `heroku git:remote` should reset the heroku branch to whatever it should be.

**Comment by dickeyxxx** [comment]
are you reliably able to reproduce the `ssh://` url?

**Comment by edmorley** [comment]
Ah!

I'd forgotten since, but I'd followed the Heroku guide here:
https://devcenter.heroku.com/articles/git#ssh-git-transport

and done a:
```bash
 git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
```

Can you reproduce using that? :-)

**Comment by dickeyxxx** [comment]
That makes more sense. I've added https://github.com/heroku/heroku-cli/pull/146 which will fix this.

**Comment by edmorley** [comment]
Ah thank you :-)

**Comment by tksalesforce** [comment]
I'm still having this problem. I had set up Heroku to use SSH exclusively, identically to @edmorley. Fixed it by removing the setting, but I can't imagine I'm the only one who would get stuck like this. Happy to provide any details you need in order to correct this issue.

**Comment by jkdf2** [comment]
I'm having this problem. I had set up Heroku to use SSH exclusively, identically to @edmorley. Fixed it by removing the setting, but I can't imagine I'm the only one who would get stuck like this. Happy to provide any details you need in order to correct this issue permanently.

**Comment by dickeyxxx** [comment]
did you have this set? `git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/`

Because that should be fixed now.

**Comment by jkdf2** [comment]
That's very strange - after resetting with `git config --global --remove-section url.ssh://git@heroku.com/`, I cannot reproduce the problem again.

Sorry for the trouble.
