### ISSUE TITLE
Heroku login does not pass exit code back

### ISSUE THREAD

**Issue by TDaglis** [heroku/heroku#1793]
Heroku login exit code is 0 on authentication failure
```
% heroku login
Enter your Heroku credentials.
Email: test
Password (typing will be hidden):
 ▸    Authentication failure.
% echo $?
0  
```
Is there a way to have the authentication failure reflected on the exit code?
The `--exit-code` option mentioned in #186 only works for `heroku run`

**Comment by dickeyxxx** [comment]
fixed here, https://github.com/heroku/heroku-cli/pull/102 will go out with the next release

**Comment by TDaglis** [comment]
thanks :+1:
