### ISSUE TITLE
Failed to update heroku cli on Mac

### ISSUE THREAD

**Issue by namxam** [heroku/heroku#1794]
Running ```heroku update``` fails with

    Error:       uninitialized constant Zip::IOExtras (NameError)
    Command:     heroku update
    Version:     heroku-toolbelt/3.42.12 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    3cbc0a6d53ed4da1ae6809207ac8bff7

Mac OS El Capitan 10.11 (15A284)

**Comment by dickeyxxx** [comment]
Try reinstalling

**Comment by namxam** [comment]
Thnx. Haven't thought of that :cry:
