### ISSUE TITLE
Can not logging into heroku toolbelt on Ubuntu

### ISSUE THREAD

**Issue by khailevn** [heroku/heroku#1811]
Error:       connect timeout reached (Excon::Errors::Timeout)
    Command:     heroku login
    Version:     heroku-toolbelt/3.42.21 (x86_64-linux) ruby/2.2.3
    Error ID:    1293c11ae0e84f5798070e256b2d2430

**Comment by ransombriggs** [comment]
Could you please try this again?  It sounds like it could have been a temporary network error.
