### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by mcpDESIGNS** [heroku/heroku#1812]
Getting an error when trying to Push an `anguar-fullstack` app to Heroku.

It's error'ing out in a node app.js file:

    import express from 'express';
    ^^^^

Has anyone run into this? Tried everything I can think of...

**Comment by dickeyxxx** [comment]
This project is for the Heroku CLI only. Submit a support ticket for general support

**Comment by mcpDESIGNS** [comment]
Apologies. I was trying it through CLI only reason I thought it was ok here.
Thanks, I'll make it there
