### ISSUE TITLE
Arrow keys are now broken in python console when run via heroku CLI toolbelt (heroku run python)

### ISSUE THREAD

**Issue by nebstrebor** [heroku/heroku#1814]
These have always worked before until recent release broke them.

When I hit an arrow key I get character output like : "^[[D"

As you can imagine, this kills the ability to move around the console or to recall the last command, making it almost worthless and very frustrating. 

```
>: heroku run python
Running python on myapp... up, run.4688
Python 2.7.6 (default, Jul 15 2014, 15:38:10) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> ^[[B^[[A^[[D heroku ^[[B^[[A^[[D
```

>: OS X 10.1
>: heroku version
heroku-toolbelt/3.42.21 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.27.2-eb1b3ca (amd64-darwin) go1.5.1
=== Installed Plugins
heroku-apps@0.5.4
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.3
heroku-local@4.1.5
heroku-run@2.9.1
heroku-status@1.2.2
heroku-wildcards

**Comment by dickeyxxx** [comment]
Another user had this issue but it turned out to be a python package in their setup. Does the sample python app work for you? https://devcenter.heroku.com/articles/getting-started-with-python#introduction

**Comment by nebstrebor** [comment]
Sure enough... only one of our apps is affected. We'll try and track it down. Any links to the related problem may be helpful in identifying the problem package... odd that it would have that effect

**Comment by dickeyxxx** [comment]
Unfortunately I don't have any information on the other user.
