### ISSUE TITLE
ERROR: runtime error: invalid memory address or nil pointer dereference when using the client

### ISSUE THREAD

**Issue by jimmckerchar** [heroku/heroku#1830]
I'm getting the error "ERROR: runtime error: invalid memory address or nil pointer dereference ! error getting commands pid **** exit 1" when using any of the client's functionality (i can't even check the version or or access help)

Edit
-----
Apologies: I'm on Ubuntu 14.04, 64bit, using ruby 1.9.3

**Comment by ransombriggs** [comment]
What platform are you on?

**Comment by jimmckerchar** [comment]
sorry, i've edited my original comment to include platform info

**Comment by ransombriggs** [comment]
Could you please add the contents of ~/.heroku/error.log as well?  I am installing ubuntu now to try and reproduce the error myself.

**Comment by ransombriggs** [comment]
Someone else had this issue as well and ~/.heroku/error.log was not very helpful.  Instead, could you please include the output of `heroku version` and attach the contents of ~/.heroku/plugin-cache.json ?

**Comment by mcramm** [comment]
I'm seeing this too, on CentOS 6.3 with ruby 2.0.0p247.

**Comment by jimmckerchar** [comment]
If i type 'heroku version' in the console, i get the "invalid memory address..." error. I'm just on my other machine at the moment so will post the contents of my err.log file in a separate comment

**Comment by ransombriggs** [comment]
@jimmckerchar I was able to recreate this bug with the file from a separate issue, so do not worry about sending me the file anymore.  I should have what I need to fix this.

**Comment by jimmckerchar** [comment]
here are the contents of error.log from the last (i think) before the issue starts occurring

2015/11/20 10:57:18 running from /home/jim/.heroku/heroku-cli
2015/11/20 10:58:12 done
2015/11/20 10:58:12 rebuilding plugins cache... 
2015/11/20 10:58:15 Error reading plugin: heroku-status. See /home/jim/.heroku/error.log for more information.
2015/11/20 10:58:15 exit status 1 
 module.js:339
    throw err;
    ^

Error: Cannot find module 'heroku-cli-util'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jim/.heroku/node_modules/heroku-status/commands/status.js:3:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

2015/11/20 10:58:19 done
2015/11/20 11:29:38 running from /home/jim/.heroku/heroku-cli
2015/11/20 11:29:38 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 11:29:53 running from /home/jim/.heroku/heroku-cli
2015/11/20 11:29:53 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 11:31:11 running from /home/jim/.heroku/heroku-cli
2015/11/20 11:31:11 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 11:48:46 running from /home/jim/.heroku/heroku-cli
2015/11/20 11:48:46 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 11:48:47 running from /home/jim/.heroku/heroku-cli
2015/11/20 11:48:47 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:02:37 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:02:37 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:02:38 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:02:38 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:03:08 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:03:08 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:03:09 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:03:09 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:03:23 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:03:23 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:12:14 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:12:14 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:13:58 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:13:58 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:14:55 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:14:55 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:20:36 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:20:36 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:24:22 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:24:22 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:33:41 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:33:41 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 12:34:19 running from /home/jim/.heroku/heroku-cli
2015/11/20 12:34:19 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 14:54:23 running from /home/jim/.heroku/heroku-cli
2015/11/20 14:54:23 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 14:55:53 running from /home/jim/.heroku/heroku-cli
2015/11/20 14:55:53 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 14:56:28 running from /home/jim/.heroku/heroku-cli
2015/11/20 14:56:28 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 15:24:59 running from /home/jim/.heroku/heroku-cli
2015/11/20 15:24:59 ERROR: runtime error: invalid memory address or nil pointer dereference
2015/11/20 16:40:51 running from /home/jim/.heroku/heroku-cli
2015/11/20 16:40:51 ERROR: runtime error: invalid memory address or nil pointer dereference

**Comment by jimmckerchar** [comment]
ah... just spotted ;)

**Comment by dickeyxxx** [comment]
Can you delete `~/.heroku/plugin-cache.json` and try again?

**Comment by dickeyxxx** [comment]
If that doesn't work, delete `~/.heroku/heroku-cli`

**Comment by jimmckerchar** [comment]
thanks @dickeyxxx 

Method 1 didn't work but  removing heroku-cli has got me a working client again ;)

**Comment by jimmckerchar** [comment]
@ransombriggs does the solution provided by @dickeyxxx relate to the issue that you were able to reproduce? The issue i opened the case for is now resolved so i'll leave closing this down to you guys ;)

**Comment by ransombriggs** [comment]
@jimmckerchar - yeah, we debugged this together, and his fix removed the problem for me as well.  One thing I should mention is that if you manually installed any plugins, you will have to reinstall them after heroku updates.  I will go ahead and close this issue.  @mcramm if this does not fix the problem for you, feel free to reopen.

**Comment by jimmckerchar** [comment]
Thanks guys ;)

**Comment by mcramm** [comment]
Thanks! Removing `~/.heroku/plugin-cache.json` worked.

**Comment by dickeyxxx** [comment]
Sorry for the trouble here everyone. We pushed a big performance patch yesterday but some of you seemed to have invalid cache files for some reason. We put a patch in to ignore the invalid parts of your command cache.
