### ISSUE TITLE
How can I make the v3 work?

### ISSUE THREAD

**Issue by lufeihaidao** [heroku/heroku#1834]
```
> heroku -v
heroku-cli: Installing Toolbelt v4...
> heroku logs
heroku-cli: Installing Toolbelt v4...
> heroku login
heroku-cli: Installing Toolbelt v4...
```

**Comment by lufeihaidao** [comment]
```
heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       end of file reached (EOFError) (Excon::Errors::SocketError)
    Command:     heroku -v
    Version:     heroku-toolbelt/3.42.22 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    9ce00299b82b47ab9ecdc57ae8279ddb
```

I don't wanna install v4 now

**Comment by dickeyxxx** [comment]
is `XDG_DATA_HOME` set by chance?

**Comment by lufeihaidao** [comment]
How can I get this var?

**Comment by dickeyxxx** [comment]
It's an environment variable, you can see them with `set`. Also does it not show any output after `heroku-cli: Installing Toolbelt v4...` and just stop? Or are you canceling it? Can you see the exit status with `$?`?

**Comment by dickeyxxx** [comment]
This seems to only be an issue on OSX Mountain Lion. Maybe it's because you have an old openssl bindings. You could try using the homebrew version `brew install heroku`.

**Comment by lufeihaidao** [comment]
Finally `brew install heroku` works. Thanks, jeff!
