### ISSUE TITLE
[windows] Buildpacks:set introduces as \ when using a branch

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku#1845]
```console
c:\> heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git#branch
```
The output includes a `\#` instead of a `#`, including if you inspect the buildpacks on linux as well.

Pushes will then fail.

I had to go to a linux machine to set the buildpack with a branch, even quoting (single or double) didn't fix the escaping.

**Comment by dickeyxxx** [comment]
what shell + version of windows? I wasn't able to reproduce.

**Comment by freeformz** [comment]
Windows 8. Both in powershell and command prompt.

**Comment by ransombriggs** [comment]
I shipped an emergency fix this morning for a bug I released yesterday, could you please run `heroku update` and try again?

**Comment by freeformz** [comment]
Thanks. Works!

**Comment by dickeyxxx** [comment]
ah I must've been a version behind
