### ISSUE TITLE
Failed to heroku create in OS X 10.11.2

### ISSUE THREAD

**Issue by wheredidjupark** [heroku/heroku#1853]
Error:       undefined method `netrc_filename' for Netrc:Class (NoMethodError)
    Command:     heroku create
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    b48decfe2c3d43b9ad466457273380ca

**Comment by webbtj** [comment]
+1
Running `heroku logs` caused the same issue. Recently re-installed the Toolbelt (latest version). Call stack looks like this:
```
2015/12/15 15:21:21 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/tjwebb/.heroku/heroku-cli
Heroku client internal error.
undefined method `netrc_filename' for Netrc:Class
/usr/local/heroku/lib/heroku/auth.rb:138:in `netrc_path'
/usr/local/heroku/lib/heroku/auth.rb:160:in `rescue in netrc'
/usr/local/heroku/lib/heroku/auth.rb:151:in `netrc'
/usr/local/heroku/lib/heroku/auth.rb:178:in `read_credentials'
/usr/local/heroku/lib/heroku/auth.rb:113:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:85:in `user'
/usr/local/heroku/lib/heroku/auth.rb:39:in `client'
/usr/local/heroku/lib/heroku/command/base.rb:80:in `heroku'
/usr/local/heroku/lib/heroku/command/logs.rb:33:in `index'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'
```
Just digging through and clearly there is an issue with getting the `netrc_filename` property of the `Netrc` class. Netrc is new to me so I'm still doing some digging, any help would be greatly appreciated.

**Comment by ransombriggs** [comment]
@webbtj I have been trying to recreate this issue on my own machine without much luck.  Could you check for `def self.netrc_filename` inside `/usr/local/heroku/vendor/gems/netrc-0.10.3/lib/netrc.rb`?  If this is defined in the netrc library that is packaged as part of the toolbelt, then it would point to another issue, possibly load path related.

**Comment by webbtj** [comment]
@ransombriggs et al, I just found *my* issue. For some reason though I updated the Heroku Toolbelt, I still had an old copy of Netrc AND the new copy. So I had both 0.7.7 and 0.10.3. Once I removed (renamed) 0.7.7 my issues were resolved.

**Comment by ransombriggs** [comment]
@wheredidjupark Could you please attach the directory listing of `/usr/local/heroku/vendor/gems`?

**Comment by ransombriggs** [comment]
@webbtj thanks for your help debugging this, it has been helpful in revealing a bug in our installer.

**Comment by wheredidjupark** [comment]
The issue matches webbtj's. Thanks for resolving the issue!

**Comment by jareilly** [comment]
Thanks webbtj, I had the same issue !

**Comment by vinkris** [comment]
Awesome, thanks for helping @webbtj.
