### ISSUE TITLE
heroku certs:update failing because of an internal server error

### ISSUE THREAD

**Issue by petervdw** [heroku/heroku#1864]
Updated an SSL certificate on several Heroku apps a few days ago and everything ran fine however tonight I'm getting the following error:

    $ heroku certs:update server.crt server.key 
    Resolving trust chain... failed
     !    Heroku client internal error.
     !    Search for help at: https://help.heroku.com
     !    Or report a bug at: https://github.com/heroku/heroku/issues/new
    
    Error:       Expected(200) <=> Actual(500 InternalServerError)
     (Excon::Errors::InternalServerError)
        Command:     heroku certs:update server.crt server.key
        Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
        Error ID:    ea08cbb4a8924c32905d524b83c2d120

Any suggestions?

**Comment by ransombriggs** [comment]
@petervdw sorry for the late response, but I now have access to the logs for the certificate verification service, could you please try again and note the time at which you attempted so that I can narrow down the error and help you debug your problem?

**Comment by petervdw** [comment]
@ransombriggs Thanks for reaching out. I've opened a support ticket and already resolved the issue. Apologies for not closing this sooner!
