### ISSUE TITLE
Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by manuks** [heroku/heroku#1875]
Heroku client internal error.
Connection reset by peer - SSL_connect (Errno::ECONNRESET)
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:229:in `get'
/usr/local/heroku/lib/heroku/jsplugin.rb:209:in `manifest'
/usr/local/heroku/lib/heroku/jsplugin.rb:222:in `url'
/usr/local/heroku/lib/heroku/jsplugin.rb:139:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:24:in `start'
/usr/bin/heroku:25:in `<main>'

**Comment by dickeyxxx** [comment]
not much we can do about this, it means your machine can't connect to our servers

**Comment by manuks** [comment]
It was able to connect form one user in the same machine but not for others. Copied the .heroku folder of that user to other's home folder and it started to work.
