### ISSUE TITLE
Heroku should error out earlier on unsupported architectures

### ISSUE THREAD

**Issue by mistydemeo** [heroku/heroku#1878]
I recently fielded an [issue](https://github.com/mistydemeo/tigerbrew/issues/403) where a user was attempting to run the heroku client on a PPC Mac (really!). This manifested itself in a confusing error message and backtrace:

```
Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:211:in `url'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/lib/heroku/cli.rb:24:in `start'
/usr/local/Cellar/heroku-toolbelt/3.42.22/libexec/bin/heroku:24:in `<main>'
```

Which is happening here, after it reads the manifest from https://cli-assets.heroku.com/master/manifest.json:

```ruby
  def self.url
    manifest['builds'][os][arch]['url'] + ".gz"
  end
```

It'd be great if this could check more explicitly for a supported architecture and error out earlier with a more explicit error message. I see that only amd64 builds are provided on OS X, so erroring out on i386 and PPC would be helpful.

**Comment by dickeyxxx** [comment]
thanks for debugging that! I got a PR for it up

**Comment by mistydemeo** [comment]
That was fast! Thanks!

Is there a pure-Ruby version of the client that still works with Heroku's servers? It'd be helpful to be able to recommend something to users who aren't on amd64 machines.

**Comment by dickeyxxx** [comment]
There might be a version, I'm not sure which one. But it wouldn't be supported and will eventually stop working due to API changes.
