### ISSUE TITLE
Can't install heroku in opensuse 13.2

### ISSUE THREAD

**Issue by jrmiranda** [heroku/heroku#1886]
After I run `wget -O- https://toolbelt.heroku.com/install.sh | sh` everytime I use the command `heroku` it shows this:

```
heroku-cli: Adding dependencies...
 ▸    Get https://cli-assets.heroku.com/node/v5.4.1/node-v5.4.1-linux-x64.tar.gz: dial tcp: lookup cli-assets.heroku.com on 192.168.2.1:53: no such host
 done
heroku-cli: Installing core plugins...
 ▸    

 ▸    fork/exec bin/node: no such file or directory
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
heroku-cli: Adding dependencies...
 ▸    Get https://cli-assets.heroku.com/node/v5.4.1/node-v5.4.1-linux-x64.tar.gz: dial tcp: lookup cli-assets.heroku.com on 192.168.2.1:53: no such host
 done
heroku-cli: Installing core plugins...
 ▸    

 ▸    fork/exec bin/node: no such file or directory
heroku-cli: Installing core plugins (retrying)...
 ▸    Error installing package. 
 ▸    
 ▸    Try running again with GODE_DEBUG=info to see more output.
 !    error getting commands pid 20638 exit 1
```

What should I do? Thanks.

**Comment by ransombriggs** [comment]
@jrmiranda Are you behind a proxy server?  The toolbelt is trying to download additional software from https://cli-assets.heroku.com/node/v5.4.1/node-v5.4.1-linux-x64.tar.gz and failing.  Could you test and make sure you can download that manually?

**Comment by jrmiranda** [comment]
@ransombriggs Still the same error.. I even installed the node last version

**Comment by ransombriggs** [comment]
@jrmiranda Sorry for the delayed response, I installed opensuse 13.2 on my machine the toolbelt worked for me.  I just wanted to make sure it was not an opensuse issue first and foremost.  This error usually points to dns problems, but there might be something I can change code wise to make this more reliable, as I have seen other users have this error recently.

**Comment by ransombriggs** [comment]
@jrmiranda this behavior may be due to a bug in glibc < 2.20 and since the latest for SUSE is 2.19, this makes sense that you are seeing this error.  There is a workaround that I am currently investigating, will let you know once I know more.

**Comment by ransombriggs** [comment]
@jrmiranda I pushed up some changes that might fix your problem, please run `heroku update` and try again.  If it does not fix your problems, feel free to reopen the issue.

**Comment by ransombriggs** [comment]
@jrmiranda We removed the netgo build flag to fix a bug for DNS problems users have been experiencing in #1899 .  Since this issue was last addressed, we have updated the Go runtime, which may or not fix this bug.  If you encounter this error again, please let us know immediately and I will see if there is another way we can fix this issue.
