### ISSUE TITLE
Cannot use heroku toolbelt - hangs on "Installing Core Plugins"

### ISSUE THREAD

**Issue by jamescgibson** [heroku/heroku#1900]
Every time I run any `heroku` command I get e.g.:

```
james@bb-8:~/dev/quottly-ng$ heroku --version
heroku-cli: Installing core plugins...
```

This will hang for north of 20 minutes with no network activity.

I'm on 14.04. I've tried every combination of:

ruby 2.3.0 with rvm
ruby 2.2.3 with rvm
node 4.1.1 with nvm
node 5.6 with nvm
heroku installed using the apt package
heroku installed standalone

And no dice. I'm fairly confident in my ability to debug this, but am not even sure where to start - the fact that I can't get _any_ output all is frustrating. 

This only started yesterday, fwiw, and I have heroku toolbelt working away happily on another machine with 15.10.

### Extra Info

The last few lines of ~/.heroku/errors.log:
```
1263 2016/02/12 11:13:52 Updating Heroku v4 CLI to 4.27.20-ddecfd7 (master)... 
1264 2016/02/12 11:13:54 done
1265 2016/02/12 11:13:54 reexecing new CLI...
1266 2016/02/12 11:13:55 Updating plugins... 
1267 2016/02/12 11:13:56 no plugins to update.
1268 2016/02/17 10:51:59 Updating Heroku v4 CLI to 4.27.21-839acbb (master)... 
1269 2016/02/17 10:52:10 done
1270 2016/02/17 10:52:10 reexecing new CLI...
1271 2016/02/17 10:52:10 Updating plugins... 
1272 2016/02/17 10:52:17 done. Updated 1 package.
1273 2016/02/17 10:52:17 heroku-cli: Installing core plugins...
1274 2016/02/17 10:56:58 Timed out while updating
1275 2016/02/17 21:27:52 heroku-cli: Installing core plugins...
1276 2016/02/17 21:29:02 heroku-cli: Installing core plugins...
1277 2016/02/17 21:30:26 heroku-cli: Installing core plugins...
1278 2016/02/17 23:56:58 heroku-cli: Installing core plugins...
1279 2016/02/17 23:59:38 heroku-cli: Installing core plugins...
1280 2016/02/18 00:04:19 heroku-cli: Installing core plugins...
1281 2016/02/18 00:07:17 heroku-cli: Installing core plugins...
1282 2016/02/18 00:07:50 heroku-cli: Installing core plugins...
1283 2016/02/18 00:11:12 heroku-cli: Installing core plugins...
1284 2016/02/18 00:13:03 heroku-cli: Installing core plugins...
1285 2016/02/18 00:13:33 heroku-cli: Installing core plugins...
```

### Update:

As is traditional, immediately after making this issue, I found `~/.heroku/` and decided to delete it and try installing again - no dice, same hang on "Installing core plugins..."

There are, after deleting and running `heroku` again, the following files in `~/.heroku`:

```
autoupdate  heroku-cli             tmp                              updating.lock.heroku-fork   updating.lock.heroku-pipelines  updating.lock.heroku-status
cacert.pem  node_modules           updating.lock.heroku-apps        updating.lock.heroku-git    updating.lock.heroku-run
error.log   node-v5.4.1-linux-x64  updating.lock.heroku-cli-addons  updating.lock.heroku-local  updating.lock.heroku-spaces
```

**Comment by dickeyxxx** [comment]
try running it with `GODE_DEBUG=1`

**Comment by jamescgibson** [comment]
@dickeyxxx Thanks! Unfortunately, no dice;

```
james@bb-8:~/dev/quottly-demo$ GODE_DEBUG=1 heroku                                                                                                                                       
heroku-cli: Installing Toolbelt v4...

```

And it just hangs.

**Comment by ransombriggs** [comment]
@jamescgibson Could you set `GODE_DEBUG=info` and try again?  This will not fix your problem, but should give us the logging information needed to fix it.

**Comment by dickeyxxx** [comment]
@ransombriggs I already asked him to do that

It looks like it got stuck at an another step though. It seems like your internet connection might be unreliable. You could try running it with HEROKU_DEBUG=1 but I'm not sure that would show more information.

**Comment by jamescgibson** [comment]
`GODE_DEBUG=info` eventually worked, showed it hanging randomly after downloading different pacages. After five or six times, success. Not sure what to make of it, maybe I have an odd configuration that's causing problems - frustrating that something as common as a slightly unreliable residential internet connection can throw npm for a loop, heh. 

Really appreciate the help @ransombriggs and @dickeyxxx !

**Comment by dickeyxxx** [comment]
there are (unfortunately) lots of things it has to download. We're working to reduce that though.
