### ISSUE TITLE
pg:backups restore fails with a 0 exit code

### ISSUE THREAD

**Issue by jooshbzm** [heroku/heroku#1901]
A few times over the past month, one of our scheduled `pg:backups restore` jobs has failed silently and left the database in a bad state. From what I can tell, this command exits with a 0 exit code even when the restore fails.

Here's my output:

```
Running... 1.32GB
Running... 1.32GB
An error occurred and your backup did not finish.

Please run `heroku pg:backups info r303` for details.
```

**Comment by ransombriggs** [comment]
@jooshbzm sorry this fell through the cracks, but a release has just been sent out so `heroku update` and verify that you have `heroku-toolbelt/3.43.1` and this should no longer occur

**Comment by jooshbzm** [comment]
No problem @ransombriggs, I'll check this and confirm as soon as I get a chance. Thanks for fixing!
