### ISSUE TITLE
Faye not working on heroku

### ISSUE THREAD

**Issue by yanhackcode15** [heroku/heroku#1907]
Faye isn't working properly on heroku. I had faye working locally and was able to publish and sub to message. 

I can see faye server booting up from heroku logs but after a publish from the rails server client, I'm not getting the callback which puts a message. 

I'm not sure what's missing. The configuration locally should have worked. 

my app is at: http://jedi-parking.herokuapp.com/

**Comment by dickeyxxx** [comment]
Can you submit a support ticket? This project is for the Heroku CLI.
