### ISSUE TITLE
Heroku : No application found to handle 'web_url'

### ISSUE THREAD

**Issue by singhakash** [heroku/heroku#1910]
I am trying to deploy my node.js application to heroku .I am following [this][1] tutorial.

But when I did `heroku open` below error is shown:

    $ heroku open
    Opening commentsystems... failed
     !    Heroku client internal error.
     !    Search for help at: https://help.heroku.com
     !    Or report a bug at: https://github.com/heroku/heroku/issues/new
    
        Error:       No application found to handle 'web_url' (Launchy::ApplicationNotFoundError)
        Command:     heroku open
        Version:     heroku/toolbelt/3.42.37 (i386-mingw32) ruby/2.1.7
        Error ID:    a55dc665a86a49558f08b0af24a4a9d9
    
    
        More information in C:/Users/ABC/.heroku/error.log

**error.log**

    Heroku client internal error.
    No application found to handle 'web_url'
    C:/Program Files (x86)/Heroku/vendor/gems/launchy-2.4.3/lib/launchy/application.rb:24:in `handling'
    C:/Program Files (x86)/Heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:43:in `app_for_uri'
    C:/Program Files (x86)/Heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:28:in `open'
    C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:389:in `block in launchy'
    C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:280:in `action'
    C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:387:in `launchy'
    C:/Program Files (x86)/Heroku/lib/heroku/command/apps.rb:233:in `open'
    C:/Program Files (x86)/Heroku/lib/heroku/command.rb:212:in `run'
    C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:33:in `start'
    C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

Then I [tried][2]

    heroku config:set HEROKU_URL=$(heroku info -s | grep web-url | cut -d= -f2)

After that when I ran `heroku open` same error message was shown.

Is there anything I am doing wrong ?
 
Any help would be appreciated.
Thanks

  [1]: http://blog.koenromers.com/deploying-your-node-js-mongodb-application-for-free/
  [2]: http://stackoverflow.com/questions/12570579/how-to-get-heroku-app-name-url-from-inside-the-app

**Comment by ransombriggs** [comment]
@singhakash sorry for the delayed response but I have not been able to reproduce the issue you encountered.  Could you please `set HEROKU_DEBUG=1` and try again and paste the output, the extra output should help me debug.

**Comment by singhakash** [comment]
It worked now . I am not sure but it might be the Procfile issue.
