### ISSUE TITLE
`heroku upgrade` exits with 1 when there are no plugins to upgrade

### ISSUE THREAD

**Issue by ghickman** [heroku/heroku#1923]
Running `heroku upgrade` with nothing to upgrade, like so:

```
$ heroku update
echo $heroku-cli: Updating plugins... ?no plugins to update.
 !    Use `brew upgrade heroku-toolbelt` to update
```

exists with a return code of 1.

Given no error has occurred, this seems like a bug to me.

**Comment by dickeyxxx** [comment]
this is now resolved
