### ISSUE TITLE
Problem to the symfony2.7 upload on heroku

### ISSUE THREAD

**Issue by coleccionista777** [heroku/heroku#1925]
Hello friends, I need your help with a problem to the symfony2.7 upload on heroku, I entered the command “git push heroku master” this is the error : 
https://drive.google.com/file/d/0BztswIqNuWoTQjA4enJzelM0dlU/view
Pd: I do not use Doctrine, however I'm connected directly to the BD
I hope you can help me.
Please excuse my limited English.

**Comment by dickeyxxx** [comment]
can you submit a support ticket? this is a project for the CLI
