### ISSUE TITLE
heroku redis:* commands don't work

### ISSUE THREAD

**Issue by denniscollective** [heroku/heroku#1929]
Hey, the docs say to use ```heroku redis:info```,

I just did: ```heroku addons:upgrade heroku-redis heroku-redis:premium-0```

and it told me to do ```heroku redis:wait``` which yields:

```
`redis:wait` is not a heroku command.
```

This could be because I installed heroku via gem install heroku, rather than the heroku toolbelt, or your docs are out of date.

I'm on the most recent heroku gem FWIW

**Comment by dickeyxxx** [comment]
it's because you're missing the heroku-redis plugin. I put an issue in to help make this more clear. https://github.com/heroku/heroku-cli/issues/253
