### ISSUE TITLE
Untrimmed logs

### ISSUE THREAD

**Issue by jmeas** [heroku/heroku#1942]
There should be an option to turn off log trimming when running `heroku local web`. That should probably even be the default.

[v2 of node-foreman](https://github.com/strongloop/node-foreman/blob/master/CHANGES.md#2016-04-30-version-200-1), for instance, now has trimming disabled by default.

**Comment by dickeyxxx** [comment]
yeah I submitted the PR to do that. It's out now, give it a shot.

**Comment by jmeas** [comment]
Oh awesome! Thanks @dickeyxxx ! I'll give it a try tonight. :v:

I suppose I'll go ahead and close this issue.
