### ISSUE TITLE
internal error from "heroku config"

### ISSUE THREAD

**Issue by lgmautner** [heroku/heroku#1947]
I'm getting the following error when calling `heroku config:get ...` as of ~5:30PM PST:

Heroku CLI submits usage information back to Heroku. If you would like to disable this, set `skip_analytics: true` in /home/ubuntu/.heroku/config.json
update in progress
update in progress
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku config:get <MY_ENV_VAR> -a <my-app-name>
    Version:     heroku-toolbelt/3.43.0 (x86_64-linux) ruby/1.9.3
    Error ID:    bcc0b23a063c44c1b2039ee97b2a1457

**Comment by dickeyxxx** [comment]
it says it's updating, just be patient

**Comment by lgmautner** [comment]
@dickeyxxx it says it's updating, but then I see a ruby error regarding "undefined method `[]' for nil:NilClass (NoMethodError)"

Was closing this issue premature? I'm re-running my build so I can check the logs
