### ISSUE TITLE
Heroku internal error when installing heroku-cli

### ISSUE THREAD

**Issue by odarino** [heroku/heroku#1959]
As a title, I've installed heroku-toolbelt, but when I run heroku.bat in \Heroku\bin, it still stands " installing CLI ... " for an hour and then throws a error. 
Here is my error log: 

Heroku client internal error. 
read timeout reached 
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:299:inraise_timeout_error'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:178:in rescue in read_nonblock' C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:165:inread_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:35:in read' C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/response.rb:148:inparse'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/response_parser.rb:6:in response_call' C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:372:inresponse'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:236:in request' C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon.rb:230:inget'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:147:in block (2 levels) in setup' C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:137:inopen'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:137:in block in setup' C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:inmktmpdir'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:135:in setup' C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:27:instart'
C:/Program Files (x86)/Heroku/bin/heroku:29:in <main>'

**Comment by ransombriggs** [comment]
@odarino are you behind a network proxy or have any firewall / antivirus software that prevents outbound connections?

**Comment by odarino** [comment]
I turned it off, including both firewall and antivirus ( avast btw ), but it still keep that screen.

**Comment by ransombriggs** [comment]
@odarino Do you get a progress bar at all?  Something like the following?
```
heroku-cli: Installing CLI... 21.02MB/21.02MB
```
Also, what happens if you try and download the following file manually (I am assuming you are on a 64 bit platform)
```
https://cli-assets.heroku.com/branches/stable/5.2.9-e9df6ac/heroku-v5.2.9-e9df6ac-windows-amd64.tar.gz
```

**Comment by odarino** [comment]
1. 
just 
> heroku-cli: Installing CLI...
2. I cant download this. I've tried it both IDM and browser.

**Comment by ransombriggs** [comment]
@odarino what error do you get in the browser?

**Comment by odarino** [comment]
@ransombriggs Nothing, just ... cant download this. Request time out.

**Comment by odarino** [comment]
Thanks to @ransombriggs . I've solved this problem. It's happened because my Internet confusingly connected to heroku server so slow ( the other's still fine ). Solution is to use a VPN app ( mine is Softether vpn client ).
