### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by BrunoQuaresma** [heroku/heroku#1961]
heroku create
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku create
    Version:     heroku-toolbelt/3.43.3 (x86_64-linux) ruby/2.2.2
    Error ID:    87dc922cc4a84b96ab17b7a996ae1490

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku login
    Version:     heroku-toolbelt/3.43.3 (x86_64-linux) ruby/2.2.2
    Error ID:    32f3c0e701054954b994fbb020189338

**Comment by vijayvaradan** [comment]
I get the same error on Ubuntu 16.04 LTS and ruby 2.3.0:

```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku login
    Version:     heroku-toolbelt/3.43.3 (x86_64-linux-gnu) ruby/2.3.0
    Error ID:    dd5e9c2dae2f4c97b7c5a5c71aa42b52

```
I've tried uninstalling and re-installing heroku and heroku-toolbelt to no avail.

**Comment by ransombriggs** [comment]
@BrunoQuaresma sorry for the delayed response, but @vijayvaradan suggestion will clean out all the heroku update and configuration files, which would give you a fresh installation and may fix your problem.  I should note however, that you would have to re-install any custom plugins that you have installed by hand.

**Comment by BrunoQuaresma** [comment]
@vijayvaradan it works! Thanks!

@ransombriggs maybe, this script can be add in the Ubuntu install doc.
