### ISSUE TITLE
i need help on this ive not been able to push into heroku 

### ISSUE THREAD

**Issue by adesinaadewale** [heroku/heroku#1967]
heroku keys:add
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/her

```
Error:       no implicit conversion of Fixnum into
Command:     heroku keys:add
Version:     heroku/toolbelt/3.43.2 (i386-mingw32)
Error ID:    2a0edd63559e4338b63ea67235c262a7


More information in C:/Users/USER/.heroku/error.log
```

**Comment by ransombriggs** [comment]
@adesinaadewale What is the value of `LOCALAPPDATA`?  Feel free to mask the username if you do not feel comfortable sharing it.

**Comment by adesinaadewale** [comment]
THANKS RANSOMBRIGGS, it worked
