### ISSUE TITLE
Command failed: ./main iTerm

### ISSUE THREAD

**Issue by ushuz** [heroku/heroku#1987]
Running `heroku` in iTerm2 results in following error. I'm using iTerm2 Build 2.1.4, on OSX 10.11.5.

![image](https://cloud.githubusercontent.com/assets/1430856/17081970/b2b0efca-519e-11e6-9ff3-c41d35f322a9.png)

While running `heroku` in Terminal is fine.

![heroku](https://cloud.githubusercontent.com/assets/1430856/17082006/12857366-51a0-11e6-82fe-a1e49fd90bad.png)

**Comment by dickeyxxx** [comment]
try updating your version of iterm to the latest

**Comment by ushuz** [comment]
@dickeyxxx Upgrading to iTerm2 3.0.5 solved the problem, thanks. So support for iTerm2 2.x has been dropped already?

**Comment by dickeyxxx** [comment]
I'm not sure what isn't working exactly. It's something with this library we use: https://github.com/sindresorhus/term-img/blob/master/index.js
