### ISSUE TITLE
Heroku client internal error when I try to run heroku create

### ISSUE THREAD

**Issue by develaper** [heroku/heroku#1988]
When I run heroku create that is the result:

!    Heroku client internal error.
!    Search for help at: https://help.heroku.com
!    Or report a bug at: https://github.com/heroku/heroku/issues/new

Error:       could not find a temporary directory (ArgumentError)
Command:     heroku create
Version:     heroku-toolbelt/3.43.7 (x86_64-linux) ruby/2.3.0
Error ID:    00f61fadb52f4517850b6d23bd74564d

And the content of my /.heroku/error.log file:

/usr/local/heroku/bin/heroku:25:in `<main>'
Heroku client internal error.
could not find a temporary directory
/home/ibrah/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:35:in `tmpdir'
/home/ibrah/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:106:in `tmpdir'
/home/ibrah/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:125:in `create'
/home/ibrah/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
/usr/local/heroku/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'

**Comment by dickeyxxx** [comment]
You don't have a temp directory configured. https://blog.diacode.com/fixing-temporary-dir-problems-with-ruby-2

**Comment by develaper** [comment]
it works perfect now.
Thanks a lot!!
