### ISSUE TITLE
pg_restore - server closed the connection unexpectedly

### ISSUE THREAD

**Issue by greedo** [heroku/heroku#1997]
while trying to do `heroku pg:pull DATABASE_URL app --app staging`

I am receiving the following internal error:
`error returned by PQputCopyData: server closed the connection unexpectedly
This probably means the server terminated abnormally before or while processing the request.`

<img width="901" alt="screen shot 2016-08-10 at 5 36 25 pm" src="https://cloud.githubusercontent.com/assets/410872/17572124/0d6f5b2e-5f21-11e6-8bf4-ecd82b2c8732.png">

I am pulling down the a copy of our staging database to a new travis ci build machine

**Comment by dickeyxxx** [comment]
this project is for the CLI but this is a server issue. Please submit a support ticket.
