### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by cmmartin** [heroku/heroku#2000]
I'm trying to push a Node.js application to Heroku. The app uses npm to fetch private github repositories, which are specified in `package.json`, like this...

```
"dependencies": {
    "my-private-dep": "github:my-org/my-repo"
}
```

The build fails during the `npm install` phase because the github host keys are not in the containers `known_hosts` file. 

```
remote:        npm ERR! Host key verification failed.
```

This is expected behavior of SSH. Does Heroku provide a workaround for this? For example, [dokku](https://github.com/dokku/dokku), which uses the same [buildpack](https://github.com/heroku/heroku-buildpack-nodejs) has a [host keys plugin](https://github.com/cedricziel/dokku-hostkeys-plugin) that will inject the host keys into the container before each build, which resolves this issue. Does Heroku have a similar solution?

**Comment by dickeyxxx** [comment]
This project is for the Heroku CLI only. Please submit a [support ticket](https://help.heroku.com/) for help with your application.

**Comment by cmmartin** [comment]
I'm not looking for help. I'm looking for a yes or no answer as to whether Heroku CLI provides a means to inject host keys into the container. It seems strange that it would support SSH keys, but not host keys. That's only half the battle. Anyway, I guess this isn't the forum for this kind of question.
