### ISSUE TITLE
Heroku CLI with Heroku Enterprise?

### ISSUE THREAD

**Issue by gjtorikian** [heroku/heroku#2002]
At work, we navigate to our Heroku apps hosted on Heroku Enterprise by first going through Okta. Is there any support for this through the CLI? I can't seem to authenticate with my Heroku Enterprise email address.

**Comment by ransombriggs** [comment]
@gjtorikian could you please try logging in with `heroku login --sso`?

**Comment by gjtorikian** [comment]
Yup, that did it! Thank you!
