### ISSUE TITLE
certificate expired..

### ISSUE THREAD

**Issue by stoffern** [heroku/heroku#2016]
https://git.heroku.com/
😆

**Comment by SanderMander** [comment]
I can't deploy because of that

fatal: unable to access '...': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

**Comment by ransombriggs** [comment]
@stoffern @SanderMander I am sorry that you are unable to deploy, I am following the status of the fix and will update when it should be working again.  If you want to, you can watch https://twitter.com/herokustatus for when it is fixed (as https://status.heroku.com/ appears to be affected as well)

**Comment by ransombriggs** [comment]
@stoffern The website has been fixed, thanks for letting us know about this

@SanderMander you may be able to deploy now, there were multiple sites affected and the incident is not fully resolved yet, but go ahead and try again.  The status site is available again at https://status.heroku.com/ and I will update once everything is fully working again.

**Comment by ransombriggs** [comment]
@SanderMander if you have not already tried yet, could you please retry your deploy?  Everything should be back to normal now.

**Comment by stoffern** [comment]
@ransombriggs working like a charm..
