### ISSUE TITLE
Unable to login into Heroku from terminal

### ISSUE THREAD

**Issue by nithinmannari** [heroku/heroku#2026]
When I am trying to login into the Heroku from my terminal it throws me the following error:

Post https://api.heroku.com/login: dial tcp: lookup api.heroku.com on 8.8.8.8:53: read udp 172.17.1.223:33433->8.8.8.8:53: i/o timeout

**Comment by nithinmannari** [comment]
I tried running the following commands but still none seem to work. Please help me with this.

rm ~/.heroku/heroku-cli`
heroku update
heroku version

**Comment by ransombriggs** [comment]
@nithinmannari This is most likely due to this ongoing incident https://status.heroku.com/incidents/965  What does `heroku version` output at this time?  If you have a working CLI, you could try the `/etc/hosts` fix that they suggest in the incident.

**Comment by nithinmannari** [comment]
@ransombriggs Thanks for replying firstly!! 

when I run just "heroku version" I am getting the version like this

heroku-toolbelt/3.43.12 (x86_64-linux) ruby/2.3.0
heroku-cli/5.2.39-010a227 (linux-amd64) go1.6.2
You have no installed plugins.

But when I run 

rm ~/.heroku/heroku-cli`
heroku update
heroku version

I am not getting any response. Please see the screenshots attached. Also can you please tell where I should add /etc/hosts to fix the issue ?
<img width="1220" alt="screen shot 2016-10-21 at 4 00 15 pm" src="https://cloud.githubusercontent.com/assets/14338021/19609866/9b325d9e-97a7-11e6-9857-ce82a523631c.png">
<img width="1244" alt="screen shot 2016-10-21 at 3 50 51 pm" src="https://cloud.githubusercontent.com/assets/14338021/19609868/9fb56906-97a7-11e6-877c-d7d8355a401b.png">

**Comment by ransombriggs** [comment]
@nithinmannari first you need to [log in as root](https://community.c9.io/t/super-user-root-in-terminal/2274) then edit `/etc/hosts` from the terminal, and add the following line.
```
151.101.45.6    status.heroku.com
54.225.188.133  api.heroku.com
50.16.189.161   help.heroku.com id.heroku.com dashboard.heroku.com devcenter.heroku.com
50.19.103.36    rendezvous.runtime.heroku.com
107.21.99.123   ssl-doctor.heroku.com
```
This is a temporary fix, and should be removed once the DNS outage has finished (I will update this issue when it is done)

**Comment by nithinmannari** [comment]
@ransombriggs I tried editing the /etc/hosts from the terminal after logging in as a super user, but it's telling that the permission is denied. Please find the screenshot attached.
<img width="877" alt="screen shot 2016-10-21 at 4 17 52 pm" src="https://cloud.githubusercontent.com/assets/14338021/19610351/17640046-97aa-11e6-82e7-1420eee0cece.png">

**Comment by ransombriggs** [comment]
@nithinmannari calling just `/etc/hosts` there means that the console will try and execute that file.  What you want to do is modify it with your editor, something like `vi` or `emacs` or whatever command line text editor you are comfortable with.

**Comment by nithinmannari** [comment]
@ransombriggs  I am new to Rails framework actually so sorry to bother you with my simple questions. Just one last thing. I am not able to locate the /etc/hosts file in my application. I tried searching every folder and sub folder.  Can you please me tell where can I find that to edit. Thanks.

<img width="367" alt="screen shot 2016-10-21 at 4 54 04 pm" src="https://cloud.githubusercontent.com/assets/14338021/19611328/3b588e72-97af-11e6-99f4-b484d35058a6.png">

**Comment by ransombriggs** [comment]
@nithinmannari `/etc/hosts` is a system file, not one from your project.  The files you see there in the dropdown are likely from `/home/ubuntu/workspace`.  Probably the easiest editor to use would be `nano` so if you go into the command line after did the sudo command and type `nano /etc/hosts` it should open the file for editing.  `nano` can be navigated by using the arrow keys and the keyboard commands along the bottom like `^X` are executed by holding control and pressing the corresponding letter.

**Comment by ransombriggs** [comment]
@nithinmannari the platform issue has been resolved, could you try removing the entries from `/etc/hosts` and trying again?

**Comment by nithinmannari** [comment]
Hi @ransombriggs 

It is working now. The issue has been resolved. Thanks a lot for the help. Really appreciate that.
