### ISSUE TITLE
JRuby Get Started Documentation Incorrect Cowsay Syntax

### ISSUE THREAD

**Issue by thomasjmwb** [heroku/heroku#2033]
https://devcenter.heroku.com/articles/getting-started-with-jruby#push-local-changes

Cowsay now takes a 'character' argument in addition to the message. Without specifying the type you get a number of arguments error

![image](https://cloud.githubusercontent.com/assets/1564699/20069036/d8e3c07e-a512-11e6-9c6d-9bea66f7a3f7.png)

**Comment by dickeyxxx** [comment]
This project is for the Heroku CLI only. Please submit a [support ticket](https://help.heroku.com/) for help with your application.
