### ISSUE TITLE
URGENT Timeout when connecting to DB

### ISSUE THREAD

**Issue by mkou** [heroku/heroku#2037]
Hey all, 

My app went down out of the blue. I dig a bit a realised it was a postgres timeout error. (This is a rails application)

In my heroku logs I have 
```
2016-11-21T17:42:05.540147+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=www.prynt.co request_id=8621956c-28d2-4bf3-b3c2-9e6473341674 fwd="73.162.26.168" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0
```

If I try to run db:migrate I get 

```
PG::ConnectionBad: could not connect to server: Connection timed out
	Is the server running on host "xxx.amazonaws.com" (54.204.xx.xx) and accepting
	TCP/IP connections on port 5432?
```

 heroku pg:diagnose gives me a  -> !    Couldn't finish job in time
Same issue when trying ``heroku pg:killall``

**Comment by ransombriggs** [comment]
@mkou could you please file a ticket at https://support.heroku.com/ this is for CLI support only and if you file a ticket, the appropriate team can better help you with your database issues.

**Comment by mkou** [comment]
Yes I did I was hoping to get help more quickly here. 
Thank you anyways!
