### ISSUE TITLE
Broken toolbelt release

### ISSUE THREAD

**Issue by jugutier** [heroku/heroku#2046]
Hi,
After spending two days trying to get this:https://s3.amazonaws.com/assets.heroku.com/heroku-toolbelt/heroku-toolbelt.pkg

to work on my computer I realized that brew installation works but this doesn't (gives segmentation fault on el-capitan and sierra). Please update the build on this link or only point to the brew installation guide. 

--J

**Comment by ransombriggs** [comment]
For others who may have encountered this issue when trying to install.  I was able to replicate this issue and reverted the installer to the previous version in order to stop this bug.  If you download from this link it should work now.

**Comment by ransombriggs** [comment]
@jugutier Thanks for reporting this issue, I reverted the release so that others do not encounter the bug.  Sorry for the inconvenience that it caused you.

**Comment by jugutier** [comment]
np @ransombriggs . Thanks for fixing it! While I have your attention, could I ask if it's possible to retrieve source code deployed on a dyno for which I have access but don't have access to the github repo that's linked to it?

**Comment by ransombriggs** [comment]
@jugutier https://devcenter.heroku.com/articles/git-clone-heroku-app

**Comment by jugutier** [comment]
you're the man! I had been trying that but with the wrong app name.. Closing issue now 👍
