### ISSUE TITLE
Additional tail filters

### ISSUE THREAD

**Issue by mmcgrana** [heroku/heroku#787]
(Bringing this over from another Heroku-internal tracker)

Currently the command line can filter logs to a specific process with `heroku logs tail --ps web.1`.  Consider support for other filters, such as dyno type (`heroku logs tail --ps web`) or multiple dynos / dyno types (`heroku logs --tail ps web,heroku-postgres`).

/cc @freeformz

**Comment by shirshendu** [comment]
The latest [release](https://github.com/heroku/heroku/releases/tag/v3.28.2) partially solves this.
Dyno type seems to work fine : `heroku logs tail --ps web`

multiple dynos/dyno types (`heroku logs --tail ps web,heroku-postgres`) do not work.
I don't think that is supported even at the [logplex filters level](https://github.com/heroku/logplex/blob/84fa341276a4cff561a10fb891d265b82578a45c/src/logplex_api.erl#L627-L637)

Is this still valid as an issue?

**Comment by freeformz** [comment]
We don't have any plans to support multiple --ps args atm. Filtering on the process type works fine.

I'm going to close this. If people want the feature of multiple filters and can make a case for it we can re-open.
