### ISSUE TITLE
Error:  Operation timed out - connect(2) (Errno::ETIMEDOUT)

### ISSUE THREAD

**Issue by ghost** [heroku/heroku#817]
Hi, I would just like to ask what could be the reason behind this error message whenever I'm doing a rake or entering rails console...

``Running `rails console` attached to terminal... up, run.7069
``Error:   Operation timed out - connect(2) (Errno::ETIMEDOUT)

Thank you.

**Comment by jgrau** [comment]
I realize that this issue is old, but as it is still open I will comment: See https://devcenter.heroku.com/articles/one-off-dynos#timeout-awaiting-process. I am experiencing the same thing. If I create a hotspot using my phone and connect to that hotspot from my computer everything works.

**Comment by dickeyxxx** [comment]
This happens if your internet connection (maybe due to firewall) can't access port 5000. You'll need to fix that on your end unfortunately.
