### ISSUE TITLE
Add ability to fork "public" apps

### ISSUE THREAD

**Issue by rwdaigle** [heroku/heroku#840]
From @trevorturk:

> This would be a great way to do something akin to the famous WordPress 5 Minute
> Install -- run these couple commands to have a forked live app on Heroku.

**Comment by trimble** [comment]
I agree, Something like ```heroku fork --from ruby-getting-started --to my-geting-started``` would be a nice kick-start for beginners. Maybe it plugs into https://devcenter.heroku.com/articles/getting-started-with-ruby#prepare-the-app somewhere?

However, right now that results in ```▸    You do not have access to the app ruby-getting-started.```

**Comment by dickeyxxx** [comment]
Right now there is no concept of a public app

**Comment by trevorturk** [comment]
Yes, the "Heroku Button" is wonderful!
