### ISSUE TITLE
Can't run heroku run rake

### ISSUE THREAD

**Issue by ttunguz** [heroku/heroku#881]
Can you help?

Running `rake twitter:update_followers` attached to terminal... up, run.3394
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Operation timed out - connect(2) (Errno::ETIMEDOUT)
    Backtrace:   /Users/Tomasz/.heroku/client/lib/heroku/client/rendezvous.rb:40:in `initialize'
                 /Users/Tomasz/.heroku/client/lib/heroku/client/rendezvous.rb:40:in `open'
                 /Users/Tomasz/.heroku/client/lib/heroku/client/rendezvous.rb:40:in `block in start'
                 /usr/local/heroku/ruby/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
                 /Users/Tomasz/.heroku/client/lib/heroku/client/rendezvous.rb:31:in `start'
                 /Users/Tomasz/.heroku/client/lib/heroku/command/run.rb:132:in `rendezvous_session'
                 /Users/Tomasz/.heroku/client/lib/heroku/command/run.rb:119:in `run_attached'
                 /Users/Tomasz/.heroku/client/lib/heroku/command/run.rb:24:in `index'
                 /Users/Tomasz/.heroku/client/lib/heroku/command.rb:206:in `run'
                 /Users/Tomasz/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/bin/heroku:24:in `<main>'

    Command:     heroku run rake twitter:update_followers
    Version:     heroku-toolbelt/2.40.0 (x86_64-darwin10.8.0) ruby/1.9.3

**Comment by shirshendu** [comment]
Were you able to resolve this, or this still a valid issue with the latest version of the heroku CLI?

**Comment by ttunguz** [comment]
Resolved!

**Comment by jvbreen1** [comment]
If this issue is resolved, it should probably be closed.
