### ISSUE TITLE
Heroku fork should have an option to skip postgres data migration

### ISSUE THREAD

**Issue by andrewsg** [heroku/heroku#911]
Heroku fork appears to be fragile and error-prone when dealing with very large postgres databases, which take a long time to migrate even if the process is successful.  It would be useful if there was an option to have fork skip database data migration but still do everything else.

Even if one assumes fork can be improved to succeed with large databases 100% of the time, it would be useful for people who will need to immediately de-provision the database and replace it with a different size once the fork is complete -- there is no need to make those users wait for the many hours it takes to migrate truly large data sets.

**Comment by dirkkelly** [comment]
This exists in the current implementation of fork `--skip-pg`

https://github.com/heroku/heroku-fork#heroku-fork-newname

Recommend this can be closed

**Comment by sailing** [comment]
Thanks @dirkkelly!
