### ISSUE TITLE
Add foreman to Linux standalone toolbelt

### ISSUE THREAD

**Issue by nderkach** [heroku/heroku#947]
When installing heroku toolbelt using guide from https://toolbelt.heroku.com/standalone foreman is not included.
It's present in all the other deliverables (at least for mac) and all you tutorial refer to it as it's supposed to be installed with the toolbelt. See heroku ticket #101227 for reference.

**Comment by Edo78** [comment]
After more than an year this issue is still opened ... Am I missing something? Is the standalone toolbelt supposed to have foreman included or not ?

**Comment by jpmolinamatute** [comment]
same problem in here

**Comment by dickeyxxx** [comment]
Use heroku local instead. We'll be removing foreman from all installs soon.
