### ISSUE TITLE
Problem running 'heroku run rake db:migrate"

### ISSUE THREAD

**Issue by praveenmakam2012** [heroku/heroku#958]
I have been trying a bunch of solutions put by experts online but couldnt get to deploy the app fully. Here is what I see when I execute "heroku run db console" or "heroku run rake db:migrate"

PRAX@PRAX-JERRY /c/users/prax/desktop/ror/samapp (master)
$ heroku run rails console
Running `rails console` attached to terminal... up, run.4425
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed becau
se connected host has failed to respond. - connect(2) (Errno::ETIMEDOUT)
    Backtrace:   C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `initialize'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `open'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `block in start'
                 d:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:68:in `ti
meout'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:31
:in `start'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:125:in `
rendezvous_session'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:112:in `
run_attached'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:21:in `i
ndex'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command.rb:207:in `run'

                 C:/Users/PRAX/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 c:/Program Files (x86)/Heroku/bin/heroku:24:in `<main>'

    Command:     heroku run rails console
    Version:     heroku/toolbelt/2.33.5 (i386-mingw32) ruby/1.9.3

PRAX@PRAX-JERRY /c/users/prax/desktop/ror/samapp (master)
$ telnet rendezvous.runtime.heroku.com 5000
sh.exe": telnet: command not found
PRAX@PRAX-JERRY /c/users/prax/desktop/ror/samapp (master)
$ heroku run bash
Running `bash` attached to terminal... up, run.7574
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed becau
se connected host has failed to respond. - connect(2) (Errno::ETIMEDOUT)
    Backtrace:   C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `initialize'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `open'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:39
:in `block in start'
                 d:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:68:in `ti
meout'
                 C:/Users/PRAX/.heroku/client/lib/heroku/client/rendezvous.rb:31
:in `start'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:125:in `
rendezvous_session'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:112:in `
run_attached'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command/run.rb:21:in `i
ndex'
                 C:/Users/PRAX/.heroku/client/lib/heroku/command.rb:207:in `run'

                 C:/Users/PRAX/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 c:/Program Files (x86)/Heroku/bin/heroku:24:in `<main>'

    Command:     heroku run bash
    Version:     heroku/toolbelt/2.33.5 (i386-mingw32) ruby/1.9.3

Someone, Could you please help me understand & fix this issue? thx.

**Comment by uhoh-itsmaciek** [comment]
This might be a firewall issue. You could try running with `run:detached` instead to avoid that. If that works, that's probably it. You can add the `--tail` flag to get log output as well. The semantics are slightly different, but probably close enough for a `db:migrate`. Let us know if that doesn't work around it.
